### ISSUE TITLE
Can't build log-courier on FreeBSD 10 

### ISSUE THREAD

**Issue by dsolsona** [driskell/log-courier#1]
Hi, 

I'm getting the following error when trying to build it under FreeBSD 10 (adm64)

```
# make with=zmq
make: "/usr/home/daniel/log-courier/Makefile" line 9: Missing dependency operator
make: "/usr/home/daniel/log-courier/Makefile" line 13: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /usr/home/daniel/log-courier
```

I can run go build inside src/log-courier and it compiles the binary, so I guess this is just a problem with the Makefile.

Running it with gmake throws the following error:

```
gmake: *** No rule to make target `bin/log-courier', needed by `all'.  Stop.
```

**Comment by trombonehero** [comment]
This is related to https://github.com/golang/go/issues/10453: `cgo` sets `-ferror-limit=0` when it knows that it's using Clang, but on FreeBSD it doesn't understand that `/usr/bin/cc` is Clang.
