### ISSUE TITLE
Failed to initialise when unix socket exists

### ISSUE THREAD

**Issue by blalor** [driskell/log-courier#101]
Got the following after killing log-courier to report the previous issue:

```
Failed to initialise: listen unix /var/run/log-courier/admin.socket: bind: address already in use
```

No other lc instance was running. I removed the socket file manually and lc was able to start.

**Comment by driskell** [comment]
Thanks for the report.

Good spot. It should be removing any existing socket file before Listening as existence of the file (even if nothing on the other end) is treated as "already in use". I'll fix it shortly.

Jason

**Comment by driskell** [comment]
I've pushed a fix to the develop branch. If you could verify it works for you that will be great.

**Comment by blalor** [comment]
Ok, this works as intended!

**Comment by driskell** [comment]
Thanks for checking.
