### ISSUE TITLE
Please log line number when reporting config errors.

### ISSUE THREAD

**Issue by xtimmu** [driskell/log-courier#102]
Current behaviour:
Configuration error: invalid character ']' after object key:value pair

Uhuh... And which ] is that?

Expected behaviour:

Configuration error: invalid character ']' after object key:value pair on line 678 (..near character?)...

Oh... Now I see!

**Comment by driskell** [comment]
Hi @xtimmu,

Thanks for the request. It's a good one. I actually was meaning to look into this in detail as it's a golang language feature we use for JSON decoding and we simply return the error from it. Looks like we can get more detailed information.

Just for my reference, some information on how we can do this is here:
https://groups.google.com/forum/#!topic/golang-nuts/fizimmXtVfc

I'll likely not get around to this for 1.4 though but it's here in case anyone wants to send a pull request this way. I'll update when I start work on this.

Jason
