### ISSUE TITLE
Importing log-courier data streams into fluentd

### ISSUE THREAD

**Issue by josh-padnick** [driskell/log-courier#117]
Hello, I realize this is more of a fluentd question than a log-courier question, but I was wondering if fluentd supports reading in log data from log-courier agents?

The reason I ask is because we are deploying log-courier across hundreds of instances here in our AWS cluster, and the word on the street is that fluentd supports much better performance than logstash.  While we can't justify a switch to logstash right now, I wanted to know if using log-courier will support a seamless transition down the line.

If no fluentd plugin exists, is there a plan by the author to write one?  

Thank you for this awesome plugin!  It has been a pleasure to work with so far.

**Comment by driskell** [comment]
Hi @josh-padnick 

Log Courier has its own improved protocol so it's not going to work with fluentd without a plugin.

Having said that fluentd is ruby based and the protocol library for Log Courier is a gem so writing a fluentd plugin should be relatively straight forward as all the hard graft is taken care of in the gem and won't need rewriting or anything.

I'm not a fluentd user though so it's not something I'd be able to test easily without investing some time, which I don't really have at the moment in afraid.

I would say a Ruby person would be able to translate the Logstash plugin to a Fluentd one fairly quickly though without my help. It's just the testing and maintaining to consider.

Jason

**Comment by driskell** [comment]
Regarding plans for a plugin. I have none at the moment. But as I said maybe someone else could offer one?

**Comment by josh-padnick** [comment]
@driskell Thanks for the prompt response.  That's good to know.  Just to be clear, we would not even use such a plugin just yet.  Really, I was interested in the business question of "how long would it take to switch to fluentd if we needed to in the future?"

It'd be interesting to see if there is any other interest for such a plugin.

**Comment by driskell** [comment]
How long it would take for a Business to switch to fluentd I have no idea. How long it would take myself, or a competent Ruby developer to make a Courier input plugin for fluentd - I would say a few days of spare time, assuming the necessary test systems are available.

I don't currently have a plans though, and don't have any fluentd test systems, everything is ELK.

Rather than close as Won't Fix, I'll leave this open for a bit longer in case anyone else spots it, and mark Help Wanted. Who knows maybe someone already has done something here.

**Comment by driskell** [comment]
The protocol is documented now in master branch at docs/Protocol.md if anyone does come to implement such a plugin for fluentd! Will close now.
