### ISSUE TITLE
Unexpected registrar conflict detected

### ISSUE THREAD

**Issue by scratch-net** [driskell/log-courier#122]
Got this today on console (windows)
2015/02/24 04:15:30.942901 BUG: Unexpected registrar conflict detected for d:\logz\my-log.1.txt

After I shutdown Courier it said it had 2 harversters for log.1.txt

I have rule to keep 2 archives of my logs and rotate them every hour thus having log.txt, log.0.txt and
log.1.txt
I will run it for some time more and let you know more conrete courier logs (will save them to file)

**Comment by scratch-net** [comment]
So, here they are:

2015/02/24 05:29:29.073626 Error prospecting d:\logz\my-log.1.txt: GetFileAttributesEx d:\logz\my-log.1.txt: Access is denied.
2015/02/24 05:29:39.074898 Error prospecting d:\logz\my-log.1.txt: GetFileAttributesEx d:\logz\my-log.1.txt: Access is denied.
2015/02/24 05:29:49.076179 Error prospecting d:\logz\my-log.1.txt: GetFileAttributesEx d:\logz\my-log.1.txt: Access is denied.
2015/02/24 05:29:59.077443 Error prospecting d:\logz\my-log.1.txt: GetFileAttributesEx d:\logz\my-log.1.txt: Access is denied.
2015/02/24 05:30:00.668645 Stopping harvest of d:\logz\my-log.txt; last change was 30m0s ago
2015/02/24 05:30:09.007699 Stopping harvest of d:\logz\my-log.0.txt; last change was 30m0s ago
2015/02/24 05:30:09.078709 Registrar received a deletion event for UNKNOWN (0xc082054000)
2015/02/24 06:00:09.195498 File rename was detected: d:\logz\my-log.txt -> d:\logz\my-log.0.txt
2015/02/24 06:00:09.195498 File rename was detected: d:\logz\my-log.0.txt -> d:\logz\my-log.1.txt
2015/02/24 06:00:09.195498 Launching harvester on new file: d:\logz\my-log.txt
2015/02/24 06:00:09.195498 Started harvester at position 0 (requested 0): d:\logz\my-log.txt
2015/02/24 06:00:09.196502 BUG: Unexpected registrar conflict detected for d:\logz\my-log.1.txt
2015/02/24 06:00:09.602543 BUG: Unexpected registrar conflict detected for d:\logz\my-log.1.txt
2015/02/24 06:00:10.521664 BUG: Unexpected registrar conflict detected for d:\logz\my-log.1.txt
2015/02/24 06:00:11.645806 BUG: Unexpected registrar conflict detected for d:\logz\my-log.1.txt
2015/02/24 06:00:11.959847 BUG: Unexpected registrar conflict detected for d:\logz\my-log.1.txt
2015/02/24 06:00:12.680941 BUG: Unexpected registrar conflict detected for d:\logz\my-log.1.txt
2015/02/24 06:00:13.877090 BUG: Unexpected registrar conflict detected for d:\logz\my-log.1.txt
2015/02/24 06:00:14.281143 BUG: Unexpected registrar conflict detected for d:\logz\my-log.1.txt

**Comment by driskell** [comment]
Can you confirm your version?

  log-courier -version

**Comment by scratch-net** [comment]
I've built it from 1.3 stable branch

**Comment by driskell** [comment]
I've found the problem. I merge the fix in the next few days.

**Comment by scratch-net** [comment]
Fantastic, it seems to be working!

**Comment by driskell** [comment]
Fixed by #124 (I mislabeled the commit - whoopsy!)
Thanks for confirming it works!
