### ISSUE TITLE
Identity parameter in multiline codec

### ISSUE THREAD

**Issue by pvshewale** [driskell/log-courier#125]
Is is possible to have specify identity in multiline codec? I have a log which generated multiline log which is associated to single event. If multiple events are genarated at same time, log lines gets mixed. But each log line contains unique session id using which I can confirm the line belong to which event.

The format of log is something as below,

2014-08-26 07:54:13.662413500 20028: *** session start ***
2014-08-26 07:54:13.662415500 20028: Remote IP: 198.18.71.30
2014-08-26 07:54:13.662415500 20028: Message reference: 1409039653!20028!1
2014-08-26 07:54:13.750761500 20028: - relayclient is set
2014-08-26 07:54:14.598071500 20028: *** session end ***

In above example "20028" is unique session id. Using multiline codec I am waiting till "*** session end ***", but in case of mixed lines for multiple parallel events, it does not work as expected. The example of mixed line will be something as below,

2014-08-26 07:54:13.662413500 20028: *** session start ***
2014-08-26 07:54:13.662415500 20028: Remote IP: 198.18.71.30
2014-08-26 07:54:13.662413500 20029: *** session start ***
2014-08-26 07:54:13.662415500 20029: Remote IP: 198.18.71.30
2014-08-26 07:54:13.662415500 20028: Message reference: 1409039653!20028!1
2014-08-26 07:54:13.750761500 20028: - relayclient is set
2014-08-26 07:54:14.598071500 20028: *** session end ***
2014-08-26 07:54:13.662415500 20029: Message reference: 1409039673!20029!1
2014-08-26 07:54:13.750761500 20029: - relayclient is set
2014-08-26 07:54:14.598071500 20029: *** session end ***

While using logstash, I achieved this using multiline filter in logstash which has "stream_identity" parameter. But while shipping logs from multiple servers to single logstash indexer we are facing performance issue in multiline filter of logstash. So looking to have something similar in log-courier itself.

**Comment by driskell** [comment]
Hi @pvshewale

This would require Log Courier to parse the event lines and hold multiple active buffers for multiple pending sessions. As it stands there's no plan for this, the current goal is just to work with lines of data and not need to parse it. Logstash is far better placed for parsing and I don't intend to replace it.

In this kind of scenario though I feel multiline is the wrong approach. If the data was meant to be together the application should print it together (as with stack traces etc which multiline works with). But as they are separate I would say they should be shipped and stored separately and data analysis used to bring these related events together. So these are related events, not part of the same event, and as such I believe multiline isn't the approach to take.

Stream identity in Logstash is intended to isolate multiple file streams in the case of reading from multiple files so the multiline applies to independent file streams (and doesn't mix them). Though it kind of works for this I think it's more of a side effect.

It's definitely a problem that would be useful to have a full solution to but I think it may be at the analysis side.

**Comment by driskell** [comment]
As this is quite a complex thing to do RIGHT (there are ways like stream identity that can work in some cases - but I don't think it's the RIGHT way) - I'll mark this Won't Fix for now. Any ideas are welcome though - but I feel on the analysis side it's probably wiser, or to change the data source output.

Complexity in stream identity comes from:
1. How many streams max to monitor for a single file? (Memory control)
1. How long to keep a stream active? (Memory control)
1. We remember where we left off when we restart - what if some logs sent and some not due to end of multiline not met? (Delivery guarantee)
