### ISSUE TITLE
document difference with LSF

### ISSUE THREAD

**Issue by zabbal** [driskell/log-courier#126]
It's nice to see overall feature description but would be handy to get a better understanding of what differes courier from forwarder? Preferably both in terms of goals and already implemented features.

**Comment by driskell** [comment]
@zabbal Yes absolutely.

I need to update features and trim it down to key points. And a goal section is a really good idea.
A difference section I can see is now important. When I started this project LSF was unmaintained (imho) but now work has started again theres going to be some divergence

For now if anyone needs a quick overview looking at the Change Log way back to the beginning is a good start. It lists the original inherent issues I had with LSF that led to Log Courier's birth.

**Comment by driskell** [comment]
This has been completed in the latest README.md
