### ISSUE TITLE
Cannot install log-courier in Freebsd 9.2

### ISSUE THREAD

**Issue by juangarciavargas** [driskell/log-courier#130]
Hi there,

I'm having trouble installing log_courier, here the errors:

root@server ~ # git clone https://github.com/driskell/log-courier
Cloning into 'log-courier'...
remote: Counting objects: 6733, done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 6733 (delta 44), reused 0 (delta 0), pack-reused 6639
Receiving objects: 100% (6733/6733), 1.51 MiB | 476.00 KiB/s, done.
Resolving deltas: 100% (4093/4093), done.
Checking connectivity... done.
root@server ~ # cd log-courier/
root@server ~/log-courier # gmake
build/fix_version ""
build/fix_version: not found
Makefile:103: recipe for target 'fix_version' failed
gmake: *** [fix_version] Error 127
root@server ~/log-courier # gmake -v
GNU Make 4.1
Built for amd64-portbld-freebsd9.2
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
root@server ~/log-courier # uname -a
FreeBSD server.internal 9.2-RELEASE FreeBSD 9.2-RELEASE #0 r255898: Thu Sep 26 22:50:31 UTC 2013     root@bake.isc.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by driskell** [comment]
Can you run "build/fix_version" manually?
Failing that, "./build/fix_version".

If you can let me know results it will help.
I wonder if using "./build/fix_version" in Makefile will fix it but I still would like to know results of the above run from the shell manually.

Thanks

**Comment by driskell** [comment]
@juangarciavargas Were you able to try the above?

**Comment by driskell** [comment]
Will close due to no response. If the problem happens again (or for anyone else) it'll be good to find out why, as I'm unable to test on this distribution myself.
