### ISSUE TITLE
Transport error, will try again: EOF

### ISSUE THREAD

**Issue by jmreicha** [driskell/log-courier#131]
Attempting to get log-courier working in a Docker container but am seeing the following errors over and over again.  Is there a way to debug these errors or is there something that can be done to help narrow down what the problem is?

I am using this to build the debian package and then install it in to the container.

https://registry.hub.docker.com/u/arep/log-courier/

I double checked, the version of log-courier is 1.5.  I am using logstash 1.5 with the log-courier plugin installed.

```
/var/log# /opt/log-courier/bin/log-courier -config /etc/log-courier
2015/03/04 17:22:27.791143 Log Courier version 1.5 pipeline starting
2015/03/04 17:22:27.791245 Pipeline ready
2015/03/04 17:22:27.805441 Launching harvester on new file: /var/log/bootstrap.log
2015/03/04 17:22:27.805751 Started harvester at position 33874 (requested 33874): /var/log/bootstrap.log
2015/03/04 17:22:27.824201 Attempting to connect to IP:4545 (server)
2015/03/04 17:22:27.970179 Connected to IP:4545 (server)
2015/03/04 17:22:27.970323 Transport error, will try again: EOF
2015/03/04 17:22:29.002857 Attempting to connect to IP:4545 (server)
2015/03/04 17:22:29.229661 Connected to IP:4545 (server)
2015/03/04 17:22:29.302225 Transport error, will try again: EOF
2015/03/04 17:22:30.322644 Attempting to connect to IP:4545 (server)
2015/03/04 17:22:30.569282 Connected to IP:4545 (server)
2015/03/04 17:22:30.569345 Transport error, will try again: EOF
2015/03/04 17:22:31.391193 Initiating shutdown
2015/03/04 17:22:31.391239 Spooler exiting
2015/03/04 17:22:31.391252 Harvester for /var/log/bootstrap.log exiting
2015/03/04 17:22:31.391278 Prospector exiting
2015/03/04 17:22:31.590065 Attempting to connect to IP:4545 (server)
2015/03/04 17:22:31.846661 Connected to IP:4545 (server)
2015/03/04 17:22:31.846880 Publisher exiting
2015/03/04 17:22:31.846897 Registrar exiting
2015/03/04 17:22:31.846913 Exiting
```

**Comment by driskell** [comment]
Is Logstash listening on port 4545? What's your Logstash configuration?

EOF means the remote side is closing the connection as soon as it receives data. In the Log Courier case it will be Logstash input plugin closing the connection (or a router/load balancer in-between them.)

**Comment by jmreicha** [comment]
I found this - https://github.com/driskell/log-courier/issues/16

Which got me looking at the Logstash configs, which is where I think my issue is.  I have lumberjack running on port 4545 and courier on 4546 on the Logstash server but am having trouble getting Logstash to actually open up the port.

I am looking for an example of how to do it correctly but this is what my conifg looks like right now:

```
input {
    lumberjack {
        port => 4545
        ssl_certificate => "/etc/logstash/logstash.crt"
        ssl_key => "/etc/logstash/logstash.key"
        codec => plain {
                charset => "ISO-8859-1"
        }
    }
}

input {
    courier {
        port => 4546
        ssl_certificate => "/etc/logstash/logstash.crt"
        ssl_key => "/etc/logstash/logstash.key"
    }
}
```

**Comment by driskell** [comment]
You can put them both in the same input stanza. When you start logstash it should report it is loading courier plugin. How do you know it's not opened the port? Via `netstat -lnpt`?

You could also run logstash with "-v" I think as a parameter and it will enable debug logging. Best to use for testing only though as it'll print out the logs it receives.

**Comment by jmreicha** [comment]
@driskell I did notice that logstash says it is loading up the courier plugin from its output.  The way I was checking the ports was with netcat from the host that I am attempting to get log courier working on.  I am able to hit the lumberjack port but not the new courier port (4546).

I haven't tried running Logstash with -v yet so that sounds like a good next step.

**Comment by jmreicha** [comment]
I spoke too soon, I made a stupid mistake.  I didn't expose the newly configured port in Docker so nothing could connect from the outside world.

**Comment by jmreicha** [comment]
That error seemed to only occur once so I won't worry about it for now.  I will revisit if it crops up again.
