### ISSUE TITLE
Transport error, will try again: Server did not respond within network timeout

### ISSUE THREAD

**Issue by jmreicha** [driskell/log-courier#132]
I don't know if I have it narrowed down at all but I feel like I have made some progress.  I am able to reproduce this error when I get a "bad log" which I am thinking the log-courier client (or server) either can't understand or doesn't know what to do with.

Have you ever seen an issue like this where a log with bad data would cause the client to blow up?

```
Transport error, will try again: Server did not respond within network timeout
2015/03/05 20:36:49.829733 Attempting to connect to 50.16.224.136:4546 (logstash_server)
2015/03/05 20:36:50.216789 Connected to 50.16.224.136:4546 (logstash_server)
2015/03/05 20:37:05.217018 Transport error, will try again: Server did not respond within network timeout
2015/03/05 20:37:06.220811 Attempting to connect to 50.16.224.136:4546 (logstash_server)
2015/03/05 20:37:06.597048 Connected to 50.16.224.136:4546 (logstash_server)
2015/03/05 20:37:21.597681 Transport error, will try again: Server did not respond within network timeout
2015/03/05 20:37:22.602386 Attempting to connect to 50.16.224.136:4546 (logstash_server)
2015/03/05 20:37:22.997631 Connected to 50.16.224.136:4546 (logstash_server)
```

EDIT:  More info

Here are the logs on the logstash server side.  I noticed that it is spitting out a new error every 8 seconds.

```
logstash_1      | {:timestamp=>"2015-03-05T23:11:43.032000+0000", :message=>"Connection timed out", :peer=>"LOGSTASH_IP:19795", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
logstash_1      | {:timestamp=>"2015-03-05T23:11:51.436000+0000", :message=>"Connection timed out", :peer=>"LOGSTASH_IP:56983", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
logstash_1      | {:timestamp=>"2015-03-05T23:11:59.426000+0000", :message=>"Connection timed out", :peer=>"LOGSTASH_IP:36100", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
logstash_1      | {:timestamp=>"2015-03-05T23:12:07.791000+0000", :message=>"Connection timed out", :peer=>"LOGSTASH_IP:36408", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
logstash_1      | {:timestamp=>"2015-03-05T23:12:15.805000+0000", :message=>"Connection timed out", :peer=>"LOGSTASH_IP:62101", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
```

EDIT 2:

More info, hopefully it is helpful.  Just for kicks I decided to change the input type on the Logstash server to "tcp" so the configuration looks like the following.

```
courier {
        transport => tcp
        port => 4546
    }
```

Now am seeing the following error on Logstash side of things.

```
logstash_1      | {:timestamp=>"2015-03-06T02:25:41.868000+0000", :message=>"Protocol error, connection aborted", :error=>"packet too large (2298544128 > 10485760)", :peer=>"CLIENT_IP:59991", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
logstash_1      | {:timestamp=>"2015-03-06T02:25:43.038000+0000", :message=>"Protocol error, connection aborted", :error=>"packet too large (2298544128 > 10485760)", :peer=>"CLIENT_IP:2831", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
logstash_1      | {:timestamp=>"2015-03-06T02:25:44.208000+0000", :message=>"Protocol error, connection aborted", :error=>"packet too large (2298544128 > 10485760)", :peer=>"CLIENT_IP:35429", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
logstash_1      | {:timestamp=>"2015-03-06T02:25:45.376000+0000", :message=>"Protocol error, connection aborted", :error=>"packet too large (2298544128 > 10485760)", :peer=>"CLIENT_IP:38291", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
logstash_1      | {:timestamp=>"2015-03-06T02:25:46.559000+0000", :message=>"Protocol error, connection aborted", :error=>"packet too large (2298544128 > 10485760)", :peer=>"CLIENT_IP:30707", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
logstash_1      | {:timestamp=>"2015-03-06T02:25:47.739000+0000", :message=>"Protocol error, connection aborted", :error=>"packet too large (2298544128 > 10485760)", :peer=>"CLIENT_IP:51227", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
```

I can post a packet dump from either the client or server if it helps with the debugging info, I am not super great with the networking but don't really see what else to look at.

**Comment by driskell** [comment]
What version of Log Courier are you using? And what's your Log Courier general/network configuration? Can you enable "log level": "debug" in the general configuration section and provide the output from Log Courier?

Unless there's some corruption going on somewhere, 2298544128 is a very large packet. Early versions were like Logstash Forwarder, with no limits on line lengths from files - so if you hit a large line it could eat huge memory, send it all over, and crash the JVM hosting Logstash. Latest versions have sane limits though so 2298544128 should never ever happen (it'll split the line up into chunks, and tag them as "partial" so you can find them in elasticsearch etc.)

**Comment by driskell** [comment]
Regarding the 2298544128 - did you change the Log Courier to send using "tcp" too? Or was it still "tis"? That would explain corruption.

If you could grab logs from both sides at the same time that would be good to correlate the timeout on Log Courier with the timeout on Logstash. If you could correlate the :peer part too to the Log Courier instance that'll help too.

**Comment by jmreicha** [comment]
@driskell thanks.  I only got the over sized packets when I changed the config to use TCP.  I'll turn on debugging and see if that can help me gather some clues.

**Comment by jmreicha** [comment]
Another thing I hadn't thought of until now, which I am starting to think may come in to play here is that all my traffic is being proxied through a public NAT instance in AWS.  Could that be related?

**Comment by jmreicha** [comment]
Here's what I've got so far, sorry I haven't had much time lately to look.  This is on 1.5.0.beta1.

Logstash server (debug turned on):

```
{:timestamp=>"2015-03-20T17:06:30.539000+0000", :message=>"Failed to flush outgoing items", :outgoing_count=>199, :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.9-java/lib/logstash/outputs/elasticsearch.rb:446:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.9-java/lib/logstash/outputs/elasticsearch.rb:444:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.9-java/lib/logstash/outputs/elasticsearch.rb:442:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1501:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn, :file=>"stud/buffer.rb", :line=>"231", "plugin"=>"input/courier", "port"=>4546}
{:timestamp=>"2015-03-20T17:06:31.540000+0000", :message=>"Failed to flush outgoing items", :outgoing_count=>199, :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.9-java/lib/logstash/outputs/elasticsearch.rb:446:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.9-java/lib/logstash/outputs/elasticsearch.rb:444:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.1.9-java/lib/logstash/outputs/elasticsearch.rb:442:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1501:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn, :file=>"stud/buffer.rb", :line=>"231", "plugin"=>"input/courier", "port"=>4546}
```

Log courier client:

```
2015/03/20 17:07:05.581615 ACKN message received for payload 8b6056077ac98cb6cd845aa095d1138f sequence 2
2015/03/20 17:07:05.581654 2 payloads still pending, resetting timeout
2015/03/20 17:07:10.582739 ACKN message received for payload 8b6056077ac98cb6cd845aa095d1138f sequence 2
2015/03/20 17:07:10.582780 2 payloads still pending, resetting timeout
2015/03/20 17:07:15.583929 ACKN message received for payload 8b6056077ac98cb6cd845aa095d1138f sequence 2
2015/03/20 17:07:15.583970 2 payloads still pending, resetting timeout
2015/03/20 17:07:20.584914 ACKN message received for payload 8b6056077ac98cb6cd845aa095d1138f sequence 2
2015/03/20 17:07:20.584954 2 payloads still pending, resetting timeout
2015/03/20 17:07:25.586152 ACKN message received for payload 8b6056077ac98cb6cd845aa095d1138f sequence 2
2015/03/20 17:07:25.586171 2 payloads still pending, resetting timeout
2015/03/20 17:07:30.587513 ACKN message received for payload 8b6056077ac98cb6cd845aa095d1138f sequence 2
```

**Comment by driskell** [comment]
That might be a bug in the elastic search output when using debug mode (which doesn't help us!). When you restart Logstash, can you find the line: "New Elasticsearch output" and provide it? It'll confirm if this is a debugging bug in the elastic search output or not.

The Log Courier output is good - it means the server is responding but without any progress, meaning the Logstash pipeline is frozen/stalled. Probably, in this case, due to the potential elastic search output bug.

**Comment by jmreicha** [comment]
I completely shut off the lumberjack input and debugging on the logstash server and so far things have been much more stable running everything through Log Courier so I suspect my issues were mostly related to the Logstash server lumberjack input at this point.

I am shutting off lumberjack clients one at a time right now and moving them to Log Courier and will update when I get more clients moved but so far so good!

If this works I will just drop lumberjack everywhere.  Have you ever run in to a client limit for Log Courier?

**Comment by jmreicha** [comment]
Just an update, servers that are connecting to the Logstash server through their own public IP seem to be working perfectly but when I start adding in network layers I experience problems.  Direct connect from a public IP is ok but servers that are proxying through a NAT server are having problems.

Here is the client debug from an internal host that is running through the NAT.

```
2015/03/21 02:32:28.281691 Log Courier version 1.5 pipeline starting
2015/03/21 02:32:28.281772 Pipeline ready
2015/03/21 02:32:28.282696 Attempting to connect to 50.16.224.136:4546 (logstash.abtm.io)
2015/03/21 02:32:28.282816 Launching harvester on new file: /data/access.http.log
2015/03/21 02:32:28.282849 Launching harvester on new file: /data/access.log
2015/03/21 02:32:28.282866 Launching harvester on new file: /data/access.ssl.log
2015/03/21 02:32:28.282883 Launching harvester on new file: /data/error.log
2015/03/21 02:32:28.283018 Started harvester at position 105928 (requested 105928): /data/access.http.log
2015/03/21 02:32:28.283368 Started harvester at position 870 (requested 870): /data/access.log
2015/03/21 02:32:28.283412 Started harvester at position 5182381453 (requested 5182381453): /data/access.ssl.log
2015/03/21 02:32:28.283455 Started harvester at position 197773166 (requested 197773166): /data/error.log
2015/03/21 02:32:28.283483 Registrar received a new file event for /data/access.http.log
2015/03/21 02:32:28.283501 Registrar received a new file event for /data/access.log
2015/03/21 02:32:28.283517 Registrar received a new file event for /data/access.ssl.log
2015/03/21 02:32:28.283534 Registrar received a new file event for /data/error.log
2015/03/21 02:32:33.282962 Spooler flushing 18 events due to spool timeout exceeded
2015/03/21 02:32:38.283174 Spooler flushing 21 events due to spool timeout exceeded
2015/03/21 02:32:43.282932 Transport init failed: Failed to connect to 50.16.224.136:4546 (logstash.domain.com): dial tcp 50.16.224.136:4546: i/o timeout
2015/03/21 02:32:44.283812 Attempting to connect to 50.16.224.136:4546 (logstash.domain.com)
2015/03/21 02:32:59.284071 Transport init failed: Failed to connect to 50.16.224.136:4546 (logstash.domain.com): dial tcp 50.16.224.136:4546: i/o timeout
2015/03/21 02:33:00.285038 Attempting to connect to 50.16.224.136:4546 (logstash.domain.com)
2015/03/21 02:33:15.285348 Transport init failed: Failed to connect to 50.16.224.136:4546 (logstash.domain.com): dial tcp 50.16.224.136:4546: i/o timeout
2015/03/21 02:33:16.286209 Attempting to connect to 50.16.224.136:4546 (logstash.domain.com)
2015/03/21 02:33:31.286473 Transport init failed: Failed to connect to 50.16.224.136:4546 (logstash.domain.com): dial tcp 50.16.224.136:4546: i/o timeout
2015/03/21 02:33:32.287310 Attempting to connect to 50.16.224.136:4546 (logstash.domain.com)
2015/03/21 02:33:47.287571 Transport init failed: Failed to connect to 50.16.224.136:4546 (logstash.domain.com): dial tcp 50.16.224.136:4546: i/o timeout
2015/03/21 02:33:48.292984 Attempting to connect to 50.16.224.136:4546 (logstash.domain.com)
2015/03/21 02:34:03.293257 Transport init failed: Failed to connect to 50.16.224.136:4546 (logstash.domain.com): dial tcp 50.16.224.136:4546: i/o timeout
2015/03/21 02:34:04.294063 Attempting to connect to 50.16.224.136:4546 (logstash.domain.com)
```

**Comment by driskell** [comment]
Dial timeout is connect failure. Can you verify connectivity using telnet? Might be a firewall blocking it.

**Comment by driskell** [comment]
Regarding client limit - I've not hit one yet but I've only gone to 100-200 myself. A thread is started in Logstash for each input though so I would guess that will hit a limit at some point (I think max 1024 on a process by default on most system so allowing for other logstash threads maybe 800-900)

**Comment by jmreicha** [comment]
Thanks, I will test port connectivity and post my findings.

On Friday, March 20, 2015, Jason Woods <notifications@github.com> wrote:

> Regarding client limit - I've not hit one yet but I've only gone to
> 100-200 myself. A thread is started in Logstash for each input though so I
> would guess that will hit a limit at some point (I think max 1024 on a
> process by default on most system so allowing for other logstash threads
> maybe 800-900)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driskell/log-courier/issues/132#issuecomment-84249301>
> .
>


-- 

[image: Joshua Reichardt on about.me]

Joshua Reichardt
thepracticalsysadmin.com | about.me <http://about.me/jmreicha>
  <http://about.me/jmreicha>

**Comment by jmreicha** [comment]
You were right about a firewall/network issue.  I can't connect to the Logstash server on the specified port for Log Courier from the internal hosts going through the NAT, I am going to have to chase down where the blockages that are happening there.

I ran a few decently busy clients overnight and when I checked this morning I saw these messages on the Logstash logs and log forwarding seemed to have sporadically stopped working.

```
{:timestamp=>"2015-03-21T17:11:52.727000+0000", :message=>"Connection timed out", :peer=>"172.17.42.1:38668", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
{:timestamp=>"2015-03-21T17:11:52.732000+0000", :message=>"Connection timed out", :peer=>"172.17.42.1:38669", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
{:timestamp=>"2015-03-21T17:12:06.557000+0000", :message=>"Connection timed out", :peer=>"172.17.42.1:38809", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
{:timestamp=>"2015-03-21T17:12:06.958000+0000", :message=>"Connection timed out", :peer=>"172.17.42.1:38814", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
{:timestamp=>"2015-03-21T17:12:09.001000+0000", :message=>"Connection timed out", :peer=>"172.17.42.1:38834", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
{:timestamp=>"2015-03-21T17:12:09.012000+0000", :message=>"Connection timed out", :peer=>"172.17.42.1:38835", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
```

And these were in the Log Courier logs:

```
ar 21 04:14:01 ip-172-16-20-204.ec2.internal docker[9609]: 2015/03/21 04:14:01.694231 Transport init failed: TLS Handshake failure with 50.16.224.136:4546 (logstash.abtm.io): read tcp 50.16.224.136:4546: connection reset by peer
Mar 21 04:14:02 ip-172-16-20-204.ec2.internal docker[9609]: 2015/03/21 04:14:02.694912 Attempting to connect to 50.16.224.136:4546 (logstash.abtm.io)
Mar 21 04:14:03 ip-172-16-20-204.ec2.internal docker[9609]: 2015/03/21 04:14:03.386658 Connected to 50.16.224.136:4546 (logstash.abtm.io)
Mar 21 04:14:03 ip-172-16-20-204.ec2.internal docker[9609]: 2015/03/21 04:14:03.386690 Transport error, will try again: Server did not respond within network timeout
Mar 21 04:14:04 ip-172-16-20-204.ec2.internal docker[9609]: 2015/03/21 04:14:04.387554 Attempting to connect to 50.16.224.136:4546 (logstash.abtm.io)
Mar 21 04:14:04 ip-172-16-20-204.ec2.internal docker[9609]: 2015/03/21 04:14:04.514585 Connected to 50.16.224.136:4546 (logstash.abtm.io)
Mar 21 17:14:18 ip-172-16-20-204.ec2.internal docker[9609]: 2015/03/21 17:14:18.610044 Transport error, will try again: EOF
```

**Comment by driskell** [comment]
Looks like at 04 connection was lost and then reconnection happens. Then it worked fine until 17.14 when connection was closed by Logstash (or a firewall.) Not sure why it did or why logging stopped. Though usually with logging stopping it's something at the Logstash side (input plugin or otherwise.) Could you check number of threads used by Logstash? (ps command can do it if you google the parameters for your distribution.)

**Comment by jmreicha** [comment]
One thing that I had overlooked was the number of workers.  Initially I did not have it set but have since increased it to 4 since the Logstash server has 4 cpu's.  I have a few more things to look at and test but will update once I get more details.

**Comment by jmreicha** [comment]
I have verified that the port is reachable via netcat on the client machine.  I still haven't ruled out a firewall rule somewhere yet but I haven't been able to chase anything weird down yet.

Here are the debugs from the client after verifying the port.

```
2015/03/22 04:05:21.417645 Transport error, will try again: Server did not respond within network timeout
2015/03/22 04:05:22.704974 Attempting to connect to 50.16.224.136:4546 (logstash.domain.com)
2015/03/22 04:05:22.947874 Connected to 50.16.224.136:4546 (logstash.domain.com)
2015/03/22 04:05:22.947938 Send now open: Retrying next payload
2015/03/22 04:05:22.948127 Send now open: Awaiting events for new payload
2015/03/22 04:05:37.948184 Transport error, will try again: Server did not respond within network timeout
2015/03/22 04:05:38.951626 Attempting to connect to 50.16.224.136:4546 (logstash.domain.com)
2015/03/22 04:05:39.217223 Connected to 50.16.224.136:4546 (logstash.domain.com)
2015/03/22 04:05:39.217276 Send now open: Retrying next payload
2015/03/22 04:05:39.217474 Send now open: Awaiting events for new payload
2015/03/22 04:05:46.416306 Spooler flushing 14 events due to spool timeout exceeded
2015/03/22 04:05:46.416357 Sending new payload of 14 events
2015/03/22 04:05:46.417704 2/10 pending payloads now in transit
2015/03/22 04:05:46.417769 Send now open: Awaiting events for new payload
2015/03/22 04:05:54.217512 Transport error, will try again: Server did not respond within network timeout
2015/03/22 04:05:55.220894 Attempting to connect to 50.16.224.136:4546 (logstash.domain.com)
2015/03/22 04:05:55.506425 Connected to 50.16.224.136:4546 (logstash.domain.com)
2015/03/22 04:05:55.506619 Send now open: Retrying next payload
2015/03/22 04:05:55.506973 Send now open: Retrying next payload
2015/03/22 04:05:55.507187 Send now open: Awaiting events for new payload
2015/03/22 04:06:06.416974 Spooler flushing 2 events due to spool timeout exceeded
2015/03/22 04:06:06.417023 Sending new payload of 2 events
2015/03/22 04:06:06.418052 3/10 pending payloads now in transit
2015/03/22 04:06:06.418110 Send now open: Awaiting events for new payload
2015/03/22 04:06:10.507052 Transport error, will try again: Server did not respond within network timeout
2015/03/22 04:06:11.510020 Attempting to connect to 50.16.224.136:4546 (logstash.domain.com)
2015/03/22 04:06:11.763501 Connected to 50.16.224.136:4546 (logstash.domain.com)
```

**Comment by jmreicha** [comment]
There has to be something going on with the networking.  I opened all ports for both IP's (address of the nat that clients are coming from and the Logstash server) on both sides but was still seeing the timeouts.

I used the internal IP address of the Logstash and clients are connecting as they should.  I'm running low on ideas of how to troubleshoot the network issues, any ideas?  Using the internal IP will fix some of the clients but there are other VPC's that will need to connect to the public address.

**Comment by driskell** [comment]
The connection is standard TCP. It comes FROM random port, TO the specified port on remote side. It does exactly the same as netcat would do if you connected that. Firewall just needs the TO port. So doesn't need any high port ranges or anything.

Is the firewall trying to "proxy" or something? Could you isolate a client to a dedicated Logstash (with just that client attached) and run the Logstash in debug mode? Maybe it will shed more light without any noise around it.

Sounds like a real PITA this one!

**Comment by jmreicha** [comment]
Yes this is a huge PITA!

I am still thinking that there is a network issue and I think that the problem is when Logstash tried to communicate back to the server inside the NAT.

I set up a tcp input on the Logstash server for testing and have been able to successfully send logs to the open tcp port from clients within the NAT.  So basically I have been able to get unencrypted log messages like syslogs to Logstash that way.  Hopefully a step in the right direction!

I wonder if Logstash chokes on the message sending back to hosts inside of the NAT since this happens with LC as well as LSF?  I'm not really sure how to test this theory but so far that is the only thing I have been able to come up with since the LC clients seemingly have no issue connecting outbound to the Logstash server.

**Comment by driskell** [comment]
Could you try pure TCP with Log Courier? Set both sides to transport TCP.

**Comment by jmreicha** [comment]
That's a good idea :) I will see if I can get that test server built as you suggested and see if I can get some debugs and will also try changing to to tcp.

**Comment by driskell** [comment]
@jmreicha Did you have any luck with this?

**Comment by jmreicha** [comment]
I haven't been able to test this, I did find a workaround that worked.  Feel free to close for now, I can always open a new issue.

**Comment by driskell** [comment]
Sure. Can you post the workaround if you think it might help others?

**Comment by jmreicha** [comment]
I'm sure it will be unique to my environment but I added a hosts entry to the internal ip of the logstash server (this was AWS VPC) so that the traffic didn't have to traverse all the way through the network.
