### ISSUE TITLE
Is there a Redis support planned?

### ISSUE THREAD

**Issue by matejzero** [driskell/log-courier#133]
Hello!

We are currently using log-courier as our shipper and so far it has performed flawlessly. Since we are slowly moving our system into production, we would like to add redis server between shipper and indexer, so we can cover the spikes we sometimes get.

Is there a Redis plugin planned? I know you already support ZeroMQ, but we already have redis setup and would not like to setup another server.

Matej

**Comment by driskell** [comment]
It is not in the roadmap.

Do you feel a need for one? One of the major goals of Log Courier is for it to cope with spikes gracefully and use the source log files as the buffer. It will send as much as it can to Logstash, and wait for it to catch up, and keep sending gradually. This has two benefits:

1. Log Courier never sends faster than Logstash can receive, this means CPU and Memory are kept low. If Redis is introduced, spikes in logs will cause spikes in Log Courier activity as it sends extremely fast to the Redis instance.
2. There isn't an extra failure point where logs can be lost (Redis is not built with guarantees on data). Without Redis, only Logstash crashes become an issue and the loss is then limited to the events in the Logstash queues - which over time will be hardened and persisted to provide guarantees that loss does not occur (see the Logstash roadmap).

It's worth being aware too that I am considering discontinuing the ZeroMQ transport and concentrating on making the TCP/TLS transport connect to multiple servers instead.

I have tried to make the transport system pluggable (though it is quite complex still...) though so if anyone else wants to write a Redis integration it should be easier than if it were all hard-coded. I know I've seen someone implement a Kafka integration here. The guarantees would be lost though so I don't think I'd want to merge them.

**Comment by matejzero** [comment]
You have a point!

I currently run a single instance of logstash and it works ok for test environment, but when I'll move it to production, I would like to have some fault-tolerance as well as load-balance. Logstash can currently handle all of the logs I'm sending, but that might change in the future, when I'll add all my logs to it.
I would like to parse logs as real-time as possible, since I'm also using statsd output and if logs are lagging, so are graphs(statsd doesn't support passing through timestamp).

Currently, log-courier supports fault-tolerance if I understand correctly, but not load-balance. You said you are concentrating on making TCP transport connect to multiple servers. Will that work as a load-balance?

**Comment by driskell** [comment]
The ZeroMQ does work as load balance at the moment. However, one slow of failed server can cause issues as ZeroMQ tries to reconnect and compensate and hides this from Log Courier.

The long term goal is TCP to do the same - load balance across multiple servers, but for Log Courier have visible and complete control over the queues etc for when failures happen to remove the issues with ZeroMQ (mainly slow performance with a failed server, and duplicated logs if it managed to reconnect as it never clears the queue - which is hidden from Log Courier - even if we resend the logs elsewhere.)

Only missing thing is "discovery" - you'd have to hard-code in the addresses of all Logstash onto all Log Courier. I guess redis method gets around this in that you can have one or two fixed receiver piping fast into Redis, then a cluster reading from Redis - after all, most performance bottleneck is filtering. Logstash 2.0 will likely include clustering and discovery which I hope to tap into.

One of my systems does use that method where the Logstash indexers vary in number. The redis server has a single Logstash purely receiving and outputting to Redis. There's then a cluster reading from it. Maybe this is the best design for your large count down the line?

**Comment by driskell** [comment]
Let me know if you have any questions - but I think best approach at the moment is to have a Logstash receiver on the redis nodes.

**Comment by mbenna** [comment]
Good dialog here. I'm evaluating what to build and the key things that come up here are:

* smooth the load on the senders during a spike by letting them handle the important customer traffic first and log shipping can be done in a catch-up mode if the receiver can't keep up. That seems to make more sense than shipping logs as fast as we can during a spike. It also decentralizes the load better.
* if better buffering *was* wanted (i.e. opposite of above comment), building a logstash to redis connector on the receiving end makes more sense than distributing a redis sender out with all the log senders. Keep the senders lean :)

Keep up the good work :+1:

**Comment by driskell** [comment]
Thanks for the feedback :-)
And yes those points are spot on and I hope they aid future users!

**Comment by noodlebreak** [comment]
@driskell Can you do an elaborate blog post on using log-courier for shipper and indexer configurations? All I've seen everywhere wherever centralized ELK setup is taught is done with using logstash-forwarder.

Having a good example of shipper and indexer configurations for lets say, simple nginx access logs, would be great. I know you wouldn't need more than 5 minutes to do it, and your 5 minutes are precious, but please do consider.

Thanks.

**Comment by driskell** [comment]
@noodlebreak Best in a new issue - that is unrelated to this topic. Having said that - you should fine most guides referring to logstash-forwarder will work with Log Courier just as well - you need only convert the "lumberjack" input to a "courier" input. Please raise new issues with any further questions so that others may find them easily.

**Comment by driskell** [comment]
@noodlebreak #lastpost - I don't actually have a blog yet lol - but I hope to start one soon, so the 5 minute job becomes a bit bigger - and I'm not one to use dedicated blogging sites (stubbornness mainly).

**Comment by noodlebreak** [comment]
Well I looked in the Configuration.md file, and I might just get helped if I go through it.
Thanks. Do update the README with a link to your blog if you create one. 

Cheers!
