### ISSUE TITLE
Output config example?

### ISSUE THREAD

**Issue by noodlebreak** [driskell/log-courier#138]
Can I see an output config example to put on servers where I ship the logs from?

I need to have logstash on those servers - check
I need to have log-courier - check
Config to ship logs - ??

**Comment by noodlebreak** [comment]
Saw this example here:
I will try now to get it to work.
https://github.com/driskell/log-courier/blob/develop/docs/examples/example-folder.conf

**Comment by noodlebreak** [comment]
@driskell  The config in example is in json.

How do I add the following filter in it:

		filter {
		  mutate {
		    replace => ["host", "SHIPPER_HOSTNAME"]
		  }
		}

**Comment by driskell** [comment]
Log Courier does not have filters.

Logstash has filters.

**Comment by driskell** [comment]
> Can I see an output config example to put on servers where I ship the logs from?
> 
> I need to have logstash on those servers - check
> I need to have log-courier - check
> Config to ship logs - ??

What do you mean logstash on those servers?

You should use Log Courier on your servers to ship logs to a remote Logstash instance. The remote Logstash instance will have all the filters and outputs and needs the courier input plugin (see the Log Courier Logstash Integration guide in README).

**Comment by noodlebreak** [comment]
@driskell Thanks for replying so fast man.
 (1994)-> sudo service logstash configtest 
Sending logstash logs to /var/log/logstash/logstash.log.
Error: Expected one of #, input, filter, output at line 1, column 1 (byte 1) after 


You said:
> What do you mean logstash on those servers?

Then I just have to make and install log-courier on my shipping servers?
Sounds reasonable and in accordance to my doubt that why should I have to use heavy logstash on my already busy shipping servers.

My new question now is (related to this only), where do I put the  conf I in my shipping servers? How will log-courier know where to get that shipping configuration from?

**Comment by driskell** [comment]
There's a command line parameter to specify location of config file: See: https://github.com/driskell/log-courier/blob/develop/docs/CommandLineArguments.md#-configpath

I will need to update the documentation in Configuration to explain this. If you've not used logstash forwarder before I can see there's some glaring holes in the documentation.

**Comment by noodlebreak** [comment]
Thanks, though I read this line in README (my fault, I totally missed it):

> The log-courier program can then be found in the 'bin' folder. This can be manually installed anywhere on your system. Startup scripts for various platforms can be found in the contrib/initscripts folder.

I made a dir /etc/log-courier, and put inside a log-courier.conf with log-courier config to pick the logs I want shipped.

Then I ran log-courier/bin/log-courier-config=/etc/log-courier/log-courier.conf

My main problem now is, how do I make bin/log-courier into a service like the logstash executable script at /etc/init.d/logstash ?

I see systemd.service in contrib/initscripts. and log-courier.sysconfig.
How do I get my /etc/init.d/log-courier service from all this?

I'm sorry for not being thoroughly experienced on Linux.

**Comment by driskell** [comment]
If it's ubuntu, I'm not sure, I have concentrated on RedHat/CentOS. You may need to role your own.

If it's SysV style (I don't think it is) you could try:
https://github.com/driskell/log-courier/blob/develop/contrib/initscripts/redhat-sysv.init

I don't have a debian/ubuntu specific script yet.

**Comment by noodlebreak** [comment]
So I created the init.d script, using skeleton and seeing stuff from logstash script.

http://pastebin.com/xWrY6tTz

It's not gonna be able to run. I'm gonna take some time on that. I'm taking cues from logstash-forwarder and logstash.

**Comment by driskell** [comment]
Thanks - let me know if it works well and I'll look at including it in contrib.
