### ISSUE TITLE
Problems in installing plugin for logstash 1.4 (gem installation)

### ISSUE THREAD

**Issue by noodlebreak** [driskell/log-courier#139]
Not an issue with your software, but..

I was following the setup process here:
https://github.com/driskell/log-courier/blob/develop/docs/LogstashIntegration.md

And I'm having problems specifically with this command:

    java -jar vendor/jar/jruby-complete-1.7.11.jar -S gem install /path/to/the.gem

I built a setup script, (which belongs to the logged in user), and ran it:

	****** Going to install log-courier gem
	ERROR:  While executing gem ... (Gem::FilePermissionError)
	    You don't have write permissions for the vendor/bundle/jruby/1.9 directory.

Then I tried it like this: (because those directories are logstash:logstash owned.

	(ubuntu)-(jobs:0)-(/tmp)-(08:55:46)
	 (2010)-> sudo -u logstash java -jar /opt/logstash/vendor/jar/jruby-complete-1.7.11.jar -S gem install /tmp/log-courier/log-courier-1.5.gem
	Fetching: cabin-0.7.1.gem (100%)
	ERROR:  While executing gem ... (Errno::EACCES)
	    Permission denied - /home/ubuntu/.gem/jruby/1.9/cache/cabin-0.7.1.gem

So I modified my script like this:

	sudo chown ubuntu:ubuntu /tmp/log-courier/log-courier-1.5.gem
	sudo chown -R ubuntu:ubuntu /opt/logstash
	java -jar vendor/jar/jruby-complete-1.7.11.jar -S gem install /tmp/log-courier/log-courier-1.5.gem
	sudo chown -R logstash:logstash /opt/logstash

I chown'd the gem, and the logstash dir, to execute that jar command smoothly.

**Comment by driskell** [comment]
You need to define GEM_HOME or it will attempt to install the gems in your user directory. The commands in the docs are:

    cd /path/to/logstash
    export GEM_HOME=vendor/bundle/jruby/1.9
    java -jar vendor/jar/jruby-complete-1.7.11.jar -S gem install /path/to/the.gem

Using sudo will not work because it will "lose" the GEM_HOME export. You need to be logged on as the user you installed Logstash as - usually this is root. I will update documentation to state so.
