### ISSUE TITLE
SSL Example for host accepting public & private connections?

### ISSUE THREAD

**Issue by ninjada** [driskell/log-courier#140]
Hello,

I presently have an internal logstash environment operating fine with multiple servers running log-courier pushing to it, all working nicely over private IP's. However, there are a couple external servers without private connectivity to my logtstash environment, that I'd like to have log-courier pushing over public IP.

I've generated my existing certs using lc-tlscert, but the existing cert will only authenticate to the private IP it was generated for and fails when used on log-courier coming from the servers over public ip with an error about the cert not being generated for that IP.

Have tried generating new certs in the same way as the working one, but also adding the second public IP of logstash during the generation, but these certs still receive error, but a slightly different one:

```
Transport init failed: TLS Handshake failure with 10.100.0.100:5000: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "logstash.mydomain.com")
```

Should this work? Is there something I might be doing incorrectly generating the SSL or with my DNS setup?

I have a public domain logstash.mydomain.com and an internal one logstash.mydomain.int. Internal log-courier's connect to logstash.mydomain.int fine even tho the cert host is logstash.mydomain.com, but it is tied to the internal IP. 

Is there something additional I need to do for this scenario? Only thing I can think of is possibly running two log-courier inputs on the logstash server, ie. on 5000 for internal and 50001 for external, with specific SSL's for both..

Thoughts?

**Comment by driskell** [comment]
@ninjada Did you apply the new certificate to BOTH the Logstash server and the clients? The certificate is installed into Logstash by the configuration. The Log Courier copy of the certificate is just used to "verify" the one Logstash has - to check they are identical - but it also verifies the IP/Hostname you connect to is specified in the certificate.

**Comment by ninjada** [comment]
@driskell yep, applied on both logstash & log-courier.

if i create the certificate for the internal ip, internal log-courier connects but external's don't.
if i create the certificate for the external ip, external log-courier connects but internal's don't.
if i attempt to create the certificate with both internal and external ip's included, neither work and get the error above.

i did have this scenario working previously with logstash & logstash-forwarder, but i self-generated the certificate in some particular way i believe.

**Comment by driskell** [comment]
I will take a look at that. As far as I know multiple IP should be fine, unless there is an issue in the certificate generation for multiple IP.

**Comment by driskell** [comment]
What version of Go did you compile from, or did you use the RPMs? Running go version should tell you.

**Comment by ninjada** [comment]
@driskell installed 1.5 via RPM's.

**Comment by driskell** [comment]
@ninjada 

> if i create the certificate for the internal ip, internal log-courier connects but external's don't.
> if i create the certificate for the external ip, external log-courier connects but internal's don't.
> if i attempt to create the certificate with both internal and external ip's included, neither work and get the error above.

Could you explain the exact steps you used to generate the certs? So if you used lc-tlscert, what options you used? Or even better, if you can generate some new ones SPECIFICALLY for testing, reproduce the issue, and share the certificates and keys via a gist? (Of course this means never use them outside test.)

**Comment by driskell** [comment]
Hi, If you can provide the above information with steps, and possibly provide the certificates, I'll be able to test and try reproduce and hopefully fix. For now I will close the topic as it's gone quiet but please do reopen if you are available to look at this again!
