### ISSUE TITLE
use of lc-tlscert - TLS Handshake failure; x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by noodlebreak** [driskell/log-courier#141]
I used lc-tlscert in log-courier/bin (after running make), to generate tls certificate and key for ssl on my indexer instance.
I copied them over to my shipper instance.
And then all I can see is this in my /var/log/log-courier/log-courier.log on my shipper instance:

	2015/03/20 10:53:28.697748 Attempting to connect to indexer-private-ip-address:5043
	2015/03/20 10:53:28.702510 Transport init failed: TLS Handshake failure with indexer-private-ip-address:5043: x509: certificate signed by unknown authority
	2015/03/20 10:53:29.703473 Attempting to connect to indexer-private-ip-address:5043
	2015/03/20 10:53:29.707626 Transport init failed: TLS Handshake failure with indexer-private-ip-address:5043: x509: certificate signed by unknown authority
	2015/03/20 10:53:30.708028 Attempting to connect to indexer-private-ip-address:5043
	2015/03/20 10:53:30.712280 Transport init failed: TLS Handshake failure with indexer-private-ip-address:5043: x509: certificate signed by unknown authority
	2015/03/20 10:53:31.712690 Attempting to connect to indexer-private-ip-address:5043
	2015/03/20 10:53:31.722125 Transport init failed: TLS Handshake failure with indexer-private-ip-address:5043: x509: certificate signed by unknown authority
	2015/03/20 10:53:32.722615 Attempting to connect to indexer-private-ip-address:5043
	2015/03/20 10:53:32.727065 Transport init failed: TLS Handshake failure with indexer-private-ip-address:5043: x509: certificate signed by unknown authority
	
So, self signed certs will not work or this or am I missing something? I mean, it's just between my private instances. Do I *have* to get CA signed certs?

**Comment by driskell** [comment]
@noodlebreak Self-signed will work.

Can you provide your configuration for the courier input in Logstash, and the configuration for Log Courier itself?

**Comment by noodlebreak** [comment]
Hi!
Very very fast reply, thank you!

Here's my shipper conf (in /etc/log-courier/):
	{
		"network": {
			"servers":[
						"xx.xx.xx.xx:5043"
					  ],
			"ssl ca":  "/etc/log-courier/ssl/logcourier-indexer.crt",
			"transport": "tls"
		},

		"files": [
			// For shipping celery. This is specifically for celery shipper
			// {
			// 	"paths": [ "/var/logs/celery/*.log" ],
			// 	"fields": { "type": "celery" }
			// },
			
			{
				"paths": [ "/var/log/nginx/access.log" ],
				"fields": { "type": "nginxaccess" }
			}
		]

	}


Here's my indexer conf (in /etc/logstash/conf.d/ ):

  input {
          courier {
                  port            => 5043
                  ssl_certificate => "/etc/logstash/ssl/logcourier-indexer.crt"
                  ssl_key         => "/etc/logstash/ssl/logcourier-indexer.key"
          }
  }

  filter {
    grok {
      match => { "message" => "%{NGINXACCESS}" }
      patterns_dir => "/etc/logstash/patterns/"
    }
    date {
      match => [ "timestamp" , "dd/MMM/YYYY:HH:mm:ss Z" ]
    }
    geoip {
      source => "clientip"
    }
  }


  output {
    elasticsearch { host => localhost }
    stdout { codec => rubydebug }
  }


I'm pretty sure everything's correct. I ran configtests on both, there' all fine:


	log-courier (on shipper instance):
		(ubuntu)-(jobs:0)-(/tmp/logcourier)-(11:31:29)
		 (2015)-> sudo service log-courier configtest 
		Configuration OK


	logstash (on indexer instance):
		(ubuntu)-(jobs:0)-(/tmp)-(11:31:29)
		 (1100)-> sudo service logstash configtest 
		Sending logstash logs to /var/log/logstash/logstash.log.
		Using milestone 1 input plugin 'courier'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.2-modified/plugin-milestones {:level=>:warn}
		Configuration OK
		Configuration OK

**Comment by driskell** [comment]
Can you verify that the certificate on both ends is the same? Could you copy the certificate from Logstash again back to the Log Courier and restart everything?

This should work fine. I can only think they don't actually match.

**Comment by noodlebreak** [comment]
My log-courier indexer and shipper script handles rsyncing of indexer key and cert from the indexer instance after installation on the shipper instance. I removed the keys, ran the script, got the keys again, restarted log-courier, and I'm still getting the same thing.

BTW, I renamed the keys from the default generated name of selfsigned.[crt,key] to the name you can see here. That absolutely can't be a problem, can it? 

Anyways, here's the log of when I generated the key and cert:

	(ubuntu)-(jobs:0)-(/tmp/log-courier/bin)-(06:45:47) (develop)
	 (987)-> ./lc-tlscert 
	Specify the Common Name for the certificate. The common name
	can be anything, but is usually set to the server's primary
	DNS name. Even if you plan to connect via IP address you
	should specify the DNS name here.

	Common name: ip-X-X-X-X.us-west-2.compute.internal

	The next step is to add any additional DNS names and IP
	addresses that clients may use to connect to the server. If
	you plan to connect to the server via IP address and not DNS
	then you must specify those IP addresses here.
	When you are finished, just press enter.

	DNS or IP address 1: <internal-private-ip-of-indexer>
	DNS or IP address 2: <public-ip-of-indexer>
	DNS or IP address 3: ec2-X-X-X-X.us-west-2.compute.amazonaws.com                                                                                
	DNS or IP address 4: 

	How long should the certificate be valid for? A year (365
	days) is usual but requires the certificate to be regenerated
	within a year or the certificate will cease working.

	Number of days: 730
	Common name: ip-X-X-X-X.us-west-2.compute.internal
	DNS SANs:
	    ec2-X-X-X-X.us-west-2.compute.amazonaws.com
	IP SANs:
	    <internal-private-ip-of-indexer>
	    <public-ip-of-indexer>

	The certificate can now be generated
	Press any key to begin generating the self-signed certificate.

	Successfully generated certificate
	    Certificate: selfsigned.crt
	    Private Key: selfsigned.key

	Copy and paste the following into your Log Courier
	configuration, adjusting paths as necessary:
	    "transport": "tls",
	    "ssl ca":    "path/to/selfsigned.crt",

	Copy and paste the following into your LogStash configuration, 
	adjusting paths as necessary:
	    ssl_certificate => "path/to/selfsigned.crt",
	    ssl_key         => "path/to/selfsigned.key",

**Comment by noodlebreak** [comment]
I made another key-cert pair using the lc-tlscert executable. This time, I gave an actual name in Common Name input field.

But I'm still getting these on logstash instance:

		{:timestamp=>"2015-03-21T11:42:50.355000+0000", :message=>"Protocol error, connection aborted", :error=>"packet too large (2248212480 > 10485760)", :peer=>"172.31.34.14:42979", :level=>:warn, "plugin"=>"input/courier", "port"=>5043}
		{:timestamp=>"2015-03-21T11:42:51.358000+0000", :message=>"Protocol error, connection aborted", :error=>"packet too large (2248212480 > 10485760)", :peer=>"172.31.34.14:42980", :level=>:warn, "plugin"=>"input/courier", "port"=>5043}
		{:timestamp=>"2015-03-21T11:42:52.362000+0000", :message=>"Protocol error, connection aborted", :error=>"packet too large (2248212480 > 10485760)", :peer=>"172.31.34.14:42981", :level=>:warn, "plugin"=>"input/courier", "port"=>5043}
		^C

And this on my shipper instance:

		2015/03/21 11:43:46.170336 Transport init failed: TLS Handshake failure with 172.31.45.120:5043: read tcp 172.31.45.120:5043: connection reset by peer
		2015/03/21 11:43:47.170602 Attempting to connect to 172.31.45.120:5043
		2015/03/21 11:43:47.174222 Transport init failed: TLS Handshake failure with 172.31.45.120:5043: read tcp 172.31.45.120:5043: connection reset by peer
		2015/03/21 11:43:48.174668 Attempting to connect to 172.31.45.120:5043
		2015/03/21 11:43:48.178210 Transport init failed: TLS Handshake failure with 172.31.45.120:5043: read tcp 172.31.45.120:5043: connection reset by peer
		2015/03/21 11:43:49.178435 Attempting to connect to 172.31.45.120:5043
		2015/03/21 11:43:49.181783 Transport init failed: TLS Handshake failure with 172.31.45.120:5043: read tcp 172.31.45.120:5043: connection reset by peer
		^C


Here's my configs (mostly unchanged):


INDEXER (logstash instance):


		input {
						courier {
										port            => 5043
										ssl_certificate => "/etc/logstash/ssl/selfsigned.crt"
										ssl_key         => "/etc/logstash/ssl/selfsigned.key"
				transport       => tcp
				
						}
		}


		filter {
			multiline {
				pattern => "^\s"
				what => "previous"
			}
			multiline {
				pattern => "^---"
				what => "previous"
			}
			multiline {
				pattern => "^Traceback"
				what => "previous"
			}
			multiline {
				pattern => "^\S*?(Error|Exception):\s"
				what => "previous"
			}
		 
			if [type] == "celery" {
				grok {
					match => { "message" => "%{DATESTAMP:timestamp}:%{DATA:python_module}:%{LOGLEVEL:Level}:%{GREEDYDATA:message}" }
					add_field => [ "hostname", "{{ grains['host'] }}" ]
					add_field => [ "process", "service_discovery_daemon"]
				}
			}
		}

		filter {
			grok {
				match => { "message" => "%{NGINXACCESS}" }
				patterns_dir => "/etc/logstash/patterns/"
			}
			date {
				match => [ "timestamp" , "dd/MMM/YYYY:HH:mm:ss Z" ]
			}
			geoip {
				source => "clientip"
			}
		}


		output {
			elasticsearch { host => "127.0.0.1" }
			stdout { codec => rubydebug
			 }
		}


SHIPPER:

(X.X.X.X is the private, not public IP of my indexer)

		{
			"network": {
				"servers":[
						"X.X.X.X:5043"
						],
				"ssl ca":  "/etc/log-courier/ssl/selfsigned.crt",
										"transport": "tls"

			},

			"files": [
				{
					"paths": [ "/var/logs/celery/*.log" ],
					"fields": { "type": "celery" }
				},
				{
					"paths": [ "/var/log/nginx/access.log" ],
					"fields": { "type": "nginxaccess" }
				}
			]

	}

**Comment by driskell** [comment]
You have set "transport" to TCP on Logstash, but on Log Courier it is TLS. You need to ensure both are TLS. This is why you get Protocol Error - it's using different transport.

**Comment by noodlebreak** [comment]
I had put tls on logstash side on that day itself, but had removed transport:tls in log-courier shipper.
So I put tls on log-courier shipper also, and now this is what I got in shipper log-courier logs:

	to X.X.X.X:5043: dial tcp X.X.X.X:5043: connection refused
	2015/03/23 05:10:01.085800 Attempting to connect to X.X.X.X:5043
	2015/03/23 05:10:01.086539 Transport init failed: Failed to connect to X.X.X.X:5043: dial tcp X.X.X.X:5043: connection refused
	2015/03/23 05:10:02.086777 Attempting to connect to X.X.X.X:5043
	2015/03/23 05:10:02.087626 Transport init failed: Failed to connect to X.X.X.X:5043: dial tcp X.X.X.X:5043: connection refused
	2015/03/23 05:10:03.087867 Attempting to connect to X.X.X.X:5043
	2015/03/23 05:10:03.394835 Connected to X.X.X.X:5043
	2015/03/23 05:10:03.395108 Send now open: Awaiting events for new payload
	2015/03/23 05:10:03.395287 Sending new payload of 1024 events
	2015/03/23 05:10:03.406244 1/10 pending payloads now in transit
	2015/03/23 05:10:03.406988 Send now open: Awaiting events for new payload
	2015/03/23 05:10:03.407182 Sending new payload of 1024 events
	2015/03/23 05:10:03.414158 2/10 pending payloads now in transit
	2015/03/23 05:10:03.414845 Send now open: Awaiting events for new payload
	2015/03/23 05:10:03.439403 Spooler flushing 1024 events due to spool size reached
	2015/03/23 05:10:03.439990 Sending new payload of 1024 events
	2015/03/23 05:10:03.453621 3/10 pending payloads now in transit
	2015/03/23 05:10:03.453938 Send now open: Awaiting events for new payload
	2015/03/23 05:10:08.439750 Spooler flushing 291 events due to spool timeout exceeded
	2015/03/23 05:10:08.439829 Sending new payload of 291 events
	2015/03/23 05:10:08.442746 4/10 pending payloads now in transit
	2015/03/23 05:10:08.443035 Send now open: Awaiting events for new payload
	2015/03/23 05:10:08.824182 ACKN message received for payload 0847807075342903fb6f3b25b7e4d671 sequence 47
	2015/03/23 05:10:08.824419 4 payloads still pending, resetting timeout
	2015/03/23 05:10:08.824605 Registrar received offsets for 47 log entries
	2015/03/23 05:10:13.825420 ACKN message received for payload 0847807075342903fb6f3b25b7e4d671 sequence 47
	2015/03/23 05:10:13.825500 4 payloads still pending, resetting timeout
	2015/03/23 05:10:18.826718 ACKN message received for payload 0847807075342903fb6f3b25b7e4d671 sequence 47
	2015/03/23 05:10:18.826809 4 payloads still pending, resetting timeout
	2015/03/23 05:10:23.440302 Spooler flushing 2 events due to spool timeout exceeded
	2015/03/23 05:10:23.440415 Sending new payload of 2 events
	2015/03/23 05:10:23.444201 5/10 pending payloads now in transit
	2015/03/23 05:10:23.444485 Send now open: Awaiting events for new payload
	2015/03/23 05:10:23.830080 ACKN message received for payload 0847807075342903fb6f3b25b7e4d671 sequence 47
	2015/03/23 05:10:23.833508 5 payloads still pending, resetting timeout
	2015/03/23 05:10:28.831306 ACKN message received for payload 0847807075342903fb6f3b25b7e4d671 sequence 47
	2015/03/23 05:10:28.831394 5 payloads still pending, resetting timeout
	2015/03/23 05:10:33.832576 ACKN message received for payload 0847807075342903fb6f3b25b7e4d671 sequence 47
	2015/03/23 05:10:33.832661 5 payloads still pending, resetting timeout
	2015/03/23 05:10:38.833753 ACKN message received for payload 0847807075342903fb6f3b25b7e4d671 sequence 47
	2015/03/23 05:10:38.833835 5 payloads still pending, resetting timeout
	2015/03/23 05:10:43.834981 ACKN message received for payload 0847807075342903fb6f3b25b7e4d671 sequence 47
	2015/03/23 05:10:43.835092 5 payloads still pending, resetting timeout
	2015/03/23 05:10:48.838124 ACKN message received for payload 0847807075342903fb6f3b25b7e4d671 sequence 47
	2015/03/23 05:10:48.841169 5 payloads still pending, resetting timeout
	2015/03/23 05:10:53.839400 ACKN message received for payload 0847807075342903fb6f3b25b7e4d671 sequence 47
	2015/03/23 05:10:53.839485 5 payloads still pending, resetting timeout
	2015/03/23 05:10:58.840594 ACKN message received for payload 0847807075342903fb6f3b25b7e4d671 sequence 47
	2015/03/23 05:10:58.840673 5 payloads still pending, resetting timeout
	2015/03/23 05:11:03.844313 ACKN message received for payload 0847807075342903fb6f3b25b7e4d671 sequence 47
	2015/03/23 05:11:03.844375 5 payloads still pending, resetting timeout
	2015/03/23 05:11:08.844863 ACKN message received for payload 0847807075342903fb6f3b25b7e4d671 sequence 47
	2015/03/23 05:11:08.844926 5 payloads still pending, resetting timeout



Then I stopped log-courier:

	2015/03/23 05:14:08.887594 5 payloads still pending, resetting timeout
	2015/03/23 05:14:13.894401 ACKN message received for payload 0847807075342903fb6f3b25b7e4d671 sequence 47
	2015/03/23 05:14:13.895717 5 payloads still pending, resetting timeout
	2015/03/23 05:14:18.899887 ACKN message received for payload 0847807075342903fb6f3b25b7e4d671 sequence 47
	2015/03/23 05:14:18.899944 5 payloads still pending, resetting timeout
	2015/03/23 05:14:21.546394 Initiating shutdown
	2015/03/23 05:14:21.546431 Spooler exiting
	2015/03/23 05:14:21.546460 Delaying shutdown to wait for pending responses from the server
	2015/03/23 05:14:21.546499 Harvester for /var/log/nginx/access.log exiting
	2015/03/23 05:14:21.546530 Prospector exiting



On logstash instance, I saw only this in the logs:


	log4j, [2015-03-23T05:09:58.321]  WARN: org.elasticsearch.discovery: [logstash-ip-172-31-45-120-5970-2198] waited for 30s and no initial state was set by the discovery
	{:timestamp=>"2015-03-23T05:09:12.865000+0000", :message=>"Using milestone 1 input plugin 'courier'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.2-modified/plugin-milestones", :level=>:warn}
	{:timestamp=>"2015-03-23T05:13:46.971000+0000", :message=>"Connection aborted", :error=>"Broken pipe", :peer=>"172.31.34.14:58181", :level=>:warn, "plugin"=>"input/courier", "port"=>5043}
	^C

Nothing about receiving any log messages from a shipper instance.
Even though my output conf in logstash indexer is this:

	output {
	           elasticsearch { host => "127.0.0.1" }
	           stdout { codec => rubydebug }
	    }

And I think I should definitely see some output in the logs since I'm using stdout in output.

**Comment by driskell** [comment]
Your elasticsearch couldn't be connected to. So everything is blocked waiting for it to connect. Ensure it is running on local host. This will be the problem.

  waited for 30s and no initial state was set by the discovery

**Comment by noodlebreak** [comment]
But it has been running already.

I even changed `elasticsearch { host => '127.0.0.1' }` to `elasticsearch { host => localhost }`, for my weird doubts.
I ran configtest, it's all fine on logstash side.

**Comment by driskell** [comment]
@noodlebreak That message is good!

Partially acknowledging is fine. It just means it's preventing timeouts and keeping the Log Courier informed of progress. Just means logs are arriving at that time faster than Logstash can process. Just keep an eye out on the processing rate - if it ALWAYS partially acknowledges you may find things get behind and Logstash will never catch up, in which case you'll need to look at bigger (or multiple) Logstash nodes or bigger Elasticsearch cluster. Also, increasing Logstash worker processes for filters helps sometimes (but you can't if you use the Logstash multiline filter - using Log Courier's it's fine.) Logstash mailing list can help with performance tweaking like this.

Since this is now working, I'll close the issue. If its not reopen. Or open another if a different issue.

**Comment by noodlebreak** [comment]
Okay, thanks!
I'm going to put a message broker soon on indexer side. That should help a bit, right?
What would you advise?
