### ISSUE TITLE
Connection failed to initialise "General SSLEngine problem"

### ISSUE THREAD

**Issue by jmreicha** [driskell/log-courier#144]
After the latest update to Logstash 1.5.0R2 with the Log Courier installed I am seeing the following errors:

```
New connection {:peer=>"172.17.42.1:46161", :level=>:info, "plugin"=>"input/courier", "port"=>4546}
New connection {:peer=>"172.17.42.1:46162", :level=>:info, "plugin"=>"input/courier", "port"=>4546}
New connection {:peer=>"172.17.42.1:46163", :level=>:info, "plugin"=>"input/courier", "port"=>4546}
Connection failed to initialise {:error=>"General SSLEngine problem", :peer=>"172.17.42.1:46162", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
Connection failed to initialise {:error=>"General SSLEngine problem", :peer=>"172.17.42.1:46163", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
Connection failed to initialise {:error=>"General SSLEngine problem", :peer=>"172.17.42.1:46161", :level=>:warn, "plugin"=>"input/courier", "port"=>4546}
```

**Comment by driskell** [comment]
What is your Java version Logstash is running atop of?

Researching this I think it can also happen if the handshake fails due to some certificate problem. Is client certificate verify turned off (it's off by default.)?

**Comment by jmreicha** [comment]
My Logstash server is running off Java 1.8 I believe now, it was on 1.7 before so maybe that's part of the problem.

I played around with some of the cert verification settings but didn't seem to make much of a difference.

**Comment by jmreicha** [comment]
The certificates I don't think are part of the problem, logstash-forwarder input is using the same certs and works, I also was able to verify that the courier input works on 1.5.0.beta1 with these certs.

**Comment by jmreicha** [comment]
Dumping out configs to see if I'm doing something stupid.  I am able to reproduce this on a test host so at least it should be easier to troubleshoot.

If I don't specify "ssl ca" then I get a `x509: certificate signed by unknown authority` error.  If I do specify this one the client and server I get a `remote error: unknown certificate` error.

I followed the instructions in your docs to generate the cert but that doesn't mean I didn't screw it up.  I can post the cert output here if it helps.

Log Courier courier.conf

```
{
  "network": {
    "servers": [ "<server name>:4546" ],
    "ssl certificate": "/opt/certs/courier.crt",
    "ssl key": "/opt/certs/courier.key",
    #"ssl ca": "/opt/certs/courier.crt",
    "timeout": 15
  },

  "general": {
    "log level": "debug"
  },

  "files": [
    {
      "paths": [ "/var/log/*.log" ],
      "fields": { "type": "syslog" }
    }
  ]
}
```

Logstash server.conf

```
input {
    courier {
        port => 4546
        ssl_certificate => "/etc/logstash/courier.crt"
        ssl_key => "/etc/logstash/courier.key"
        #ssl_verify_ca => "/etc/logstash/courier.crt"
    }
}

#Filter {}

output {
    stdout {
        codec => "rubydebug"
    }
}
```

**Comment by driskell** [comment]
Remove ssl certificate and key from Log Courier and only specify ca. Try that.

Unless you are wanting Logstash to also verify clients then you don't need the cert or key on the Log Courier side. I'll test your config though to see if I can reproduce and maybe improve docs.

**Comment by jmreicha** [comment]
@driskell +1!

You were right, removing the ssl cert/key from the Log Courier config fixed it.  Thank you!

**Comment by driskell** [comment]
For reference, I've raised a PR at jruby-openssl#37
It'll improve the SSL library so that in future, once upgraded etc, it will report "certificate verify failed" instead of "General SSLEngine problem" which is more meaningful!
