### ISSUE TITLE
Compiling log-courier for windows

### ISSUE THREAD

**Issue by ramreddy26** [driskell/log-courier#145]
Hi @driskell we are planning to move away from logstash-forwarder to log-courier. I have been trying to compile log-courier for windows since last 2-3 days, but we are getting different make errors like below. Could you please help me to compile log-courier for windows.

1. make: Interrupt/Exception caught (code = 0xc00000fd, addr = 0x4227d3)
2. 
The system cannot find the path specified.
build/fix_version ""
'build' is not recognized as an internal or external command,
operable program or batch file.
make: *** [fix_version] Error 1

3. build/fix_version ""
Set Log Courier Version 1.6
build/setup_root
ln: creating symbolic link `src/github.com/driskell/log-courier' to `../../..':
Not a directory
makefile:106: recipe for target 'setup_root' failed
make: *** [setup_root] Error 1

**Comment by driskell** [comment]
Hi @ramreddy26 Looks like with recent changes I broke the build on Windows.
I will aim to look at this soon and reproduce/test/fix. Apologies.

**Comment by ramreddy26** [comment]
Thank you, If it's possible could you please add the exe file in next release

**Comment by driskell** [comment]
To make this easier for future maintenance of the project, I'm going to update docs to install cygwin with "bash", "make" and "coreutils" which should be enough. I'll start some testing and checking this soon but it'll mean I can make the entire build system use general Linux utilities and not have to worry about cross-platform for Windows. Cygwin can provide all this functionality to it.

**Comment by driskell** [comment]
Just to update this ticket. I've since found out after my own testing that cygwin doesn't work very well at all with Go.

I've updated my build scripts and such to work with msysGit instead (which is a prebuilt combination of Git, MinGW, various core util binaries, and msys bash-like shell - everything needed to build Log Courier).

My testing has shown msysGit to be the easiest way to build.
