### ISSUE TITLE
logstash 1.5 cannot start the log-courier plugin without SSL cert

### ISSUE THREAD

**Issue by dkirrane** [driskell/log-courier#146]
I understood from the homepage that unlike Logstash Forwarder log-courier made SSL optional. 
However I'm hitting the following error in the logstash log for the plugin:
```
The error reported is: \n  input/courier: 'ssl_certificate' is required", "plugin"=>"input/courier"
```

**Comment by driskell** [comment]
What is your config?

To use plain TCP instead of TLS you should specify the "transport" option as "tcp" (default is "tls" which does require the SSL certificate specifying.

**Comment by dkirrane** [comment]
Yes thats the problem. Thanks.
