### ISSUE TITLE
log-courier transport problem -> General SSLEngine problem

### ISSUE THREAD

**Issue by rogerthat** [driskell/log-courier#147]
hi, 
logstash: 1.4.2
log-courier: Log Courier version 1.6.3.gc967820 client
prior versions: log-courier shipper & input-plugin 1.3.1

i compiled log-courier shipper without problem.
after this i upgrade the logstash-installation acccoring to 
https://github.com/driskell/log-courier/blob/develop/docs/LogstashIntegration.md#manual-installation
and had no problems doing so; 
{:timestamp=>"2015-04-02T12:57:28.170000+0200", :message=>"Connection failed to initialise", :error=>"General SSLEngine problem", :peer=>"X.X.X.X:43819", :level=>:warn, :file=>"log-courier/server_tcp.rb", :line=>"191", "plugin"=>"input/courier", "port"=>1514}

to get rid of the problem i had to remove the 1.6.2 - gem completely from logstash.

please note: the 1.6.2 log-courier logshipper works quite fine with the 1.3.1 - courier/input plugin in logstash, and during the problems the 1.3.1 - gem was installed as well.

it might be a jruby-sslproblem though, i remember a similar problem some time ago with the logstash-forwarder

**Comment by driskell** [comment]
Can you provide your configurations? Both Logstash side and Log Courier side?

**Comment by rogerthat** [comment]
i found alot of the following in the log-courier.log (did not changed anything in the configs on client/server-side though, the certs/keys are the same on both sides):

2015/04/02 12:48:45.210654 Transport init failed: TLS Handshake failure with X.Y.Z.A:9999 (some.host.org): remote error: unknown certificate

-------------------------

config log-courier:

{

  "general": {
    "admin enabled": true,
    "spool size": 5120,
    "prospect interval": 10,
    "admin listen address": "tcp:127.0.0.1:1234",
    "log level": "debug",
    "log file": "/var/log/log-courier.log"

  },


  "network": {
    "servers": [ "some.host.org:9999" ],

    "ssl certificate": "/etc/logstash-forwarder/logstash-forwarder.crt",
    "ssl key": "/etc/logstash-forwarder/logstash-forwarder.key",
    "ssl ca": "/etc/logstash-forwarder/ca.pem",

    "timeout": 15
  },

  "files": [
    {
      "paths": [
        "/var/log/messages",
        "/var/log/syslog",
        "/var/log/daemon.log"
      ],

      "fields": { "type": "syslog" }
    }, {
      "paths": [
        "/var/log/apache/*access.log"
      ],
      "fields": { "type": "apache_access" }
    }, {
      "paths": [
        "/var/log/auth.log"
      ],
      "fields": { "type": "auth_log" }
    }, {
   ... and some more files here
   
   -----------------------------

config logstash:

input {

    courier {
      port            => 1514
      ssl_certificate => "/etc/logstash/ssl/logstash-forwarder.crt"
      ssl_key => "/etc/logstash/ssl/logstash-forwarder.key"
      tags => "logstash_fw"
     }


    file {
        path => ["/var/log/messages", "/var/log/syslog", "/var/log/daemon.log"]
        type => "syslog"
    }

    file {
        path => ["/var/log/secure", "/var/log/auth.log"]
        type => "auth_log"
    }
  
    ....,some more files and filters

**Comment by driskell** [comment]
Remove "SSL certificate" and "SSL key" from the Log Courier configuration. It's probably the same issue as in #144 

Can you tell me why you put in these settings? I'm curious as it will allow me to improve my (clearly) insufficient documentation! :)

**Comment by driskell** [comment]
(To be elaborate - leave the certificate and key in Logstash side. Just remove it from Log Courier side. They are used for "client" verification, which you haven't enabled on Logstash so don't need to do.)

**Comment by rogerthat** [comment]
i think it's a leftover from logstash-forwarder (i used it first, but had some real issues), but am not quite sure

**Comment by rogerthat** [comment]
will try your suggestion

**Comment by rogerthat** [comment]
yeah, that did the trick, thanx!

oh, and btw:  i checked google for the error "General SSLEngine problem" + log-courier (no hit) and also the tickets, but forgot to check the "resolved" issues, my bad :D

**Comment by driskell** [comment]
For reference, I've raised a PR at jruby-openssl#37
It'll improve the SSL library so that in future, once upgraded etc, it will report "certificate verify failed" instead of "General SSLEngine problem" which is more meaningful!
