### ISSUE TITLE
Errors building with cygwin/windows

### ISSUE THREAD

**Issue by rsflaherty** [driskell/log-courier#158]
I am trying to build on Windows with cygwin and running into errors.

I have Cygwin with bash, coreutils, and make installed and am seeing the following when I run make.

$ make
build/fix_version ""
Set Log Courier Version 1.6
build/setup_root
GOPATH: /cygdrive/c/workspace/log-courier-develop
go get -d -tags "" log-courier
package log-courier: unrecognized import path "log-courier"
Makefile:114: recipe for target 'bin/log-courier' failed
make: *** [bin/log-courier] Error 1

If I change the Makefile to hardcode my GOPATH to use Windows path structure I get the following:

$ make
build/fix_version ""
Set Log Courier Version 1.6
build/setup_root
GOPATH: "c:/workspace/log-courier-develop"
go get -d -tags "" log-courier
package github.com/driskell/log-courier/src/lc-lib/admin: c:\workspace\log-courier-develop\src\github.com\driskell\log-courier exists but c:\workspace\log-courier-develop\src\github.com\driskell\log-courier\.git does not - stale checkout?
package github.com/driskell/log-courier/src/lc-lib/codecs
        imports github.com/driskell/log-courier/src/lc-lib/codecs
        imports github.com/driskell/log-courier/src/lc-lib/codecs: cannot find package "github.com/driskell/log-courier/src/lc-lib/codecs" in any of:
        C:\Go\src\github.com\driskell\log-courier\src\lc-lib\codecs (from $GOROOT)
        c:\workspace\log-courier-develop\src\github.com\driskell\log-courier\src\lc-lib\codecs (from $GOPATH)
package github.com/driskell/log-courier/src/lc-lib/codecs
        imports github.com/driskell/log-courier/src/lc-lib/core
        imports github.com/driskell/log-courier/src/lc-lib/core
        imports github.com/driskell/log-courier/src/lc-lib/core: cannot find package "github.com/driskell/log-courier/src/lc-lib/core" in any of:
        C:\Go\src\github.com\driskell\log-courier\src\lc-lib\core (from $GOROOT)
        c:\workspace\log-courier-develop\src\github.com\driskell\log-courier\src\lc-lib\core (from $GOPATH)
package github.com/driskell/log-courier/src/lc-lib/codecs
        imports github.com/driskell/log-courier/src/lc-lib/core
        imports github.com/driskell/log-courier/src/lc-lib/harvester
        imports github.com/driskell/log-courier/src/lc-lib/harvester
        imports github.com/driskell/log-courier/src/lc-lib/harvester: cannot find package "github.com/driskell/log-courier/src/lc-lib/harvester" in any of:
        C:\Go\src\github.com\driskell\log-courier\src\lc-lib\harvester (from $GOROOT)
        c:\workspace\log-courier-develop\src\github.com\driskell\log-courier\src\lc-lib\harvester (from $GOPATH)
package github.com/driskell/log-courier/src/lc-lib/codecs
        imports github.com/driskell/log-courier/src/lc-lib/core
        imports github.com/driskell/log-courier/src/lc-lib/harvester
        imports github.com/driskell/log-courier/src/lc-lib/prospector
        imports github.com/driskell/log-courier/src/lc-lib/prospector
        imports github.com/driskell/log-courier/src/lc-lib/prospector: cannot find package "github.com/driskell/log-courier/src/lc-lib/prospector" in any of:
        C:\Go\src\github.com\driskell\log-courier\src\lc-lib\prospector (from $GOROOT)
        c:\workspace\log-courier-develop\src\github.com\driskell\log-courier\src\lc-lib\prospector (from $GOPATH)
package github.com/driskell/log-courier/src/lc-lib/codecs
        imports github.com/driskell/log-courier/src/lc-lib/core
        imports github.com/driskell/log-courier/src/lc-lib/harvester
        imports github.com/driskell/log-courier/src/lc-lib/prospector
        imports github.com/driskell/log-courier/src/lc-lib/publisher
        imports github.com/driskell/log-courier/src/lc-lib/publisher
        imports github.com/driskell/log-courier/src/lc-lib/publisher: cannot find package "github.com/driskell/log-courier/src/lc-lib/publisher" in any of:
        C:\Go\src\github.com\driskell\log-courier\src\lc-lib\publisher (from $GOROOT)
        c:\workspace\log-courier-develop\src\github.com\driskell\log-courier\src\lc-lib\publisher (from $GOPATH)
package github.com/driskell/log-courier/src/lc-lib/codecs
        imports github.com/driskell/log-courier/src/lc-lib/core
        imports github.com/driskell/log-courier/src/lc-lib/harvester
        imports github.com/driskell/log-courier/src/lc-lib/prospector
        imports github.com/driskell/log-courier/src/lc-lib/publisher
        imports github.com/driskell/log-courier/src/lc-lib/registrar
        imports github.com/driskell/log-courier/src/lc-lib/registrar
        imports github.com/driskell/log-courier/src/lc-lib/registrar: cannot find package "github.com/driskell/log-courier/src/lc-lib/registrar" in any of:
        C:\Go\src\github.com\driskell\log-courier\src\lc-lib\registrar (from $GOROOT)
        c:\workspace\log-courier-develop\src\github.com\driskell\log-courier\src\lc-lib\registrar (from $GOPATH)
package github.com/driskell/log-courier/src/lc-lib/codecs
        imports github.com/driskell/log-courier/src/lc-lib/core
        imports github.com/driskell/log-courier/src/lc-lib/harvester
        imports github.com/driskell/log-courier/src/lc-lib/prospector
        imports github.com/driskell/log-courier/src/lc-lib/publisher
        imports github.com/driskell/log-courier/src/lc-lib/registrar
        imports github.com/driskell/log-courier/src/lc-lib/spooler
        imports github.com/driskell/log-courier/src/lc-lib/spooler
        imports github.com/driskell/log-courier/src/lc-lib/spooler: cannot find package "github.com/driskell/log-courier/src/lc-lib/spooler" in any of:
        C:\Go\src\github.com\driskell\log-courier\src\lc-lib\spooler (from $GOROOT)
        c:\workspace\log-courier-develop\src\github.com\driskell\log-courier\src\lc-lib\spooler (from $GOPATH)
package github.com/driskell/log-courier/src/lc-lib/codecs
        imports github.com/driskell/log-courier/src/lc-lib/core
        imports github.com/driskell/log-courier/src/lc-lib/harvester
        imports github.com/driskell/log-courier/src/lc-lib/prospector
        imports github.com/driskell/log-courier/src/lc-lib/publisher
        imports github.com/driskell/log-courier/src/lc-lib/registrar
        imports github.com/driskell/log-courier/src/lc-lib/spooler
        imports github.com/driskell/log-courier/src/lc-lib/transports
        imports github.com/driskell/log-courier/src/lc-lib/transports
        imports github.com/driskell/log-courier/src/lc-lib/transports: cannot find package "github.com/driskell/log-courier/src/lc-lib/transports" in any of:
        C:\Go\src\github.com\driskell\log-courier\src\lc-lib\transports (from $GOROOT)
        c:\workspace\log-courier-develop\src\github.com\driskell\log-courier\src\lc-lib\transports (from $GOPATH)
Makefile:114: recipe for target 'bin/log-courier' failed
make: *** [bin/log-courier] Error 1

I can see the symbolic link in c:\workspace\log-courier-develop\src\github.com\driskell and am able to see files in my local workspace in the location specified under c:\workspace\...

Any guidance you can provide is greatly appreciated.

**Comment by driskell** [comment]
What is your Go version? Can you run go version and go env?

**Comment by rsflaherty** [comment]
$ go version
go version go1.4.1 windows/amd64

$ go env
set GOARCH=amd64
set GOBIN=
set GOCHAR=6
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

**Comment by rsflaherty** [comment]
Just FYI - I tried on another box with 32 bit go 1.4.2 and got the same results.

**Comment by rsflaherty** [comment]
I was able to get it to build by copying the entire log-courier directory into $GOROOT/src/github.com/driskell.

I think the issue had to do with the symbolic link in log-courier/src/github.com/driskell.  It seemed to be recognized fine from cygwin but I don't think it was working when Go tried to do its import.

**Comment by driskell** [comment]
Possibly. Thanks for the details and looking into it. I admit I have done some very Linux-orientated things in the Makefile which meant cygwin was needed. But it looks like actually Go itself is not cygwin compatible so it looks like I've a fair bit of work to correct this. Apologies.

I'll try and find some time soon to look into this. I'm currently deep in some v2 improvements though but once I find a good moment to break off I'll sit down and work through Windows build.
