### ISSUE TITLE
unable to ship logs from begining

### ISSUE THREAD

**Issue by madhusudand** [driskell/log-courier#160]
i wanted to ship logs from beginning of a log file.
When i add a new path to log files. It starts shipping logs from point where new logs are created after that time. I need to consider logs which are created from beginning, i mean old logs.
Is there any option which i need to enable for this .
Thanks in advance....

**Comment by driskell** [comment]
Please see command line option, `-from-beginning`:
https://github.com/driskell/log-courier/blob/develop/docs/CommandLineArguments.md#-from-beginning

**Comment by madhusudand** [comment]
ohh... thanks
