### ISSUE TITLE
No such file to load --jrjacker

### ISSUE THREAD

**Issue by Rajeshkumar123** [driskell/log-courier#162]
When I try to run the config file from logstash I am getting this error "No files to load --jrjacker". I am running in windows 7 env.

**Comment by driskell** [comment]
What Logstash version are you using? How are you running it and what is your config?

**Comment by Rajeshkumar123** [comment]
logstash 1.5.0. 
1. I first started the log courier with port 1434. I got the message in cmd as "connected".
2. Then I started the logstash.
3. My config file lokks like below

input{
courier{
port => 1434
.
.
}
}

filter{
}

**Comment by driskell** [comment]
Can you provide full error output and any surrounding messages?

**Comment by Rajeshkumar123** [comment]
@driskell . The error was resolved it was due to some gem file missing. Thank you.

**Comment by Rajeshkumar123** [comment]
@driskell . The error was resolved it was due to some gem file missing. Thank you
