### ISSUE TITLE
I am getting "undefined : DefaultLogBackend" when I tried to create an log-courier.exe file

### ISSUE THREAD

**Issue by Rajeshkumar123** [driskell/log-courier#165]
I am using logcourier 1.6 plugin in logstash. I am trying to create a log-courier.exe file. When I tried to execute it. I am getting the below error.

c:\go\src\log-courier>go build
.\log-courier.go:76: undefined: core.Log_Courier_Version
.\log-courier.go:177: undefined: core.Log_Courier_Version

c:\go\src\log-courier>go build log-courier.go
.\log-courier.go:56: undefined: DefaultLogBackend

![goexe](https://cloud.githubusercontent.com/assets/7466386/7806175/87bfa0a6-0332-11e5-8398-3efbf99c60.

Below are my go env deatils.

c:\go\src\log-courier>go env
set GOARCH=386
set GOBIN=
set GOCHAR=8
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\go\src
set GORACE=
set GOROOT=c:\go
set GOTOOLDIR=c:\go\pkg\tool\windows_386
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

Please let me know If I am missing anything. If you have any documents in creating log-courier.exe pls share it to me. It would be a great help.

**Comment by driskell** [comment]
Running `go build` is not enough as there's some dependencies to download and source to generate. Please follow the Windows build instructions: https://github.com/driskell/log-courier/blob/master/README.md#windows

**Comment by Rajeshkumar123** [comment]
@driskell 
I am getting this below error 

![git](https://cloud.githubusercontent.com/assets/7466386/7810308/b1b1346a-0355-11e5-8f02-e38e6b02cb3e.jpg)

**Comment by driskell** [comment]
Do you have internet access? It's trying to download some dependencies from github.com

**Comment by Rajeshkumar123** [comment]
Yes I have high speed internet access

**Comment by driskell** [comment]
You're firewall may be blocking something. You need to find out why it cannot connect to GitHub

**Comment by Rajeshkumar123** [comment]
I checked my firewall also but no luck still getting the same error. Is there anyother possible way to create the log-courier.exe file. Is it downloadable?

**Comment by driskell** [comment]
I don't have any packaged versions of Windows EXE, sorry, though I have considered it.
Could you try on a different machine? Are you within a corporate network that uses a proxy?

**Comment by Rajeshkumar123** [comment]
Yes

**Comment by driskell** [comment]
If you're using a proxy you'll need extra steps to configure msysgit to use the proxy. It's outside the scope of the README though so I won't be placing it there.

You'll either need to use `git config --global http.proxy proxy.host.com:8080` or set environment variable for it `export https_proxy=proxy.host.com:8080`

May be easier to use a machine that does not sit behind a proxy though.
