### ISSUE TITLE
log-courier does not accept a directory as config argument (like logstash-forwarder).

### ISSUE THREAD

**Issue by jarpy** [driskell/log-courier#174]
logstash-forwarder allows using a directory full of config fragments as the argument to `-config`. This is a great feature that helps simplify configuration management.

It would be nice to have this in log-courier (along with all the great stuff the logstash-forwarder _can't_ do.

```
$ log-courier -config=/etc/log-courier/conf.d/
Configuration error: read /etc/log-courier/conf.d/: is a directory
```

**Comment by driskell** [comment]
@jarpy check out the [`includes`](https://github.com/driskell/log-courier/blob/master/docs/Configuration.md#includes) configuration.

This was implemented prior to LSF's method and is more explicit and inline with other software.

The main 'pet hate' I had with specifying a directory is where does the network/general configuration get stored? A random file? (Makes it harder to find and potentially different on each system.) How is repetition of network handled? (LSF just overwrites in alphabetical file order I think, except for servers, which I think it merges.)

**Comment by jarpy** [comment]
Thanks @driskell. Sorry to take your time when you have an excellent solution already.

BTW, log-courier has made my Logstash setup 200% more awesome since I started using it _this morning_. Thank you.
