### ISSUE TITLE
Error in logstash - "Failed parsing date from field"  because of IllegalArgumentException

### ISSUE THREAD

**Issue by ahaeber** [driskell/log-courier#176]
I'm trying out log-courier together with logstash-1.5 and experience a parsing error in logstash for the events:
```javascript
{:timestamp=>"2015-06-02T12:12:12.725000+0200", :message=>"Failed parsing date from field", :field=>"timestamp", :value=>"2015-06-02 12:12:06.5215", :exception=>java.lang.IllegalArgumentException: Invalid format: "2015-06-02 12:12:06.
5215" is malformed at "5", :level=>:warn, "plugin"=>"input/courier", "port"=>5000}
{:timestamp=>"2015-06-02T12:12:12.735000+0200", :message=>"Failed parsing date from field", :field=>"timestamp", :value=>"2015-06-02 12:12:11.0090", :exception=>java.lang.IllegalArgumentException: Invalid format: "2015-06-02 12:12:11.
0090" is malformed at "0", :level=>:warn, "plugin"=>"input/courier", "port"=>5000}
{:timestamp=>"2015-06-02T12:12:12.747000+0200", :message=>"Failed parsing date from field", :field=>"timestamp", :value=>"2015-06-02 12:12:11.0090", :exception=>java.lang.IllegalArgumentException: Invalid format: "2015-06-02 12:12:11.
0090" is malformed at "0", :level=>:warn, "plugin"=>"input/courier", "port"=>5000}
```

This appears to be a typical Joda Time parsing error due to an incorrect format. I've experienced this before with the date filter due to locale mismatch (logstash or filter assumes the wrong locale). So it seems to be the same issue here. However, the date filter has several configuration options for date parsing but I cannot see anything similar for the input/courier configuration.

Does anybody know a fix / workaround for this issue? Or is it simply a bug in log-courier?

**Comment by driskell** [comment]
@ahaeber Ignore the "plugin"=>"input/courier" - this is a misdirection caused by a bug in the plugin - the plugin adds that to ALL log events rather than only its own. The issue here is indeed with the date filter and the issue is occurring there.

Sorry for the confusion.
