### ISSUE TITLE
Log Courier and Latest ELK Compatibility?

### ISSUE THREAD

**Issue by ninjada** [driskell/log-courier#177]
Quick one, testing latest logstash, elasticsearch & kibana stack. I diverted one of my webservers running log-courier to the new test setup and the log-courier logs seemed to indicate things were ok in terms of connectivity, but logstash never took the logs or created an elasticsearch indice. 

From there I was stuck, I couldn't even get into testing kibana4 because you need to have some data indexed within elasticsearch to setup an index term.

Switched to logstash-forwarder and things worked straight away.

I'm not up on the plans for logstash-forwarder, I believe it was being rebuilt? Or a new alternative was coming?

I did have a lot of problems with it in the past, alleviated by log-courier. Just wondering what I should be considering when evaluating the new ELK stack for plans to move to the latest options etc.

**Comment by driskell** [comment]
@ninjada if you run Logstash in debug mode (from cmd line with `-d` option) do you see anything?

Versions of the stack components will help greatly too including log courier version and how it was installed (from source, rpm etc)

I'm running logstash 1.5 with log courier perfectly.

**Comment by ninjada** [comment]
running the following versions, logstash with --debug and i'm not seeing a single thing log-wise on the logstash end.

log-courier log also in debug mode is just looping the following logs:

{code}
2015/06/04 03:16:31.268570 Send now open: Retrying next payload
...
2015/06/04 03:16:31.268592 Send now open: Awaiting events for new payload
2015/06/04 03:16:31.268604 Sending new payload of 1 events
2015/06/04 03:16:31.268919 Pending payload limit of 10 reached
2015/06/04 03:16:40.202202 Spooler flushing 1 events due to spool timeout exceeded
2015/06/04 03:16:46.268300 Transport error, will try again: Server did not respond within network timeout
2015/06/04 03:16:47.271756 Attempting to connect to 172.31.6.102:5000 (logtest.test)
2015/06/04 03:16:47.336033 Connected to 172.31.6.102:5000 (logtest.test)
2015/06/04 03:16:47.336062 Send now open: Retrying next payload
...
2015/06/04 03:16:47.336237 Send now open: Retrying next payload
2015/06/04 03:16:47.336596 Send now open: Awaiting events for new payload
2015/06/04 03:16:47.336609 Sending new payload of 1 events
2015/06/04 03:16:47.337404 Pending payload limit of 10 reached
2015/06/04 03:17:02.336321 Transport error, will try again: Server did not respond within network timeout
2015/06/04 03:17:03.339688 Attempting to connect to 172.31.6.102:5000 (logtest.test)
2015/06/04 03:17:03.404135 Connected to 172.31.6.102:5000 (logtest.test)
2015/06/04 03:17:03.404180 Send now open: Retrying next payload
{code}

**Comment by driskell** [comment]
If you're seeing nothing, something is very wrong. You should at least see something logged, especially in debug.

Make sure you're running it in console and not running as service and reading from log files. Log files have problems with buffering and sometimes logs aren't written until they reach certain size. So switch to /opt/logstash or wherever it is and run `bin/logstash agent --debug -f /path/to/config.conf`

**Comment by driskell** [comment]
I'll close this for now. If you manage to get logs from Logstash side please reopen.
