### ISSUE TITLE
Add fields section on general section

### ISSUE THREAD

**Issue by disaster37** [driskell/log-courier#178]
It's possible to enhance log-courier to put fields in general section and add this fields on each path.
It's usefull to add some context field about server like environment (dev, prod), project, etc.

The current way it's to add the same fields on each path :x

**Comment by driskell** [comment]
I'll look at this for the roadmap. Thanks!

**Comment by driskell** [comment]
There's now `global fields` in the master branch!

**Comment by disaster37** [comment]
Tanks, I will try this on the next upgrade.
