### ISSUE TITLE
Logstash cannot bind to port 443

### ISSUE THREAD

**Issue by algupta** [driskell/log-courier#179]
Installed log-courier plugin.
Tried to bind logstash to port 443.

################################################################################
# INPUT SECTION
################################################################################
input {
  courier {
    port        => 443
    transport=> "tcp"
  }
}

From: /var/log/logstash/logstash.log
{:timestamp=>"2015-06-05T12:42:15.927000+0000", :message=>"You are using a deprecated config setting \"index_type\" set in elasticsearch. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future.  If you have any questions about this, please visit the #logstash channel on freenode irc.", :name=>"index_type", :plugin=><LogStash::Outputs::ElasticSearch --->, :level=>:warn}
{:timestamp=>"2015-06-05T12:42:15.941000+0000", :message=>"You are using a deprecated config setting \"index_type\" set in elasticsearch. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future.  If you have any questions about this, please visit the #logstash channel on freenode irc.", :name=>"index_type", :plugin=><LogStash::Outputs::ElasticSearch --->, :level=>:warn}
{:timestamp=>"2015-06-05T12:42:15.947000+0000", :message=>"You are using a deprecated config setting \"index_type\" set in elasticsearch. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future.  If you have any questions about this, please visit the #logstash channel on freenode irc.", :name=>"index_type", :plugin=><LogStash::Outputs::ElasticSearch --->, :level=>:warn}
{:timestamp=>"2015-06-05T12:42:17.279000+0000", :message=>"The error reported is: \n  input/courier: Failed to initialise: Permission denied - bind(2)"}

Note: Works for all ports >1K.

Regards
Alok

**Comment by driskell** [comment]
Out of the box, only root/administrator can bind to ports < 1024. This is a standard Linux and Windows behaviour.

I also advise against binding to 443 - it is registered for use by HTTPS and Log Courier does not use HTTPS. It will confuse network scanners and be very unintuitive.

**Comment by algupta** [comment]
I had logged in as 'root'. Yes I know 443 is for https, but due to some firewall rules, ports > 1K are blocked in our n/w so though of binding it to standard ports which I am not going to use for any web server.
I think if user is root/administrator, user should be able to start logstash on any unused ports.

Regards
Alok

**Comment by driskell** [comment]
If you installed Logstash via RPM, and started it using `service logstash start` - it will not run as root, it will drop privileges and run as `logstash`.

**Comment by algupta** [comment]
Thank you,
-Alok
