### ISSUE TITLE
configuration error XML files not parsing in logstash

### ISSUE THREAD

**Issue by Rajeshkumar123** [driskell/log-courier#182]
I am getting this error in my linux machine when I tried to run the ELK setup.

Below is my log courier code

{
	"general": {
		"log level" : "debug",
		"persist directory" : "/sample/conf"
	},

	"network": {
		"servers": [ "127.0.0.1:14780" ],
		"ssl ca": "/sample/key/signed.crt"
		
	},
	"files": [
		{
			"paths":[ "/sample/logs/*/*.xml"],
			"fields": { "type": "log" },
			"codec": {
				"name": "multiline",
				"pattern":"<\/statement>",
				"negate": true,
				"what": "next"
			},
			"dead time": "300s"
		}
	]
}

I am getting this error "configuration error: Option /files[0]/event on eof is not available log courier".

I removed this line "event on eof": true on that time I didn't get any error but it fails to fetch the files from the mentioned path.

The same configuration was running perfectly for ".log" files but its not working for other file type like(.xml,.txt,etc).

**Comment by driskell** [comment]
Do your XML files end in a new line? I've seen previous issue where the XML file was written without a new line ending. As far as Log Courier is concerned - it looks like the line is "half-written" and not yet completed, thus it waits.

All lines need to be complete and have a corresponding line ending.

**Comment by driskell** [comment]
Also, `"event on eof"` - where did you see this? It's not a valid option and I've never heard of it.

**Comment by Rajeshkumar123** [comment]
I am having .txt file but the content inside the file is in xml format. New line ending is available in that files. I removed the event on eof from the code.

**Comment by Rajeshkumar123** [comment]
Do I need to apply any patches as mentioned for windows below.

https://github.com/driskell/log-courier/commit/e251405f7b820d8d986f32fd5c94b312452c9895

**Comment by Rajeshkumar123** [comment]
Is there any option to mention to read the file till end like eof in log courier.

**Comment by driskell** [comment]
Can you provide logs from Log Courier?

**Comment by Rajeshkumar123** [comment]
In logcourier log files I have the file path information only.

**Comment by driskell** [comment]
Can you provide logs anyway? It will have key information on whether or not it is picking up lines or not.

**Comment by Rajeshkumar123** [comment]
{"C:\\Users\\9.xml":{"vol":108030804,"idxhi":458752,"idxlo":278880,"source":"C:\\Users9.xml","offset":23848},
"C:\\Users\\05.xml":{"vol":108030804,"idxhi":393216,"idxlo":278882,"source":"C:\\Users\\05.xml","offset":23455},
"C:\\Users\\15.xml":{"vol":108030804,"idxhi":1572864,"idxlo":279519,"source":"C:\\Users\\15.xml","offset":18528}}

**Comment by Rajeshkumar123** [comment]
Its fetching the files but it not parsing the XML filter and the fields inside the XPATH. I am getting only default fields 


   "host" => "ABCD",
"message" => "?<system systemid=\"9870></system>....
....
....
...
        "offset" => 0,
          "path" => "C:\\Users\\156687\\Documents\\Java\\1ddlogs\\error-2015-04-
13130333Z-18738fa1-7c7f-4cff-9007-b024ed167eb5.xml",
          "type" => "elmah_log",
      "@version" => "1",
    "@timestamp" => "2015-06-11T06:22:31.445Z"
}

**Comment by driskell** [comment]
Enable "log syslog": true in log courier general section and you'll get logs to the syslog. The file you have above is not the log file.

It looks like stuff is being sent though so it's likely a Logstash problem with XML parsing and not a courier problem.

**Comment by Rajeshkumar123** [comment]
Can you please check in logstash why XML files are not parsing. Let me know if you need any further details.

**Comment by driskell** [comment]
Please raise Logstash issues in the Logstash repository.
