### ISSUE TITLE
unable to install courier plugin for logstash 1.5

### ISSUE THREAD

**Issue by madhusudand** [driskell/log-courier#183]
this is what i get after running bin/plugin install logstash-input-courier 
Validating logstash-input-courier
Plugin logstash-input-courier does not exist
ERROR: Installation aborted, verification failed for logstash-input-courier
please help me in this regard
Thanks

**Comment by driskell** [comment]
Please can you run in debug?

    DEBUG=1 bin/plugin install logstash-input-courier

**Comment by madhusudand** [comment]
DEBUG=1 bin/plugin install logstash-input-courier
DEBUG: exec /root/junk/logstash-1.5.0/vendor/jruby/bin/jruby --1.9 -J-XX:+UseParNewGC -J-
This was the output:
XX:+UseConcMarkSweepGC -J-Djava.awt.headless=true -J-XX:CMSInitiatingOccupancyFraction=75 -J-XX:+UseCMSInitiatingOccupancyOnly -J-Xmx500m /root/junk/logstash-1.5.0/lib/pluginmanager/main.rb install logstash-input-courier
Validating logstash-input-courier
Plugin logstash-input-courier does not exist
ERROR: Installation aborted, verification failed for logstash-input-courier

**Comment by driskell** [comment]
@madhusudand Does the machine have internet access? I tested and it works fine.

**Comment by madhusudand** [comment]
yes it has the access.
its a private network. i want all the dependencies to be put in our private repo too before using.
So can you tell me what are the dependencies it requires at the time installing courier plugin. So that i can get all of them on our private repo and if any workaround for installing it using dependencies put up on private repo.

**Comment by driskell** [comment]
You will need to download these gems

https://rubygems.org/gems/ffi-rzmq-core
https://rubygems.org/gems/ffi-rzmq
https://rubygems.org/gems/multi_json
https://rubygems.org/gems/log-courier
https://rubygems.org/gems/logstash-input-courier

You'll then need to manually install the gems into Logstash:

```
cd /path/to/logstash
export GEM_HOME=vendor/bundle/jruby/1.9
java -jar vendor/jar/jruby-complete-1.7.11.jar -S gem install /path/to/the.gem /path/to/next.gem /path/to/more.gem
```

**Comment by driskell** [comment]
If you can get an internet connection it will work MUCH easier.

Alternatively, if you installed Logstash from a `tar.gz` you could run `bin/plugin install` on one machine that does have internet access and then just copy the entire logstash folder to the desired server (the plugin will already be installed then.)

**Comment by madhusudand** [comment]
Sounds good... Thanks a lot ....

**Comment by driskell** [comment]
If it's ok Id like to keep this open to remind me to improve the docs :-)

**Comment by madhusudand** [comment]
i am installing log-courier plugin for logstah-1.5.2 manually because of some restriction. the steps are like this :
cd /path/to/logstash
export GEM_HOME=vendor/bundle/jruby/1.9
java -jar vendor/jar/jruby-complete-1.7.11.jar -S gem install /path/to/the.gem /path/to/next.gem /path/to/more.gem

but i am not able to find this "vendor/jar/jruby-complete-1.7.11.jar" in logstash-1.5.2
please help me to resolve this.

Thanks in advance

**Comment by madhusudand** [comment]
friendly ping..
Any update for above query??

**Comment by driskell** [comment]
Try this:

```
cd /path/to/logstash
export GEM_HOME=vendor/bundle/jruby/1.9
java -jar vendor/jruby/lib/jruby.jar -S gem install /path/to/the.gem /path/to/next.gem /path/to/more.gem
```

**Comment by madhusudand** [comment]
@driskell 
i got following error
LoadError: no such file to load -- rubygems
  require at org/jruby/RubyKernel.java:1071
   (root) at /usr/bin/gem:8

**Comment by madhusudand** [comment]
@driskell  
I have stuck in installing log-courier plugin for logstash -1.5.0  manually(not using plugin manager).
Can you try it once locallly and suggest me the ways of doing it.I have some deadline to for automating whole system which includes this step.

Thanks in advance....

**Comment by packplusplus** [comment]
@madhusudand 
If you want a custom packaged logstash;
* log into to a machine
* grab the logstash tarball and init script
* install it in a single directory like /opt/logstash
* use the native plugin manager to install whatever you'd like
* use [fpm](https://github.com/jordansissel/fpm) to turn that directory into a package .
* install that package instead. 

Yeah, it's a couple extra steps, but like beats waiting on the package maintainer to document an unsupported installation method.

**Comment by driskell** [comment]
I will close this now. There's some work for me to do on Logstash 2 support etc. and improving docs for it, and this refers back to 1.5 which is now fairly old.
