### ISSUE TITLE
Parameter to disable paths from being watched

### ISSUE THREAD

**Issue by martinhynar** [driskell/log-courier#184]
Hi, I would find useful to have option to disable certain path definition from usage. What I mean, I have 'main' configuration that has all the general and network parameters in it. This one has very rare changes. Then I have bunch of 'specific' configurations for named paths and files with the field additions and patterns. These 'specific' configs are included from 'main'.

I would find useful, to have parameter, e.g. "enabled" that will control whether given included 'specific' configuration shall be used or not. Having this will allow me to dynamically configure what paths are watched.

Example:
```
/etc/log-courier/main.json:
{
  "general": { ... },
  "network": { ... },
  "includes": ["/etc/log-courier/input-*.json"]
}
```
```
/etc/log-courier/input-syslog.json:
[
  {
     "paths": ["/var/log/messages"],
     "enabled": false
  }
]
```

**Comment by driskell** [comment]
Would renaming the file from `input-syslog.json` to `input-syslog.json.disabled` be any good?
This would already work and prevent the need for loading unused configuration.

**Comment by martinhynar** [comment]
Renaming will of course work, but what I am aiming is to be able to reconfigure log-courier by only making changes inside existing configuration files.

**Comment by driskell** [comment]
Are you using configuration management to achieve this? Could you outline the requirements you have and how you intend to use them?

I'm just not understanding the scenarios in which this would be useful so I'm hesitant to add extra complexity to code to achieve this method. When manual, you can rename. When automated via configuration management, you can just not install the configuration or install as a different name.

**Comment by martinhynar** [comment]
I understand your concern. Let me explain my use case.

I am running monitoring of logs on virtual machines that are created on demand and then discarded. When given virtual machine is created, it shall be possible to configure what components shall be monitored (there are lots of them per VM).
One of the typical case is to run bunch of tests where one wants to collect logs from component that is suspect for malfunction. Another one is when some component is not behaving as it should (but not always) and I want to see only this "hot" one over a series of executions. 

Each VM is auto-provisioned with configuration for all components that could be deployed. Such configurations are typically templates with `__variables__` that are replaced before actual task is executed based on configuration file that says which components shall be monitored. I do this by going through all templates and replacing `__variables__ `. The simplest use would be to have `"enabled" : __WATCH_X_FILES__` where `__WATCH_X_FILES__` gets replaced with true or false.

To be honest, I am in doubt whether this is enough justification for addition of `enabled` field, but other users of log-courier might find it also useful.

Since I started this issue, I was able to solve this problem by renaming the template configuration files and replacing different `__variable__` so I am able to exclude monitoring of unwanted logfiles anyway. So, I let you decide whether to add it or maybe make it more general.

**Comment by driskell** [comment]
> Since I started this issue, I was able to solve this problem by renaming the template configuration files and replacing different __variable__ so I am able to exclude monitoring of unwanted logfiles anyway. So, I let you decide whether to add it or maybe make it more general.

If you could drop a note on what different approach you took that will help others.

I'll hold on adding any "enabled" option for now unless others find some use for it, as if there's an alternative approach you've found that works just as well it may be it would never get used as a result.

**Comment by martinhynar** [comment]
My approach is like that. I have a script that takes all files named `xx.json.template`, replaces `__VARIABLE__` with actual value and creates file xx.json. This is done based on configuration file received as parameter.

For log-courier, I have main file `log-courier.json.template` having this content

```
"includes": [
    "/etc/log-courier/__INCLUDE-SYSLOG__-syslog.json",
    "/etc//log-courier/__INCLUDE-APACHE__-apache.json"
  ]
```

Then I have specific configuration files for different log files (services, ...). For example, `include-syslog.json` could contain `"paths" : ["/var/log/messages"]`.

Now, when I want to watch `messages` file, I pass to to template replacing script configuration `{"syslog" : true}` and it goes over `log-courier.json.template` and replaces `"/etc/log-courier/__INCLUDE-SYSLOG__syslog.json"` with `"/etc/log-courier/include-syslog.json"` which causes `include-syslog.json` being loaded. When I pass `{"syslog" : false}` I get `"/etc/log-courier/exclude-syslog.json"`, but such file does not exists and `messages` are omitted. (Also, I see "exclude-syslog" which conveys information that this is excluded).

**Comment by driskell** [comment]
One possibility here is to use # comment in the JSON file. It's non-standard but supported by Log Courier. So you could comment out the lines you don't need.

In all honesty though I wonder if you are better doing a active/inactive style system. Have two folders, "/etc/log-courier/active" and "/etc/log-courier/inactive" and only include files from the active folder with `"includes": [ "/etc/log-courier/active" ],`. Then your script can just move the different config files around without editing them, which may be much cleaner and simpler to do.

Or even an upstart/sysv style method - also used by nginx on debian I think. Have all files in a "/etc/log-courier/configs-available" folder. Then symlink to corresponding files inside "/etc/log-courier/configs".

Thanks for feeding back though! Glad you worked something out. I'll close this now.
