### ISSUE TITLE
 Logstash: no such file to load -- logstash/inputs/courier

### ISSUE THREAD

**Issue by imax36581** [driskell/log-courier#185]
Hi all
recently i installed Courier integration with logstash 1.5 via:
bin/plugin install logstash-input-courier

but i got following error when i tried to start logstash:
{:timestamp=>"2015-06-10T12:18:16.834000+0430", :message=>"The error reported is: \n  Couldn't find any input plugin named 'courier'. Are you sure this is correct? Trying to load the courier input plugin resulted in this error: no such file to load -- logstash/inputs/courier"}

logstash configuration:
input {courier {
                port            => 14300
                transport       => "tcp"
        }
}
output {elasticsearch {host => "127.0.0.1" protocol => http} }

**Comment by driskell** [comment]
Can you check that the plugin installation worked? Run `bin/plugin install logstash-input-courier` again and verify the output states it was successful.

**Comment by imax36581** [comment]
I run the command again:
Validating logstash-input-courier
Installing logstash-input-courier
Installation successful

**Comment by driskell** [comment]
How are you running Logstash?

**Comment by imax36581** [comment]
via its default init script in centos (installed via RPM)

**Comment by driskell** [comment]
What directory were you in when you ran `bin/plugin install`?
Can you try uninstall and reinstall? `bin/plugin uninstall logstash-input-courier` then reinstall it.

**Comment by driskell** [comment]
Noting here I received email from you and you were running CentOS 7

**Comment by driskell** [comment]
Did you manage to resolve this issue?

**Comment by imax36581** [comment]
Hi Jason
Sorry for delay in response.i was on a long trip.
It seems the default init script cause this issue.
After staring logstash by a customized script the plugin worked
successfully.
Thanks again for your help

**Comment by driskell** [comment]
No problem thanks for dropping a note!
