### ISSUE TITLE
XML Filter not parsing fields mentioned inside XPATH in Logstash 1.5.0

### ISSUE THREAD

**Issue by Rajeshkumar123** [driskell/log-courier#186]
When I pass the xml files to logstash via logcourier. The xml files are not parsing properly.

Below is my logstash code.

input{
   courier {
		port => 10545 
		transport => "tcp"	
	}
} 

filter{

   if [type] == "system_log" {

	 xml {
		source => "message"
		store_xml => false 
		xpath => [
			"/system/@message","system_message",	     
			"/system/@detail","detail",
			"/system/@host","host",
			"/system/@user","user",
			"/system/@time","timestamp",
			"/system/@type","Type",
			"/system/item/@name", "systemNames"
]
}
output{
stdout{codec=>rubydebug}
}

In my output I didnt see the fileds mentioned inside xpath. I am getting the entire xml in "message" field.

**Comment by driskell** [comment]
@Rajeshkumar123 Before you head over to Logstash issues - I noticed one thing.

In your Log Courier config you had type "log" and in your output you provided in the other issue, the type was "logs". And in your Logstash configuration above, you're only applying xml filter to type "system_log"

Best check that your types are aligned. It's likely the XML filter is just not getting applied at all.

**Comment by Rajeshkumar123** [comment]
@driskell  this is different file. I have checked the type it was same only.
