### ISSUE TITLE
Transport init failed

### ISSUE THREAD

**Issue by Rajeshkumar123** [driskell/log-courier#187]
When I start a log courier I am getting following error in logstash
"port"=>10547}←[0m
[33mProtocol error, connection aborted {:error=>"packet too large (2264989696 >
10485760)", :peer=>"127.0.0.1:59212", :level=>:warn, "plugin"=>"input/courier",
"port"=>10547}←[0m
[33mProtocol error, connection aborted {:error=>"packet too large (2264989696 >
10485760)", :peer=>"127.0.0.1:59213", :level=>:warn, "plugin"=>"input/courier",
"port"=>10547}←[0m
[33mProtocol error, connection aborted {:error=>"packet too large (2264989696 >
10485760)", :peer=>"127.0.0.1:59214", :level=>:warn, "plugin"=>"input/courier",
"port"=>10547}←[0m
[33mProtocol error, connection aborted {:error=>"packet too large (2264989696 >
10485760)", :peer=>"127.0.0.1:59215", :level=>:warn, "plugin"=>"input/courier",
"port"=>10547}←[0m
[33mProtocol error, connection aborted {:error=>"packet too large (2264989696 >
10485760)", :peer=>"127.0.0.1:59216", :level=>:warn, "plugin"=>"input/courier",
"port"=>10547}←[0m
[33mProtocol error, connection aborted {:error=>"packet too large (2264989696 >
10485760)", :peer=>"127.0.0.1:59217", :level=>:warn, "plugin"=>"input/courier",
"port"=>10547}←[0m
[33mProtocol error, connection aborted {:error=>"packet too large (2264989696 >
10485760)", :peer=>"127.0.0.1:59218", :level=>:warn, "plugin"=>"input/courier",
"port"=>10547}←[0m

Below is the error I am getting in logcourier
2015/06/11 06:09:07.320312 Attempting to connect to 127.0.0.1:10547
2015/06/11 06:09:07.325196 Transport init failed: TLS Handshake failure with 127
.0.0.1:10547: EOF
2015/06/11 06:09:08.327290 Attempting to connect to 127.0.0.1:10547
2015/06/11 06:09:09.318640 Transport init failed: TLS Handshake failure with 127
.0.0.1:10547: EOF
2015/06/11 06:09:10.320735 Attempting to connect to 127.0.0.1:10547
2015/06/11 06:09:10.326595 Transport init failed: TLS Handshake failure with 127
.0.0.1:10547: EOF
2015/06/11 06:09:11.328689 Attempting to connect to 127.0.0.1:10547
2015/06/11 06:09:11.337479 Transport init failed: TLS Handshake failure with 127
.0.0.1:10547: EOF
2015/06/11 06:09:12.338597 Attempting to connect to 127.0.0.1:10547
2015/06/11 06:09:12.345434 Transport init failed: TLS Handshake failure with 127
.0.0.1:10547: EOF
2015/06/11 06:09:13.346551 Attempting to connect to 127.0.0.1:10547
2015/06/11 06:09:13.354365 Transport init failed: TLS Handshake failure with 127
.0.0.1:10547: EOF
2015/06/11 06:09:14.355482 Attempting to connect to 127.0.0.1:10547
2015/06/11 06:09:15.361483 Transport init failed: Failed to connect to 127.0.0.1

**Comment by driskell** [comment]
You may have configured transport in Logstash courier plugin to plaintext "TCP" and not configured Log Courier to use TCP.

The default, when omitted, is to encrypt all communication with TLS.

**Comment by Rajeshkumar123** [comment]
You are right. Thank you.

**Comment by chilicuil** [comment]
I recently was bitten by this mix-up too, for future readers, this is how the log-courier.conf should look:

```
{
    "network": {
        "transport": "tcp",
        "servers": [ "server:port" ]
    },
   ...
}
```
