### ISSUE TITLE
multiline codec causes log-courier to crash if a line is longer than "max multiline bytes"

### ISSUE THREAD

**Issue by peterholak** [driskell/log-courier#188]
It crashes on
```go
c.buffer = append(c.buffer, text[:cut])
```
with `panic: runtime error: slice bounds out of range` because `cut` ends up being a negative number on the next log line.

From the TODO at the end of the function I see that splitting lines that are too long is not supported yet, however it would be better if the event simply got discarded in such a case (which in my case usually means some corrupted log file) and log-courier kept going instead of crashing.

Tested with `"what": "next"`

**Comment by driskell** [comment]
Thanks! Good spot. I've reproduced in a test and pushed the fix.

**Comment by driskell** [comment]
Splitting lines is actually supported, that TODO should really have been removed, sorry!

**Comment by peterholak** [comment]
Thank you for the fast fix. There are still some issues however, in cases when the lines are either very long (more than twice the "max multiline bytes" size) or when there is a sequence of multiple long lines. I don't know the exact details of when this occurs, but the following test file causes a crash with "max multiline bytes" set to 10, "what" to next, "negate" to true and "pattern" to "^---".

```
1234567890abcdefg
1234567890abc
1234567
---
1234
```

**Comment by driskell** [comment]
Thanks - I reproduced your example as a test exactly, and yes in addition to the previous problem with state not clearing between subsequent splits, if multiple splits were required within the same event (say you sent 20 characters and limit was 5... it would need to split multiple times in that single event) then that would also trigger a crash.

I'm confident this should be fully fixed now. It will loop until all splitting is complete. Let me know if you find any other problems though. I've left the ticket open so you can tell me its fixed rather than any assumption.

**Comment by peterholak** [comment]
There seems to still be an error where cut ends up being -1. I've managed to narrow it down to the following test file

```
0 
---
1 a
2 aa
3 aaa
---
4 aaaa
5 aaaaa
6 aaaaaa
---
7 aaaaaaa
8 aaaaaaaa
9 aaaaaaaaa
---
```

with the codec config being

```
"name": "multiline",
"pattern": "^---",
"what": "next",
"negate": true,
"max multiline bytes": 5
```

**Comment by driskell** [comment]
Reproduced again! Different problem this time. If the buffer was exactly `max multiline bytes` size and not over, it wouldn't flush - it would wait until next event, and that's then where it would fall over.

I'll push the fix shortly - I'm going to rewrite the tests so they assert a bit more and are tidier. If you need it now, it's literally just changing `check_len > c.config.MaxMultilineBytes` to `check_len >= c.config.MaxMultilineBytes`.

**Comment by driskell** [comment]
I've rewritten the tests for the multiline codec to test much more, and found a couple other issues with reported offsets etc. Everything should be working now.

I'm going to keep this open a little longer though - as I think the code can be tidies a bit more and documented a bit better for future readability.

**Comment by driskell** [comment]
I'll close this now. I can do the improvements to code later in the background as I don't have much time for it before 1.8 and need to concentrate on 2.0
