### ISSUE TITLE
Error:cannot assign requested address-bind

### ISSUE THREAD

**Issue by Rajeshkumar123** [driskell/log-courier#190]
I am running log-courier(windows server) and logstash(Linux) in different servers. When I try to connect with logcouier running on different server I am getting this error, " Cannot assign requested address-bind"

Logstash config:
input{
   courier {
                host => "VINIT"  #hostname on which logcourier is running
		port => 10547
		ssl_certificate => "/logcert/log.crt"
		ssl_key         => "/logcert/log.key"
		}
} 

Logcourier config:
"network": {
		"servers": [ "127.0.0.1:10547" ],
		"ssl ca": "C:/Key/log1.crt"
	}

**Comment by driskell** [comment]
The `host` config in Logstash is the `host` on which to LISTEN for connections. This should be omitted (to listen on all interfaces) or set to the IP to bind to. If you set it to a remote IP it won't be able to bind.

**Comment by driskell** [comment]
It's a bad name is `host` - I just wanted to keep compatibility as much with lumberjack plugin. It'll soon be cleaned up and set to `listen_ip` or something

**Comment by Rajeshkumar123** [comment]
I tried with IP address but I am getting same error. What I need to do if I want to listen on remoteip

**Comment by driskell** [comment]
You can't ask a server to listen on a remote IP. That's fundamental in how a network works. A server can only receive connections on its OWN IP.

I also notice your Log Courier is connecting to 127.0.0.1. This is the IP of the "local" machine. You said Logstash is on another server. Log Courier needs to connect to the IP of the remote server. This is also fundamental in how a network works. I apologise if I've misunderstood.

**Comment by Rajeshkumar123** [comment]
I changed my code 

Logcourier config:
"network": {
"servers": [ "xx.xx.xx:10547" ],
"ssl ca": "C:/Key/log1.crt"
}

Logstash config:
input{
courier {
port => 10547
ssl_certificate => "/logcert/log.crt"
ssl_key => "/logcert/log.key"
}
}

Now I am facing the following error.

Connection failed to initialise {:error=>"Received fatal alert: bad_certificate", "network": {
"servers": [ "xx.xx.xx:10547" ],, :level=>:warn, "plugin"=>"input/courier", "port"=>10548}

**Comment by driskell** [comment]
Did you manage to fix the issue? The error would generally be cause by a client trying to connect with a bad certificate - though not sure why - could you try disabling all Log Couriers or running a test environment with just one client and one server with those configs you provided?

**Comment by Rajeshkumar123** [comment]
I tried using "transport"=>tcp the issue was resolved but when trying to connect via TLS it throws
the error

**Comment by driskell** [comment]
I notice in your provided config:

Log Courier
```
"ssl ca": "C:/Key/log1.crt"
```

Logstash
```
ssl_certificate => "/logcert/log.crt"
ssl_key => "/logcert/log.key"
```

Is log.crt and log1.crt the same certificate? Or is log1.crt the Issuer of log.crt?

Essentially, the certificate Log Courier is given must be the Issuer or same certificate as the one Logstash is using. And the one Logstash is using must be paired correctly with its private key in log.key.

**Comment by Rajeshkumar123** [comment]
Those are same certificate only in another server I named it as log1 to differentiate.

**Comment by driskell** [comment]
All I can think is try to use a certificate/key pair generated by the `lc-tlscert` tool that is built alongside log-courier, and see if that works. If it works, then there is a problem with your certificates.

**Comment by driskell** [comment]
I'll close this ticket due to inactivity - if you have issue with certificate still we can keep looking at it.

**Comment by Rajeshkumar123** [comment]
I used tcp transport. The issue was resolved.
