### ISSUE TITLE
cannot start log-courier as service

### ISSUE THREAD

**Issue by mmlumba** [driskell/log-courier#191]
Hello,
I'm trying to start log-courier as a service on my RHEL 5.x server but it seems to fail. It works fine with the standalone command though (`bin/log-courier -config /path/to/config.conf`). This is the error I get:
```
Configuration test: Please specify a configuration file with -config.

  -config="": The config file to load
  -config-test=false: Test the configuration specified by -config and exit
  -cpuprofile="": write cpu profile to file
  -from-beginning=false: On first run, read new files from the beginning instead of the end
  -list-supported=false: List supported transports and codecs
  -stdin=false: Read from stdin instead of files listed in the config file
  -version=false: show version information
                                                           [FAILED]
```
This is my log-courier config file:
```
{
    "network": {
      "servers": [ "xxxxxxxx:6379" ],
          "ssl ca": "/opt/log-courier/ssl/selfsigned.crt"
    },
        "files": [
      {
        "paths": [ "/var/atlassian/application-data/confluence/logs/atlassian-confluence.log"],
        "fields": {"type": "atlassian-confluence"}
      }
    ]
}

```
And this is the indexer piece on Logstash:
```
        #ConfluenceLog
                if [type] == "atlassian-confluence" {
                grok {
                       match   => [ "message", "(?<date>%{YEAR}-%{MONTHNUM}-%{MONTHDAY}) %{TIME:time},%{INT} (?<loglevel>(WARN|SEVERE|ERROR)) %{DATA:source} %{DATA:user} %{GREEDYDATA:errormessage}" ]
                       add_tag => "Confluence"
                }
        }
```
Please let me know if you need anything else to help solve this issue.

Thanks

**Comment by rogerthat** [comment]
you startscript seems to be buggy. 

what is the full command you used to start log-courier as a service?

**Comment by driskell** [comment]
Yes something wrong with the startup script. Could be one of mine!
Where are you installing Log Courier from as I don't provide packages for RHEL 5 due to its age and lack of support from Golang. Though I know the RHEL 6 packages may install fine and will probably work in most cases.

**Comment by driskell** [comment]
If you installed manually and copied the `contrib/initscripts` files to create init script; bear in mind that you'll also need to create `/etc/sysconfig/log-courier` using one of the template files in the same folder, as this is what specifies the path to the configuration file the init script should be using.

**Comment by driskell** [comment]
See: https://github.com/driskell/log-courier/blob/master/contrib/initscripts/log-courier.env
This should be saved to `/etc/sysconfig/log-courier` for use by the init script.

**Comment by mmlumba** [comment]
The `/etc/sysconfig/log-courier` file was missing, and now its working. Thanks again!

**Comment by driskell** [comment]
I'll update the scripts to not require one, really there should be defaults and the sysconfig file only required to override them.

**Comment by driskell** [comment]
@mmlumba Just to check - did you definitely get your init script from the `contrib` folder? It's odd because the init script in there (`redhat-sysv.init`) shouldn't need the `/etc/sysconfig/log-courier` file - it should just work without it.

**Comment by mmlumba** [comment]
Yes I did. I found out the missing Sysconfig file was the issue since one of my servers had that file and the service was working while another did not have the file and it wasn't working. And both use the same init script.
