### ISSUE TITLE
No log-courier packages for Ubuntu precise 12.04

### ISSUE THREAD

**Issue by chilicuil** [driskell/log-courier#192]
Hi,

Thanks for the great alternative to logstash-forwarder, I'm trying log-courier on Ubuntu 12.04 (the vivid package) and it works great, I've looked at https://github.com/driskell/log-courier/blob/master/contrib/ppa_builder and it seems to build precise packages so I wonder if there is other reason to not provide precise packages on https://launchpad.net/~devel-k/+archive/ubuntu/log-courier/+packages

Ubuntu 12.04 EOL will be in a couple of years (2017).

**Comment by driskell** [comment]
The PPA platform only allows 12.04 packages to be installed during the automated build and the version of Golang compiler available is significantly old (version 1.1 I think, or older). Log Courier needs 1.2 at least, preferably 1.4.

Easiest thing is to just install the vivid package (once built its pretty much distribution agnostic.) Eventually I may try get it to work by including a Golang PPA repository with newer versions as a dependency, I'm just not sure how it will impact the end-user - the launchpad docs are very weak on that area.

**Comment by chilicuil** [comment]
Hi,

I've experience with the ppa dependency feature and it doesn't add dependencies on the user, it only adds the dependencies temporary in the virtual environment where the packages are built, so it could be used safely. 

Another alternative could be to copy automatically the vivid package to the precise one after every upload:

http://askubuntu.com/a/591580

Thanks

**Comment by driskell** [comment]
I just added a PPA dependency to include Golang 1.4

So this will in fact make Log Courier faster on Ubuntu when using DEB since it'll be built using newer and better Golang version (1.4 instead of 1.2). It also installs 1.4 onto Precise so there's now a package on its way out for Precise (built successfully but pending as I write this.)
