### ISSUE TITLE
Client Cert Verification Bug, with possible fix.

### ISSUE THREAD

**Issue by packplusplus** [driskell/log-courier#193]
<b>TL;DR</b> Client auth using the logstash agent as a shipper and receiver isn't working. https://github.com/driskell/log-courier/blob/master/lib/log-courier/client_tcp.rb#L233 isn't passing in the ssl object with things like the cert_store, the client cert, the client key. When I insert a little ", ssl" it's magically okay. You want a PR for 4 chars? Or can you just take the credit?

p.s. I had written out this ridiculously long bug report when I found that little shit,  so now you get the wall of text I was amassing in case you ever wanted to turn this into a regression test or see wtf users are doing with your code. 

The server has a cert/key called logging-server.crt/key, from a self signed CA logging-server-ca.crt
The client has a cert/key called logging-client.crt/key, from a self signed CA logging-client-ca.crt 

Verified the certs
<pre>openssl verify -verbose -CAfile logging-client-ca.crt logging-client.crt 
logging-client.crt: OK
openssl verify -verbose -CAfile logging-server-ca.crt logging-server.crt 
logging-server.crt: OK
</pre> 

Using logstash 1.5.1, 
client config:
<pre>
input {
  stdin {
    add_field => { "field1" => "field_data" }
    tags => "mytag"
    type => "sometype"
  }
}
output {
  courier {
    hosts           => [ "loggingserver.local" ]
    port            => 6783
    ssl_certificate => "logging-client.crt"
    ssl_key         => "logging-client.key"
    ssl_ca          => "logging-server-ca.crt"
  }
}</pre>
server config
<pre>input {
  courier {
    port            => 6783
    ssl_certificate => "logging-server.crt"
    ssl_key         => "logging-server.key"
    ssl_verify_ca   => "logstash-client-ca.crt"
    ssl_verify      => true
    ssl_verify_default_ca => false
  }
}

output {
  stdout { codec => rubydebug }
}</pre> 
When I run it I get an error on the client<pre>Connection failed {:error=>"Received fatal alert: bad_certificate", :address=>"loggingserver.local", :port=>6783, :level=>:warn}
</pre>and an error on the server
<pre>Connection failed to initialise {:error=>"null cert chain", :peer=>"127.0.0.1:36019", :level=>:warn}
</pre>

If ssl_verify is set false, the client connects and passes messages. 
If ssl_verify is set to true, and if  "| OpenSSL::SSL::VERIFY_FAIL_IF_NO_PEER_CERT" is commented out in server_tcp.rb it works. So it seemed like either the client cert isn't being sent by the client, or the  the server isn't trusting the client cert. 

I checked https://github.com/driskell/log-courier/blob/master/lib/log-courier/client_tcp.rb#L233, if I pass ssl into that socket everything works.

**Comment by driskell** [comment]
Thanks @packplusplus 

Must say that's a little embarrassing!! :disappointed:

**Comment by packplusplus** [comment]
@driskell any thoughts on the 1.8 release? If there's any bugs blocking I'd love to help out. I'm rolling my own rpms now with this fix and I hate it.
