### ISSUE TITLE
log courier is reading the files repeatedly

### ISSUE THREAD

**Issue by Rajeshkumar123** [driskell/log-courier#194]
log courier is reading the files infinite times. Refer the below logstash trace

2015/06/24 05:20:57.779441 Unexpected file truncation, seeking to beginning(file path)
2015/06/24 05:21:02.420748 Spooler flushing 9 events due to spool timeout exceeded
2015/06/24 05:21:02.420792 Sending new payload of 9 events
2015/06/24 05:21:02.422427 1/10 pending payloads now in transit
2015/06/24 05:21:02.422524 Send now open: Awaiting events for new payload
2015/06/24 05:21:02.425789 ACKN message received for payload 4daddf7516f35ba2f16 d32950fa96cae sequence 9
2015/06/24 05:21:02.425803 No more pending payloads, entering idle
2015/06/24 05:21:02.425829 Registrar received offsets for 9 log entries
2015/06/24 05:21:07.721163 Unexpected file truncation, seeking to beginning:(file path)

**Comment by driskell** [comment]
@Rajeshkumar123 Is this on Windows? Which version of Log Courier? What is logging to the log file? Please can you provide some more information? Thanks!

My initial assumption though is that your log file is not being "appended" to. That is, the logging program is not adding lines to the log file. Instead, my guess is the program is writing a brand new file every time a log entry is written. This means Log Courier thinks the file was reset and started again, and starts reading from the beginning (as you would expect in this scenario). If the program is indeed rewriting existing logs on every single log entry then this is bad behaviour on the logging application side.

**Comment by Rajeshkumar123** [comment]
this is on Linux VM. 
Log Courier version  1.6/1.7
I am logging as xml format in the text files.

**Comment by driskell** [comment]
@Rajeshkumar123 I'm shipping large amount of logs from hundreds of servers and not experienced this, otherwise it would have been fixed. I'll need some more information. Are you able to reproduce it? What are your configurations? What is the data getting logged? Is it detecting truncation when you log to the file, or every 10 seconds even when it isn't logged? As it stands I don't really have an answer if it's not what I previously said - the application logging incorrectly. Did you check how the application is logging?

**Comment by Rajeshkumar123** [comment]
log file looks like a below one.
<?xml version="1.0" encoding="UTF-8"?>
<xmlNodeName>
<time>2015-04-15</time>
</xmlNodeName>

my log courier file looks like below.
{
	"general": {
		"log level" : "debug",
		"persist directory" : "/file directory path"
	},
	"network": {
		"servers": [ "ip" ],
		"ssl ca": "log.crt"
	},
	"files": [
	{
			"paths": 
				 #["logs/*.txt"]
				 ["/logs/a1.txt"],
				  "fields": { "type": "log_source_name" },
			"codec": {
				"name": "multiline",
				"pattern": "<\/.*:xmlNodeName>",
				"negate": true,
				"what": "next"
			},
			"dead time": "1s",
			"event on eof": true
	}
}



logstash config file looks like this.
input {
   courier {
		port => portnumber
		ssl_certificate => "log.crt"
		ssl_key         => "log.key"
	}
}
filter {   

	   if [type] == "log_source_name" {
		xml {
				source => "message"
				store_xml => false 
			xpath => [
				"//ParentNode/ChildNode/text()","field1",
				"//ParentNode/ChildNode/text()","field2",

			}
		}	
	if [type] == "log_source_name"
	{
		fingerprint {
		  source => ["uniqueFieldName1","uniqueFieldName2"]
		  target => "fingerprint"
		  key => "12345678"
		  method => "SHA1"
		  concatenate_sources => true
	   }
	}
}

output{
if [type] == "log_source_name" 
{
	elasticsearch {
	  index => "logstash-%{[type]}-%{+YYYY.MM.dd}"
	  host => "vmhostname"
	  protocol => "http"
	  cluster => "clustername"
	  document_id => "%{fingerprint}" 
	}
}

**Comment by driskell** [comment]
Is the log file appended to or rewritten on each write?

**Comment by driskell** [comment]
Does the unexpected truncation event happen every 10 seconds always, even if the log file is not written to, or at specific times (such as only 10 seconds after the log file is written to) ?

**Comment by Rajeshkumar123** [comment]
The log file getting appended. The truncation happens very frequently(less than 10seconds) same file is reading infinite times.

**Comment by driskell** [comment]
Does the unexpected truncation event happen even if the log file is not written to?

Can you prove example log file for me to test with?

**Comment by Rajeshkumar123** [comment]
is it necessary to have EOF in the log file?
log courier can read a single file with a newline at the end of the file once without any issue.
But when i tried to apply the concept for multiple files (applying EOF), logcourier stops harvesting the files.
The log courier shows the below message and stops there.
Launching harvester on new file: filename
2015/06/25 02:59:57.857816 Started harvester at position 5099 (requested 5099):
 path/file1.txt
2015/06/25 02:59:57.857871 Started harvester at position 5111 (requested 5111):
 path/file2.txt
2015/06/25 02:59:57.857906 Started harvester at position 5144 (requested 5144): 
 path/file3.txt
2015/06/25 02:59:57.858225 Started harvester at position 5100 (requested 5100): 
 path/file4.txt
2015/06/25 02:59:57.858313 Registrar received a new file event for /path/file1.txt
2015/06/25 02:59:57.858329 Registrar received a new file event for /path/file2.txt
2015/06/25 02:59:57.858341 Registrar received a new file event for /path/file3.txt
2015/06/25 02:59:57.858352 Registrar received a new file event for /path/file4.txt
2015/06/25 02:59:57.858589 Connected to ip:portnumber
2015/06/25 02:59:57.858607 Send now open: Awaiting events for new payload
2015/06/25 03:00:07.861959 Stopping harvest of /path/file1.txt last change was 10s ago
2015/06/25 03:00:07.862028 Stopping harvest of /path/file2.txt last change was 10s ago
2015/06/25 03:00:07.862094 Stopping harvest of /path/file3.txt last change was 10s ago
2015/06/25 03:00:07.862126 Stopping harvest of /path/file4.txt last change was 10s ago

**Comment by driskell** [comment]
You've set `"dead time"` to `1s` so Log Courier will stop harvesting if no change in the file in a second.

On first run of Log Courier where no ".log-courier" state exists, it will start all new files from the end of the file. It will only ingest entire files on subsequent runs. This ensures on first install and first run it doesn't start ingesting gigabytes of old log data. So may try running it again.

> is it necessary to have EOF in the log file?

I don't know what you mean. Do you mean is it necessary for the log file to end in a new line? Yes. Log files must end in a new line. Otherwise Log Courier does not know if the line is complete, or if it was half-buffered by a buffered writer (some log outputs are buffered)

**Comment by driskell** [comment]
I will close this due to inactivity and we can reopen if need to.

**Comment by Rajeshkumar123** [comment]
The issue is with end of line some logs didn't have the EOL. It was resolved once I added the EOL to all the logs properly.

**Comment by driskell** [comment]
Thanks. Just FYI about the commit I did for this issue - it improves handling of Multiline codec etc when the file truncates. Previously it would wrap around and potentially save incorrect offsets during shutdown. It was more of an anticipated issue and not one you encountered.
