### ISSUE TITLE
wheezy packaging instructions can't be followed

### ISSUE THREAD

**Issue by tomryanx** [driskell/log-courier#195]
In contrib/README-deb.md

    git clone https://github.com/driskell/log-courier
    tar -czf log-courier_VERSION.orig.tar.gz log-courier
    cd log-courier
    mv contrib/deb debian

However there's no tar.gz file, and neither the deb-systemd nor deb-upstart appear to be usable.  For Jessie I've used the PPA package to successfully build a package - is there a straightforward way to package for Wheezy?

Thanks in advance, very much enjoying log-courier

**Comment by driskell** [comment]
The `tar -czf` command creates the `.tar.gz` from the cloned source, which is used to tell debian package builder, "this tar contains the upstream source, the log-courier folder contains the debian-modified source". This allows me to keep the debian specific stuff in contrib folder out of the way. When building the package debian creates a patch for the debian folder you move from contrib.

**Comment by tomryanx** [comment]
Sorry, you're right, I had failed to follow the instructions to the letter in several different ways!  Paid much closer attention this time and hit this:

    $ mkdir logcourier
    $ cd logcourier/
    $ git clone https://github.com/driskell/log-courier
    Cloning into 'log-courier'...
    remote: Counting objects: 7546, done.
    remote: Compressing objects: 100% (12/12), done.
    remote: Total 7546 (delta 1), reused 0 (delta 0), pack-reused 7534
    Receiving objects: 100% (7546/7546), 1.72 MiB | 2.21 MiB/s, done.
    Resolving deltas: 100% (4612/4612), done.
    $ cat log-courier/version_short.txt 
    1.7
    $ tar -czf log-courier_1.7.orig.tar.gz log-courier
    $ cd log-courier/
    $ mv contrib/deb debian
    mv: cannot stat `contrib/deb': No such file or directory
    $ ls -d contrib/deb*
    contrib/deb-systemd/  contrib/deb-upstart/
    $

**Comment by tomryanx** [comment]
Trying again, cloning "-b stable"

**Comment by driskell** [comment]
Ah sorry yes. There are two folders so the instructions need updating.

```
mv contrib/deb-upstart debian
```

Use the above for upstart init script package. For a systemd package, use the systemd folder.

**Comment by tomryanx** [comment]
We're using neither systemd nor upstart.  The following more or less worked for me.  (it would be good to know whether it's a bad idea for any reason to use stable)

    $ git clone -b stable https://github.com/driskell/log-courier
    $ tar -czf log-courier_1.6.orig.tar.gz log-courier
    $ cd log-courier/
    $ mv contrib/deb debian
    $ dpkg-buildpackage -uc -us

I notice the version numbers are a little out of sync, but that's no biggy.  I'm still hitting something on the postinst:

    # dpkg -i log-courier_1.6-4_amd64.deb 
    Selecting previously unselected package log-courier.
    (Reading database ... 29155 files and directories currently installed.)
    Unpacking log-courier (from log-courier_1.6-4_amd64.deb) ...
    Setting up log-courier (1.6-4) ...
    # service status log-courier
    status: unrecognized service
    # ls -l /etc/{rc,init}*/*log-courier
    -rwxr-xr-x 1 root root 2201 Jun 24 15:43 /etc/init.d/log-courier
    lrwxrwxrwx 1 root root   21 Jun 24 16:17 /etc/rc0.d/K01log-courier -> ../init.d/log-courier
    lrwxrwxrwx 1 root root   21 Jun 24 16:17 /etc/rc1.d/K01log-courier -> ../init.d/log-courier
    lrwxrwxrwx 1 root root   21 Jun 24 16:17 /etc/rc2.d/S01log-courier -> ../init.d/log-courier
    lrwxrwxrwx 1 root root   21 Jun 24 16:17 /etc/rc3.d/S01log-courier -> ../init.d/log-courier
    lrwxrwxrwx 1 root root   21 Jun 24 16:17 /etc/rc4.d/S01log-courier -> ../init.d/log-courier
    lrwxrwxrwx 1 root root   21 Jun 24 16:17 /etc/rc5.d/S01log-courier -> ../init.d/log-courier
    lrwxrwxrwx 1 root root   21 Jun 24 16:17 /etc/rc6.d/K01log-courier -> ../init.d/log-courier
    # service --status-all 2>&1 | grep log-courier
     [ - ]  log-courier
    #

**Comment by driskell** [comment]
What are you using? Based on the output you've provided it looks like upstart.

Have you tried: `service log-courier status` ?

**Comment by tomryanx** [comment]
Thanks for your patience.  You're right "service status log-courier" was always going to fail.  I'd say I'm good now.

Have a better one!

**Comment by driskell** [comment]
Using stable is your best bet. `master` is actively developed so is not guaranteed to be feature complete, so new features may be unfinished or subject to change. `stable` is guaranteed to be feature complete.

Also the `stable` branch tends to be a little better tested, but generally by `stable` it just means feature-wise.

**Comment by driskell** [comment]
I should probably rename that branch to `release`... :grin:
