### ISSUE TITLE
using tls as a transport

### ISSUE THREAD

**Issue by madhusudand** [driskell/log-courier#196]
small clarrification required: can we use any certificate and key pair  for communication between logstash and log-courier ??
I mean certificate generated by openssl or any tool ,not using lc-tls cert ,certificate generated not bound to any ip(logstash server ip). 
And it will be really help full if you explain how tls trannsport happens with respect to log-courier and logstash..
Thanks in advance....

**Comment by driskell** [comment]
Yes

Just bear in mind the certificate logstash is using must match the hostname used to connect to it or log courier will fail verification.

**Comment by driskell** [comment]
lc-tlscert just makes it easier especially in the case where you connect to logstash using an IP, as the logstash certificate needs something called IPSAN that the client can verify against (common name is used for host names and only for host names, not IPs). Adding IPSAN with other tools can be difficult - OpenSSL you need a config file to do it.

At the end of the day though, using host names only and the etc hosts file where necessary gets around all the problems.

**Comment by madhusudand** [comment]
"Just bear in mind the certificate logstash is using must match the hostname used to connect to it or log courier will fail verification"
here i am using IP for connecting to logstash. do u  mean that the certificate must be bound to IP address ??

**Comment by driskell** [comment]
I do not know the requirements of the certificate. I would think any standard server certificate will work. Key signing certificates etc I do not know, but would guess they will NOT work.

> Just bear in mind the certificate logstash is using must match the hostname used to connect to it or log courier will fail verification

If you connect via IP, the certificate on Logstash side must contain that IP in the Subject Alternative Names as an IP address entry. The common name is ignored if you connect via IP address as the hostname is considered unknown. The workaround for this is to connect via hostname ALWAYS, and to create a entry in /etc/hosts if you do not have the capability to setup DNS for the hostname.

For example, connecting to 123.123.123.123 you would need a certificate, Common Name "logstash.example.com" with Subject Alternative Names containing "IP:123.123.123.123" as a special IP entry. Alternatively, connect to "logstash.example.com" and put in the /etc/hosts file logstash.example.com with IP address 123.123.123.123, then the certificate need not contain the IP.

**Comment by driskell** [comment]
`lc-tlscert` makes adding the Subject Alternative Names really easily. It automatically detects if you give hostname or IP and creates the correct kind of entry. Using OpenSSL it is not easy to do SAN at all - in fact its impossible on command line, you need to setup a full OpenSSL CNF configuration.

**Comment by driskell** [comment]
Also, bear in mind if getting TLS gets too difficult, and you don't actually need the connection encrypted or authenticated, you can switch to plain TCP - see the `"transport"` configuration option.

**Comment by jkahrs** [comment]
Maybe one could expose InsecureSkipVerify as an optional parameter (https://golang.org/src/crypto/tls/common.go?s=8340:12616#L233) for testing purposes within the configuration.

**Comment by driskell** [comment]
@jkahrs That would just disable verification and I don't know how that would help with testing where using TCP would not.

**Comment by driskell** [comment]
I will close this now due to inactivity but we can reopen if need be.
