### ISSUE TITLE
installing log-courier plugin for logstash-1.5.0 manually 

### ISSUE THREAD

**Issue by madhusudand** [driskell/log-courier#198]
i am installing log-courier plugin for logstah-1.5.2 /1.5.0 manually because of some restriction. the steps are like this :
cd /path/to/logstash
export GEM_HOME=vendor/bundle/jruby/1.9
java -jar vendor/jar/jruby-complete-1.7.11.jar -S gem install /path/to/the.gem /path/to/next.gem /path/to/more.gem

but i am not able to find this "vendor/jar/jruby-complete-1.7.11.jar" in logstash-1.5.0
please help me to resolve this.

can u please tell me what bin/plugin install will do, so that i can have all dependencies offline and run some script to install courier plugin. 
P.S : i dont know ruby..

Thanks in advance

**Comment by driskell** [comment]
Yes this needs some testing and documentation improvements. I'll add them to the roadmap as these install aspects need tidying up.

**Comment by madhusudand** [comment]
thanks for the reply.... 
Is there any workaround as of now for manual installation.. specifically this step..
**but i am not able to find this "vendor/jar/jruby-complete-1.7.11.jar" in logstash-1.5.0
 
I have some deliverables dependent on upgrading logstash to 1.5.*  ..

**Comment by driskell** [comment]
I will close this now. There's some work for me to do on Logstash 2 support etc. and improving docs for it, and this refers back to 1.5 which is now fairly old.
