### ISSUE TITLE
Feature request: lc-admin status to show the server we are connected to.

### ISSUE THREAD

**Issue by dsolsona** [driskell/log-courier#199]
Hi,

Would it be possible to show to which server is log-courier connected when running `lc-admin status` command?

```
Publisher:
  Status: Connected
  Server: your.logstash.server
  Speed (Lps): 36.34
  Published lines: 18281902
  Pending Payloads: 1
  Timeouts: 3
  Retransmissions: 0
```

**Comment by driskell** [comment]
Yes this is on my roadmap :)

**Comment by driskell** [comment]
Will implement in v2 as it's complex to attempt this with ZMQ still there, as it handles the endpoints.
