### ISSUE TITLE
Support for property placeholder in Configuration

### ISSUE THREAD

**Issue by dkirrane** [driskell/log-courier#201]
It would be a nice enhancement if I could use property place holder inside the Configuration.
Something like `${property-placeholder}` in the Configuration. E.g:
```
{
...
    # Define some properties
    "properties": {
	   "root-directory": "/var/log"
    },
    # Re-use properties
    "files": [
        {
            "paths": ["${root-directory}/supervisor/supervisord.log"]
        },
        {
            "paths": ["${root-directory}/servers/server1/*.log", "${root-directory}/servers/server2/*.log""],
        }
    ]
}
```

**Comment by driskell** [comment]
Could you provide some more info of your use case?

In general I would expect the root directory so always be the same on the servers, especially `/var/log`. So it seems a lot of code would be going into Log Courier to handle a fairly rare edge case that might be better handled in another way (ensuring directory always the same or using a common symlink.) It could make configurations that little harder to read too if they are large, as you'd need to scroll back around to find the properties you need.

**Comment by dkirrane** [comment]
So our application has 2 deployments Windows and Linux and the root log directory changes.
Agreed this is a nice-to-have but if it takes a lot of code then possibly not worth it.
