### ISSUE TITLE
make with=zmq4 fails, 'could not determine kind of name for C.free'

### ISSUE THREAD

**Issue by gpurrenhage** [driskell/log-courier#207]
First off: thanks--I've been using log-courier for a while and it's better than any other logstash agent I've found.

But, I'm sometimes having a problem trying to compile on Ubuntu 14.04, using latest go (1.4.2), libsodium (1.0.3), and zeromq (4.1.2).

This script has generally worked:
    git clone https://github.com/driskell/log-courier /opt/log-courier
    export PATH=/usr/local/go/bin:$PATH
    export PKG_CONFIG_PATH=/opt/zeromq-4.1.2/src:$PKG_CONFIG_PATH
    cd /opt/log-courier
    git checkout tags/v1.7
    make with=zmq4

But in a few servers, it's failing to 'make'.  I can't see anything particularly different about these servers:
    root@couriertest:/opt/log-courier# git checkout tags/v1.7
    HEAD is now at 4f0279f... Merge branch 'master' into stable
    root@couriertest:/opt/log-courier# make with=zmq4
    build/fix_version ""
    Set Log Courier Version 1.7
    build/setup_root
    GOPATH: /opt/log-courier
    go get -d -tags " zmq zmq_4_x" log-courier
    go install -tags " zmq zmq_4_x" log-courier
    # github.com/driskell/log-courier/src/lc-lib/transports
    could not determine kind of name for C.free
    make: *** [bin/log-courier] Error 2

Any insight you can provide would be greatly appreciated.

**Comment by driskell** [comment]
FYI in version 2 I'll be removing the ZeroMQ feature in favour of improving the TCP/TLS transports.

I'm not entirely sure what is happening here though but it may be there are missing glibc headers or something or incompatible versions/stubs of them installed. Is it happening all the time or only sometimes?

**Comment by gpurrenhage** [comment]
I did discover that moving back to the last stable version of zmq (4.0.7) eliminated this problem for me.  But then yes, I saw that you're removing zmq so I switched back to TLS.  Now it works, but I miss the automatic load balancing :-).

**Comment by driskell** [comment]
Good to know.

Watch this space though - I just need to do some cleanup and version 2 will have load balancing over TLS :)
