### ISSUE TITLE
logstash plugin at java-8: Transport error, will try again: Unknown message received

### ISSUE THREAD

**Issue by kabakaev** [driskell/log-courier#208]
### Summary
When running `logstash` on Java-8, the `log-courier` issues warning *Transport error, will try again: Unknown message received* every second. If `logstash` is run on Java-7, there is no such error message.

This can cause trouble in the future, because usage of Java-7 is deprecated in current `logstash`.

### Steps to reproduce
* Install Debian GNU/Linux 8.1 (jessie).

* Install Java-8: `apt-get install openjdk-8-jre-headless`
```
$ java -version
openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
```

* Install elasticsearch and logstash from official repos. Installed logstash version is 1.5.3-1.

* Install input plugin: `cd /opt/logstash ; bin/plugin install logstash-input-courier`.

* Configure input plugin:
```
input {
  courier {
# readme: https://github.com/driskell/log-courier/blob/master/docs/LogstashIntegration.md
    transport       => "tls"
    max_packet_size => 104857600
    port            => 12345
    ssl_certificate => "/etc/logstash/ca/keys/server.hostname.net.crt"
    ssl_key         => "/etc/logstash/ca/keys/server.hostname.net.key"
  }
}
```

* Configure log-courier
```
{
  "general": {
    "log level": "debug",
    "log file": "/var/log/log-courier/log-courier.log"
  },
  "network": {
    "servers": [ "server.hostname.net:12345" ],
    "ssl ca": "/etc/log-courier/ca.crt",
    "timeout": 15
  },

  "files": [
    {
      "paths": [
        "/var/log/*.log",
        "/var/log/redis/*.log",
        "/var/log/mysql/mysql-slow.log",
        "/var/log/syslog",
        "/var/log/nonexistent_placeholder_system"
      ],
      "fields": {
        "type": "system",
        "project_name": "STAGING"
      }
    }
  ]
}
```

* see errors in `/var/log/log-courier/log-courier.log` repeating every second
```
2015/07/22 19:23:13.094149 Attempting to connect to 136.243.0.1:12345 (server.hostname.net)
2015/07/22 19:23:13.238214 Connected to 136.243.0.1:12345 (server.hostname.net)
2015/07/22 19:23:13.238246 Send now open: Retrying next payload
2015/07/22 19:23:13.238333 Send now open: Awaiting events for new payload
2015/07/22 19:23:13.240712 ACKN message received for payload d7fc4db99eec61a16d2cbeb7143381e0 sequence 17
2015/07/22 19:23:13.240731 No more pending payloads, entering idle
2015/07/22 19:23:13.240750 Registrar received offsets for 17 log entries
2015/07/22 19:23:15.086663 Spooler flushing 7 events due to spool timeout exceeded
2015/07/22 19:23:15.086719 Sending new payload of 7 events
2015/07/22 19:23:15.087318 1/10 pending payloads now in transit
2015/07/22 19:23:15.087415 Send now open: Awaiting events for new payload
2015/07/22 19:23:15.089340 Transport error, will try again: Unknown message received: 86 45 3F 00
2015/07/22 19:23:18.093041 Attempting to connect to 136.243.0.1:12345 (server.hostname.net)
etc.
```

**Comment by driskell** [comment]
Do you see anything in the Logstash logs?

**Comment by eliecharra** [comment]
Java version isn't in cause, i've the same problem with :

```
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
```

```
$ cat /etc/log-courier/log-courier.conf 
```
```json
{
  "network": {
    "servers": [ "logstash.example.com:5000" ],

    "ssl certificate": "/etc/pki/tls/certs/log_courier.pem",
    "ssl key": "/etc/pki/tls/certs/log_courier.key",
    "ssl ca": "/etc/pki/tls/certs/ca.pem",

    "timeout": 15
  },

"general": {
    "log level": "debug",
    "log file": "/var/log/log-courier.log"
  },

  "files": [
                {
      "paths": [
                    "/var/log/apache2/*access*.log",
                    "/var/www/*/shared/*/logs/*access*_log"
                          ],
      "fields": { "type": "apache" }
    },            {
      "paths": [
                    "/var/log/*.log"
                          ],
      "fields": { "type": "syslog" }
    },            {
      "paths": [
                    "/var/log/apache2/*error*.log",
                    "/var/www/*/shared/*/logs/*error*_log"
                          ],
      "fields": { "type": "apache_error" }
    }
 ]
}
```

```
2015/08/03 17:50:42.730120 Connected to XX.XX.XX.XX:5000 (logstash.example.com)
2015/08/03 17:50:42.730238 Send now open: Awaiting events for new payload
2015/08/03 17:50:47.624305 Spooler flushing 142 events due to spool timeout exceeded
2015/08/03 17:50:47.624447 Sending new payload of 142 events
2015/08/03 17:50:47.631045 1/10 pending payloads now in transit
2015/08/03 17:50:47.631838 Send now open: Awaiting events for new payload
2015/08/03 17:50:47.680048 ACKN message received for payload 32ccdda4bce033587ddc577969af18bc sequence 142
2015/08/03 17:50:47.680150 No more pending payloads, entering idle
2015/08/03 17:50:47.680233 Registrar received offsets for 142 log entries
2015/08/03 17:50:52.624591 Spooler flushing 7 events due to spool timeout exceeded
2015/08/03 17:50:52.624727 Sending new payload of 7 events
2015/08/03 17:50:52.626405 1/10 pending payloads now in transit
2015/08/03 17:50:52.626933 Send now open: Awaiting events for new payload
2015/08/03 17:50:52.630186 Transport error, will try again: Unknown message received: 62 35 85 00
2015/08/03 17:50:54.631018 Attempting to connect to XX.XX.XX.XX:5000 (logstash.example.com)
2015/08/03 17:50:54.726087 Connected to XX.XX.XX.XX:5000 (logstash.example.com)
2015/08/03 17:50:54.726202 Send now open: Retrying next payload
2015/08/03 17:50:54.726803 Send now open: Awaiting events for new payload
2015/08/03 17:50:54.729001 ACKN message received for payload 8abb79b0acf26b3316e721c6bc623585 sequence 7
2015/08/03 17:50:54.729097 No more pending payloads, entering idle
2015/08/03 17:50:54.729450 Registrar received offsets for 7 log entries
2015/08/03 17:50:57.624868 Spooler flushing 13 events due to spool timeout exceeded
2015/08/03 17:50:57.625266 Sending new payload of 13 events
2015/08/03 17:50:57.630157 1/10 pending payloads now in transit
2015/08/03 17:50:57.630521 Send now open: Awaiting events for new payload
2015/08/03 17:50:57.634692 Transport error, will try again: Unknown message received: 6A E9 E7 00
2015/08/03 17:50:59.635447 Attempting to connect to XX.XX.XX.XX:5000 (logstash.example.com)
```

@driskell In my logstash logs :

```
{:timestamp=>"2015-08-03T17:46:13.540000+0200", :message=>"Connection aborted", :error=>"Connection reset by peer", :peer=>"XX.XX.XX.XX:35992", :level=>:warn}
```

**Comment by driskell** [comment]
Can you run Logstash in debug mode? It might produce a huge amount of output though but if you could filter it to "knowledging" with `| grep knowledging` it will only print the debug output from the courier plugin where it acknowledges events. With some luck it gives a little more information but this is looking really odd to me.

Does it always happen after one ACKN? As in, every time it connects it always succeeds with a single ACKN, but the second one always fails?

NB: Duplication is likely here if Logstash was successful in processing the events, and the ACK never got back to Log Courier. If the above about always the second packet failing is true I would expect exactly 2 of every event except the first few.

**Comment by driskell** [comment]
@kabakaev Do you know what your Logstash version was? Just want to rule out it being a Logstash version issue.

**Comment by eliecharra** [comment]
@driskell This error always happen after ans ACKN yeah, following pattern is always the same ans repeating :

```
2015/08/03 18:32:24.918161 Connected to XX.XX.XX.XX:5000 (logstash.example.com)
2015/08/03 18:32:24.918287 Send now open: Retrying next payload
2015/08/03 18:32:24.919091 Send now open: Awaiting events for new payload
2015/08/03 18:32:24.924899 ACKN message received for payload 0838267fc221acc4f2705228275b39ee sequence 13
2015/08/03 18:32:24.925001 No more pending payloads, entering idle
2015/08/03 18:32:24.925097 Registrar received offsets for 13 log entries
2015/08/03 18:32:27.812283 Spooler flushing 13 events due to spool timeout exceeded
2015/08/03 18:32:27.812424 Sending new payload of 13 events
2015/08/03 18:32:27.816355 1/10 pending payloads now in transit
2015/08/03 18:32:27.816696 Send now open: Awaiting events for new payload
2015/08/03 18:32:27.824449 Transport error, will try again: Unknown message received: C8 D8 CC 00
```

Here is my logstash trace in debug mode

![debug](https://cloud.githubusercontent.com/assets/6154987/9042537/ac0183d0-3a0f-11e5-9687-db44597f1f6b.png)

**Comment by driskell** [comment]
Wow it's the last 3 octets of the second ACKN plus a null byte... I'll investigate a bit!

**Comment by eliecharra** [comment]
@driskell Thks ! Lemme know if you need additional traces

**Comment by packplusplus** [comment]
@driskell I have a user reporting this error. I haven't seen it, but I'll try java7 and see if I can also add to the report.

**Comment by packplusplus** [comment]
Could this have anything to do with @jordansissel tightening up the logstash ssl setting across the app.

**Comment by kabakaev** [comment]
@driskell, i have  version 1.5.3-1 of logstash from official elastic.co repo. You may try to reproduce the environment in a Debian-8 virtual machine, steps are given explicitly. If needed, I could prepare a Vagrantfile with reproducible buggy environment.

**Comment by driskell** [comment]
OK, managed to reproduce it. It looks like it's a mixture of things.

Due to the tightened ciphers on the Logstash side the acknowledgements are now crossing record borders, whereas previously they would slot within a single record (this is my assumption anyway).

Now, on the Log Courier side, the Golang TLS read used to return full reads all the time, however it is no longer returning full reads, it's actually returning a partial read for the second acknowledgement of always 1 single byte. It actually returns `read:1 error:nil` - this is unexpected to me, I would expect it to block until it read all requested bytes and return `read:8 error:nil`, and only return a partial read alongside a timeout error such as `read:1 error:Timeout`.

I've hardened the Read/Write handling in Log Courier to prevent this and pushed to master. I will aim to release 1.8 with this fix this week once you can confirm it fixes the problem for you.

I'll also try to throw up a quick Golang reproduce case and check with other Golang developers on whether this is meant to happen or not, and if the documentation should be updated if it is, or the code fixed to block if it isn't.

**Comment by driskell** [comment]
Reopening so you can confirm fix.

**Comment by eliecharra** [comment]
Thanks for your fix !
Here is my new trace, i'll try to investigate a bit

```
015/08/04 10:44:03.126122 Connected to XX.XX.XX.XX:5000 (logstash.kitservice.net)
2015/08/04 10:44:03.126285 Send now open: Awaiting events for new payload
2015/08/04 10:44:04.126665 socket.Read err: read tcp XX.XX.XX.XX:5000: i/o timeout
2015/08/04 10:44:05.126948 socket.Read err: read tcp XX.XX.XX.XX:5000: i/o timeout
2015/08/04 10:44:06.127301 socket.Read err: read tcp XX.XX.XX.XX:5000: i/o timeout
2015/08/04 10:44:07.127583 socket.Read err: read tcp XX.XX.XX.XX:5000: i/o timeout
2015/08/04 10:44:08.003558 Spooler flushing 13 events due to spool timeout exceeded
2015/08/04 10:44:08.003723 Sending new payload of 13 events
2015/08/04 10:44:08.008751 1/10 pending payloads now in transit
2015/08/04 10:44:08.009271 Send now open: Awaiting events for new payload
2015/08/04 10:44:08.014388 socket.Read err: <nil>
2015/08/04 10:44:08.014500 socket.Read err: <nil>
2015/08/04 10:44:08.014751 ACKN message received for payload efeb1e7dcbe09a13a2be65a73933e21b sequence 13
2015/08/04 10:44:08.014973 No more pending payloads, entering idle
2015/08/04 10:44:08.015289 Registrar received offsets for 13 log entries
2015/08/04 10:44:09.014805 socket.Read err: read tcp XX.XX.XX.XX:5000: i/o timeout
2015/08/04 10:44:10.015180 socket.Read err: read tcpXX.XX.XX.XX:5000: i/o timeout
2015/08/04 10:44:11.015495 socket.Read err: read tcp XX.XX.XX.XX:5000: i/o timeout
2015/08/04 10:44:12.015803 socket.Read err: read tcp XX.XX.XX.XX:5000: i/o timeout
2015/08/04 10:44:13.016098 socket.Read err: read tcp XX.XX.XX.XX:5000: i/o timeout
2015/08/04 10:44:14.016477 socket.Read err: read tcp XX.XX.XX.XX:5000: i/o timeout
2015/08/04 10:44:15.016792 socket.Read err: read tcp XX.XX.XX.XX:5000: i/o timeout
```

Anyway :+1: to integrate this fix in 1.8

**Comment by driskell** [comment]
Thanks. I'll drop that last debug line.

It's definitely an error on my part - apologies for the problem everyone. Thanks for all the logs and helping get to the bottom of it!
The Reader interface is explicitly documented as being able to return n != len(p) along with no error.
https://golang.org/pkg/io/#Reader

**Comment by driskell** [comment]
@eliecharra The `socket.Read err` is a debug entry I placed in when testing and is normal - I've just pushed a commit to remove it. All reads timeout after about a second so that it can check for shutdown and shutdown gracefully - nothing to worry about. If you pull latest commit it'll disappear :+1:

**Comment by eliecharra** [comment]
@driskell Yeah I can see that, just checking data consistence in logstash side, seems to be all good :+1: 
Thanks for investigating and quick fix :smiley:

**Comment by kabakaev** [comment]
@driskell, the fix is working. Just compiled from master, no issues. Thanks!
