### ISSUE TITLE
Too Many files Open

### ISSUE THREAD

**Issue by MichaelLiZhou** [driskell/log-courier#209]
Was running for about a day or two then these messages started to show up:
2015/07/23 18:59:14.390627 Registry write failed: open ./.log-courier.new: too many open files
2015/07/23 18:59:14.982363 Registry write failed: open ./.log-courier.new: too many open files
2015/07/23 18:59:24.393966 Registry write failed: open ./.log-courier.new: too many open files

**Comment by driskell** [comment]
I'm assuming you're on Linux of some kind as you didn't say.

This tends to happen when the number of log files Log Courier has open exceeds your operating systems open file limit (usually around 1024).

How many files match the paths set in the config file?

Setting "dead time" in the files config may help as it tells Log Courier to not keep open files older than that time period. See the configuration docs for more info. Default is 24h so if you have over a thousand matching files all modified within last day then this issue can occur.

Other option is to increase the operating system open file limit - you could use "ulimit" in the /etc/default or /etc/sysconfig file to do so if you've set up Log Courier as a service.

**Comment by MichaelLiZhou** [comment]
Thanks for the quick reply! Yes its on a suse box. And yes it is around 1000+ files because instead of rolling 1 log it just keeps adding 4 log files (11mb each) every minute. Thanks for the solution I will try to kill after about 10-15 minutes.

**Comment by driskell** [comment]
Every 10 seconds or so the paths in the Log Courier config file are scanned again. If the modification time of a file it had previously closed changes it will open the file again and resume at the last known position.

So it won't miss anything :)

Just bear in mind this scanning of files may become intensive as the file count rises because it has to stat every file to check for rotations, deletions, movements etc. For 1000 files I guess you may want to look at the `prospector interval` setting too so you can space it out a bit.

Ideally you would want to ensure old files are moved elsewhere or removed to keep the scanning intensity low. I was looked at a `move when dead` option at some point but there was little demand for it.

**Comment by MichaelLiZhou** [comment]
I am not sure what the prospector interval does but I will look into this setting. 

For the move when dead I think this is a great idea if you are working on system you cal easily change. My situation is a little different. I am consolidating logs on application that has many working modules and someone (don't know who) has decided to compress these logs which gets deleted... Don't know why. So I do not want to move or change too many settings. My goal is to do this without others noticing large effects or minimize their changes.  

I was given an okay to unlimit the amount of files opened. But now you brought up the CPU killer.

So I want to purpose this (probably only works here): The log files that are generated have this in common once the file reaches ~11mb it moves on to create another with a unique timestamp in the name. And older files will actually never be updated! Is there away never check those files and only look at the most recently updated file?

If you think this is possible I will try to work on something like this as a solution. I have never written anything in Go but I have some free time til the end of the summer so I will be glad to work on this if feasible.

**Comment by driskell** [comment]
I think your best bet is just use the `dead time` then. The prospector is going to scan and stat the files anyway but at least open files is kept low. You can increase `prospector interval` to increase how often it checks for new files so reduce impact of scanning thousands of files.

Dead time already does the check for latest files. If the file is old it is ignored until it is changed. The only improvement could be to never check that file again but that could be bad and unexpected if one DOES change or if there is a clock change that makes a 1 minute old file 1 hour and 1 minute old for example.

`dead time` and increased `prospector interval` I think is best for now. If you still have issues after that we can look further in how to handle this.

**Comment by MichaelLiZhou** [comment]
Alright I will try to look out for the performance with proposed solution. When I have the time I will see if I can think of a way to never look at files. I know for sure that these older files will not change because someone set a default size of the log file and at times max utilization these logs fill up every 10-15 seconds for about an hour. After filled to 11mb create another file. My current thoughts on the logic:
if new log indexed --> close all other
otherwise continually look at most recently changed log

**Comment by driskell** [comment]
If it's OK I'll close this now as the original issue should be fixed (pending any performance issue but with 1000 files it might be fine).
