### ISSUE TITLE
Configuration - Advice for High-Volume-Logfiles wanted

### ISSUE THREAD

**Issue by rogerthat** [driskell/log-courier#210]
Hi,

we're transfering logfiles with log-courier taht are generating ~1GB data per minute. 

when running weith default-settings we see a high delay between the time a logentry is written and the time it is received and processed by logstash-input.

what would be the best options to play with to prevent any delay for such a setup?
and advice, even by try&error would be apppreciated. 

cheers, 

mex

**Comment by driskell** [comment]
> when running weith default-settings we see a high delay between the time a logentry is written and the time it is received and processed by logstash-input.

How are you measuring this time? Can you define exactly "high delay"?

One good way to see if the bottleneck is the transport or Logstash itself is to use `admin enabled` and the various admin options, then use `lc-admin` tool to connect to the running Log Courier and get the status: `lc-admin -connect unix:/var/run/log-courier.socket status`. This will have a Publisher section that says how many Pending Payloads. If this number is always 10 then Logstash is the bottleneck (usually the filters, though could be the input). If this number is always low then it's a bottleneck on the sender.

**Comment by driskell** [comment]
One thing is to make sure your Logstash is using 100% CPU - if not then you need to tune it. Best tuning I find is `-w` - for example running Logstash with `-w 8` sets 8 filter workers which means more threads for processing. Ultimately you may eventually hit Logstash output as the bottleneck.
