### ISSUE TITLE
Either 'ssl_verify_default_ca' or 'ssl_verify_ca' must be specified when ssl_verify is true"}

### ISSUE THREAD

**Issue by packplusplus** [driskell/log-courier#214]
Not passing ssl_verify_ca in /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-courier-1.8/lib/logstash/inputs/courier.rb on line 117 or 118. You want a PR? Also, any shot you can re-release 1.8, this is kind of a big deal (booo regressions). 

happened on : 23144a32240c38bdd3e12df2382c20c6a775a5cb

**Comment by driskell** [comment]
> (boo regressions)

Aye :-(
It's the one area that has zero test coverage. When I do v2 I'm going to get that covered and maybe split up into separate repositories so I can follow more inline with other Logstash plugins.
Sorry about this. I'll send out a 1.8.1 update as soon as I can.
