### ISSUE TITLE
"The error reported is: \n  undefined method `addresses'

### ISSUE THREAD

**Issue by packplusplus** [driskell/log-courier#215]
in the 1.8 release, /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-courier-1.8/lib/logstash/outputs/courier.rb looks has a configuration input called hosts, but then passes addresses to the module. 

changing hosts to addresses seems to work (update courier.rb and your config file).

Breaking change not in the release notes.

**Comment by driskell** [comment]
When I release 1.8.1 to fix these regressions I will revert it back to `hosts` again. Apologies for the regressions.
