### ISSUE TITLE
first char of peer_ssl_cn trimmed off

### ISSUE THREAD

**Issue by packplusplus** [driskell/log-courier#216]
Seemed to happen on the upgrade to 1.8, but I have a mix of 1.4 and 1.5 running. Investigating versions.

**Comment by driskell** [comment]
Can you provide more information? This part of the code wasn't touched as far as I can remember. I'll investigate it though once the other regressions are fixed.

**Comment by packplusplus** [comment]
When I test locally (courier to logstash, or logstash to logstash) I can't reproduce it, but prod i'm seeing it. I'm still poking.

**Comment by packplusplus** [comment]
Seems to be a single older client (1.4 something). Trying to get a usecase pulled together.

**Comment by driskell** [comment]
I'll close this as I wasn't able to work out the issue.
