### ISSUE TITLE
Logstash service starting then stopping immediately .conf error  

### ISSUE THREAD

**Issue by obhabib** [driskell/log-courier#220]
When starting the logstash service it starts but stops running in about 3 seconds. I get the following error message in the logs: :message=>"Error: Expected one of #, input, filter, output at line 65, column 1 
:message=>"You may be interested in the '--configtest' flag which you can\nuse to validate logstash's configuration before you choose\nto restart a running system."}

We have used the --config test and the configuration is ok. 

Any idea why this is happening? Was running fine previously with the same .conf....

**Comment by driskell** [comment]
I don't mean to sound blunt, but what makes you believe it to be a Log Courier issue? Might be best reported in the logstash repository.

**Comment by driskell** [comment]
I'll close this as it looks to be a logstash problem with faulty conf file.
