### ISSUE TITLE
The error reported is:input/courier: Failed to initialise: No message available

### ISSUE THREAD

**Issue by ramreddy26** [driskell/log-courier#221]
Hi @driskell , I am getting below error when I run logstash, It was fine till last week. But I am seeing this error since 2 days, I tried upgrading logstash to 1.5.3 but still same error. Could you please help me troubleshoot this ? 

Starting courier input listener {:address=>"0.0.0.0:6379", :level=>:info, :file=>"logstash/inputs/courier.rb", :line=>"92", :method=>"                                                                             register"}
The error reported is:
  input/courier: Failed to initialise: No message available
/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.8.1/lib/log-courier/server_tcp.rb:137:in `initialize'
/opt/logstash/vendor/bundle/jruby/1.9/gems/log-courier-1.8.1/lib/log-courier/server.rb:65:in `initialize'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-courier-1.8.1/lib/logstash/inputs/courier.rb:96:in `register'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:149:in `start_inputs'
org/jruby/RubyArray.java:1613:in `each'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:148:in `start_inputs'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:81:in `run'
org/jruby/ext/thread/Mutex.java:149:in `synchronize'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:81:in `run'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/agent.rb:155:in `execute'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/runner.rb:91:in `run'
org/jruby/RubyProc.java:271:in `call'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/runner.rb:96:in `run'
org/jruby/RubyProc.java:271:in `call'
/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/task.rb:12:in `initialize'

Thanks

**Comment by ramreddy26** [comment]
Issue seems to be due to old version of Java ...It's working now with logstash 1.4.2. But I am still getting the error while using logstash 1.5.3 version with Java 1.8 version.

**Comment by driskell** [comment]
What's your config?

**Comment by ramreddy26** [comment]
input {
        courier {
                port => 6379
                ssl_certificate => "/opt/logstash/ssl/selfsigned.crt"
                ssl_key => "/opt/logstash/ssl/selfsigned.key"
        }
}

filter {

#Dropping all headings
        if [message] =~ "^#" {drop {}}

 #RabbitMQlog
                if [type] == "RabbitMQ" {
                        if [message] =~ "^\n" {drop {}}

                        multiline {
                                pattern => "^="
                                what => "previous"
                                negate => true
                        }

                        mutate {
                                gsub => [ "message", "\n", "" ]
                        }

                        grok {
                                match => [
										"message", "(?m)=(?<Level>(.*?))==== (?<log_timestamp>%{MONTHDAY}-%{MONTH}-%{YEAR}::%{HOUR}:%{MINUTE}:%{SECOND}) ===(%{GREEDYDATA:RMQ_Connection}): %{WORD:RMQ_Role} \<(?<RMQ_Observer>(.*?))\> saw deaths of mirrors \<(?<RMQ_Target>(.*?))\>",
                                        "message", "(?m)=(?<Level>(.*?))==== (?<log_timestamp>%{MONTHDAY}-%{MONTH}-%{YEAR}::%{HOUR}:%{MINUTE}:%{SECOND}) ===(%{GREEDYDATA:RMQ_message})<(%{GREEDYDATA:RMQ_node})> \((?<Server_IP>(.*?)):(?<Server_Port>(.*?)) -> (?<Client_IP>(.*?)):(?<Client_Port>(.*?))\):(%{GREEDYDATA:RMQ_error})",
                                        "message", "(?m)=(?<Level>(.*?))==== (?<log_timestamp>%{MONTHDAY}-%{MONTH}-%{YEAR}::%{HOUR}:%{MINUTE}:%{SECOND}) ===(%{GREEDYDATA:RMQ_message})<(%{GREEDYDATA:RMQ_node})> \((?<Server_IP>(.*?)):(?<Server_Port>(.*?)) -> (?<Client_IP>(.*?)):(?<Client_Port>(.*?))\)",
                                        "message", "(?m)=(?<Level>(.*?))==== (?<log_timestamp>%{MONTHDAY}-%{MONTH}-%{YEAR}::%{HOUR}:%{MINUTE}:%{SECOND}) ===(%{GREEDYDATA:RMQ_Connection}) <(%{GREEDYDATA:RMQ_node})> \((?<RMQError_State>(.*?))\), (?<RSM_Channel>(.*?)) - (?<RMQError_WriteLevel>(.*?)):{(?<RMQError_Type>(.*?)),(?<RMQError_Source>(.*?)),(?<RMQError_Type>(.*?)),(?<RMQError_DeliveryTag>(.*?))}",
                                        "message", "(?m)=(?<Level>(.*?))==== (?<log_timestamp>%{MONTHDAY}-%{MONTH}-%{YEAR}::%{HOUR}:%{MINUTE}:%{SECOND}) ===(%{GREEDYDATA:RMQ_Connection}) <(%{GREEDYDATA:RMQ_node})>, (?<RSM_Channel>(.*?)) - (?<RMQError_WriteLevel>(.*?)):{(?<RMQError_Type>(.*?)),(?<RMQError_Source>(.*?)),(?<RMQError_Type>(.*?)),(?<RMQError_DeliveryTag>(.*?))}",
                                        "message", "(?m)=(?<Level>(.*?))==== (?<log_timestamp>%{MONTHDAY}-%{MONTH}-%{YEAR}::%{HOUR}:%{MINUTE}:%{SECOND}) ===(%{GREEDYDATA:RMQ_message})<(%{GREEDYDATA:RMQ_node})> \((?<Server_IP>(.*?)):(?<Server_Port>(.*?)) -> (?<Client_IP>(.*?)):(?<Client_Port>(.*?))\):(%{GREEDYDATA:RMQ_error})",
                                        "message", "(?m)=(?<Level>(.*?))==== (?<log_timestamp>%{MONTHDAY}-%{MONTH}-%{YEAR}::%{HOUR}:%{MINUTE}:%{SECOND}) ===(%{GREEDYDATA:RMQ_message})<(%{GREEDYDATA:RMQ_node})> \((?<Server_IP>(.*?)):(?<Server_Port>(.*?)) -> (?<Client_IP>(.*?)):(?<Client_Port>(.*?))\)",
										"message", "(?m)=(?<Level>(.*?))==== (?<log_timestamp>%{MONTHDAY}-%{MONTH}-%{YEAR}::%{HOUR}:%{MINUTE}:%{SECOND}) ===(?<RMQ_message>(.*?)):%{GREEDYDATA:RMQ_error}"
                                ]
                                add_tag => "RabbitMQ"
                        }

                        if [RMQ_message] =~ "closing AMQP connection" {drop {}}
                        if [RMQ_message] =~ "accepting AMQP connection" {drop {}}

                        date {
                                match => [ "log_timestamp", "dd-MMM-YYY::HH:mm:ss" ]
                                timezone => "Etc/UCT"
                        }
                        mutate {
                                remove_tag => ["multiline"]
                        }
                }
}
output {
        elasticsearch {
                host => "localhost"
        }
}

**Comment by driskell** [comment]
Not sure if Logstash is compatible fully with Java 1.8 - but looking it up it seems that Jruby-OpenSSL is throwing an exception but "losing" the actual message. So it could be related to something wrong with the certificates.

But if it's only having issues with Logstash 1.5.3 it could be related to the OpenSSL security improvements they patched into Logstash 1.5.3 which fixes the cipher exchanges to a known-good set rather than the defaults.

If you can detail your OS and exact Java setup (OpenJDK? Oracle? RPM? Apt-get?) maybe I can look into it later - but I doubt I'd be able to fix it. We could also wait for 1.5.4 which tweaks the OpenSSL setup a bit and maybe that will resolve it.

**Comment by driskell** [comment]
Have you been able to try Logstash 1.5.4?

**Comment by ph** [comment]
Just stepping in a bit, we are recommending java 8 for the few latest releases of logstash.
The cyphers in 1.5.3 were OK, but we were forcing the `VERIFY_PEER`  check on the client, which was causing in the majority of the cases a TLS negotiation errors. 

I am looking at a similar issue on the lumberjack input itself that may be related to yours. (as pointed by @driskell) You said it used to work fine for some time than it stopped, did you upgrade you java version at the same time? If so which java / os are you running?

**Comment by ramreddy26** [comment]
@driskell I haven't upgraded it to 1.5.4 yet, I will try it during weekend.

@ph I did not upgrade my java at same time, for some reason it stopped working suddenly.
Right now I am using java 1.8.0_45 for logstash 1.4.2 and OS is Red Hat Enterprise Linux Server release 6.7 (Santiago).

**Comment by BenGatewood** [comment]
I'm seeing this same error. Just started happening on a previously perfectly fine installation. I've tried different combinations of Logstash version and Java version with no change. Anything else I can provide to help?

**Comment by driskell** [comment]
Hi @BenGatewood - can you outline your versions (Logstash / Log Courier / Courier Input Plugin), and also provide a copy paste of the error as well?

**Comment by driskell** [comment]
Key is the Java version and Logstash version.

**Comment by BenGatewood** [comment]
Java:

openjdk version "1.8.0_51"
OpenJDK Runtime Environment (build 1.8.0_51-b16)
OpenJDK 64-Bit Server VM (build 25.51-b03, mixed mode)

Logstash: 1.5.4
Log-courier: 1.8

Error:

The error reported is:
  input/courier: Failed to initialise: No message available

**Comment by driskell** [comment]
Hi @BenGatewood
Sorry for the lack of response. I did struggle to reproduce this.
If you experience this issue in newer Logstash (it's now 2.x) let me know in a new issue. I will close this for now.
