### ISSUE TITLE
Multiline Pattern Regex Issues

### ISSUE THREAD

**Issue by MichaelLiZhou** [driskell/log-courier#226]
Why doesn't the \s work in pattern matching? Neither does \[? 
It says these are invalid characters:

Configuration error: invalid character 's' in string escape code on line 18
        "pattern": "^([0-9]{8}\s+[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}\[INFO\s\]-Inbound Message)",
                               ^

Trying to match this:
20150825 11:39:28.780[INFO ]-Inbound Message

This statement works on logstash. The syntax guide provided by google is really no help and confusing.

**Comment by MichaelLiZhou** [comment]
just in \\[ and \\] simple issue fixed. But still really google syntax has bad documentation

**Comment by driskell** [comment]
The config file is JSON so backslash in a regex string need to be doubled. JSON decoding takes a backslash away so we need one left behind for regex still so \ \ s needed.

Logstash tries to be smart by not eating up backlash in its unique-to-logstash config format. It's likely a debatable subject but I find the logstash method inconsistent and it makes escaping quotes difficult. Though admittedly it makes for easier reading of regex strings!

**Comment by driskell** [comment]
Glad you had it sorted and I can see a need to make this clear in our documentation since I'm sure a lot of users will be pulling their multiline regex from logstash!
