### ISSUE TITLE
Too many open files at startup - old static files should be skipped not resumed

### ISSUE THREAD

**Issue by arep** [driskell/log-courier#229]
version 1.8.1

When I start log-courier I get error of "Too many open files". I know I have alot of log files, but most of them are old files and won't get any new updates. I think it's trying to do a "Resuming harvester on a previously harvested file" ... but then it's too many files.

If I remove these log files from the config I can then start log-courier. After that I can add them to the config again and issue a "reload". It then skips the files with "Skipping file (older than dead time of 24h0m0s)". So I'm happy.

It would be nice if log-courier could skip these files on normal startup as well even if it has harvested them previously.

**Comment by driskell** [comment]
Yes, definitely it should be skipping unless the file was recreated or the file size changed. Initial look it's not a simple fix but definitely doable. I'll see if I can get this fixed for the next version.

**Comment by amodakvnera** [comment]
Do we have any patch available to fix this?

**Comment by driskell** [comment]
This was fixed as part of fixing #242 (which is duplicate)
