### ISSUE TITLE
How to re-process log files?

### ISSUE THREAD

**Issue by jacobweber** [driskell/log-courier#230]
Is there a way to tell log-courier to re-process log files that it's already processed? I know with logstash-forwarder we can delete the sincedb files, but I'm not sure how to do this with log-courier.

(Sorry this is more of a question than an issue.)

**Comment by padusumilli** [comment]
You can delete ```.log-courier``` file. 

See [persist-directory](https://github.com/driskell/log-courier/blob/stable/docs/Configuration.md#persist-directory) for more info on the location of the offset file.

On CentOS 6 if installed using the provided rpm, the offset file is at ```/var/lib/log-courier``` directory

**Comment by jacobweber** [comment]
Thanks.
