### ISSUE TITLE
Link to CentOS/RedHat 7.x repo is broken

### ISSUE THREAD

**Issue by kbrown** [driskell/log-courier#231]
broken:
https://copr.fedoraproject.org/coprs/driskell/log-courier/repo/epel-6/driskell-log-courier-epel-7.repo
correct:
https://copr.fedoraproject.org/coprs/driskell/log-courier/repo/epel-7/driskell-log-courier-epel-7.repo

**Comment by driskell** [comment]
Fixed after merge of PR #232 thanks!
