### ISSUE TITLE
Publish binary releases

### ISSUE THREAD

**Issue by mkuzmin** [driskell/log-courier#234]
Right now I have to compile Windows binaries myself.
Also, using Linux version inside Docker containers, I have to base my Docker images on Ubuntu. It makes resulted images much larger, and longer to download.

It would be nice, if you compile and publish official binaries right on GitHub Releases page.
[Gox](https://github.com/mitchellh/gox) cross-compiler makes this task easier.

**Comment by driskell** [comment]
What platform are you needing to install on?
I've concentrated mainly on packaging for RHEL and Ubuntu.
Windows is more a limited area at the moment (the build is complex on Windows itself) but yes cross compiling likely works better than the current steps. Ideally it needs an installer though.

I'd rather publish packages than binaries as they are better maintainable. Publishing binaries feel like giving out IKEA furniture. Though I guess the argument is that stuff is actually quite popular though!

**Comment by mkuzmin** [comment]
1) Linux Docker containers. 
Due to Ubuntu dependencies, [my current image](https://hub.docker.com/r/mkuzmin/log-courier) weighs 200 Mb. Having a standalone log-courier binary, I would base a Docker image it on `easybox` or `alpine`, and cut it to 10 Mb.

2) Windows.
I have no problems to compile binaries myself. But I'd like to escape a routine to build, host, and update custom releases, if possible.

**Comment by mkuzmin** [comment]
Indeed, packages are better than raw binaries. If such packages exist.
It would be great if you provide official Docker image, but until then deb-package adds more issues than convenience.

Windows is another story. Windows installers are too heavy, and if installation is automated by tools like PowerShell DSC, installers make the procedure less reliable.

**Comment by driskell** [comment]
Understood. As part of cleaning up any Windows build I'll definitely consider cross-compiling and attaching binaries to the GitHub releases. I can't really commit at this stage but I can see it will be of great benefit to do so!
