### ISSUE TITLE
Transport error, will try again: EOF

### ISSUE THREAD

**Issue by trikosuave** [driskell/log-courier#236]
I am using log-courier 1.8.1 with transport TLS to logstash 1.4.5. 

I was also getting the following errors with lc1.3/ls1.4.1 as well and was hoping the upgrade would fix it.

Log-courier:
2015/09/25 12:07:29.158339 Transport error, will try again: EOF
2015/09/25 12:07:30.158659 Attempting to connect to xx.xx.xx.xx:50100 (xxxxx.com)
2015/09/25 12:07:30.524547 Connected to xx.xx.xx.xx:50100 (xxxxx.com)
2015/09/25 12:07:30.524592 Send now open: Awaiting events for new payload

logstash:
{:timestamp=>"2015-09-25T19:11:40.109000+0000", :message=>"Connection aborted", :error=>"Connection reset by peer", :peer=>"xx.xx.xx.xx:17386", :level=>:warn}

The IP addresses on the logstash.log side are always one of the 3 ELBs in the multi AZ setup. (AWS).
We have ELK setup in an ASG. We are using TLS with the proper certs/keys in place. Logs still seem to be coming through, but only after it retries. 

Also, logstash would eventually crash with log-courier having a null pointer or out of memory error after a couple of hours. I am hoping that it unrelated and fixed by the upgrade from 1.3 to 1.8.1

**Comment by trikosuave** [comment]
Actually, is this normal behavior? Is it initializing a connection to logstash, then waiting for logs, but there are none, so it times out and closes the connections and then reopens?
Is there a way to have it only open the connection where there is something to do?

**Comment by driskell** [comment]
Connections should remain open. It sends a periodic ping. I think the TCP mode on AWS ELB has connection time limits and possibly this is the cause of it only happens after a while.

If you get crashes in log courier though I need the stack trace to fix it if you can get it.

**Comment by driskell** [comment]
Have you encountered any further issues? If using ELB I would say this is expected as the ELB will likely close the connection after some time, and eventually once Log Courier realises it will get an EOF error and reconnect, but no impact on logs.

The upgrade may have fixed the null pointer problem but if you do see it please drop the stack trace and I'll get it fixed. I can't see anything related in the change logs but it still may be fixed. I've not seen anything like this at all with the latest versions, it's tended to be extremely stable.
