### ISSUE TITLE
Corresponding request and response files are not getting read

### ISSUE THREAD

**Issue by Rajeshkumar123** [driskell/log-courier#237]
Hi,

I have xml log files(request and response). I am doing correlation from request to response in logstash so for that logcourier should fetch the request files and process it first and then the corresponding response files. Actually some of the response files are getting read ahead of request files and subsquently correlation failed there. Is there any way to set the logcourier like response files should get read only after request files.
I am using logstash 1.5.2 and logcourier 1.6
Notes:  I am having split_xpath to process multiple same nodes in xml request files. Is there anything to do with request files getting executed delayed because of split_xpath?

Thanks

**Comment by driskell** [comment]
Hi @Rajeshkumar123 

I'm not sure what you want to achieve. It looks like you have two sets of files, and want one set to import before the other. This isn't really possible and would be very complex to implement (how would you tell Log Courier which to do first?)

I think the best action may be a script of some sort that combines the request and response together into a single file, and places it into a directory that Log Courier monitors. This will then ensure the lines are transmitted in order.

Jason
