### ISSUE TITLE
Feature request: have admin show percentage complete

### ISSUE THREAD

**Issue by jacobweber** [driskell/log-courier#239]
It would be very helpful if the admin tool showed the percentage of the file that's already been processed (e.g. the offset / size). This way you could get an idea of how much longer it will take to complete.

Maybe you could also add up the offsets and sizes for all files, and calculate the total percentage.

**Comment by sysmonk** [comment]
Are you parsing standalone files, or live logs? 
I don't really see any usefulness of this feature in live logs - logs are constantly written, and the percentage will never be correct. 

Just my 2 cents :)

**Comment by jacobweber** [comment]
I was thinking it would be useful when you need to parse existing files, starting from the beginning.

**Comment by driskell** [comment]
I have felt this same thing before. When Logstash has had a problem and everything has been put back online, I'd wanted to know how long before data becomes realtime again. So I do think it would be useful information. It would be especially useful in alerting too as backlogs like this prevent log files from being deleted so its a good advance warning of issues such as if there's a comm problem and the rate of logs from a single instance is too slow for the build up.
