### ISSUE TITLE
Log Courier sending all but latest log entry.

### ISSUE THREAD

**Issue by trikosuave** [driskell/log-courier#240]
I set up a server to throw an error when I send a specific request to it. I can send an id in the request to track the logs in ELK.

If I send an id of 'error10' and send it 10 times, only the first 9 show in Kibana (making sure log-courier is in idle). If then I send an id of error5 5 times, I will get the 10th error of error10 and only the first 4 of error5. 
It seems to be holding on to the last error and sending it with the next batch. This is not good, since the last error will likely be the smoking gun.  

I have messed around with various spool sizes and spool timeouts, but have ran out of ideas. Is this a bug? (log-courier 1.8.1)

Thanks!

**Comment by driskell** [comment]
@trikosuave Does the line have a line ending in the file? I've only ever seen this where the app didn't log a new line until the following message.

**Comment by trikosuave** [comment]
Yes, there is a hex 0A (line feed) at the end of the last entry. We have tomcat with log4j aggregating our logs.

**Comment by driskell** [comment]
If you read the file from command line is the line there. Just to rule out buffering on the application side. Also if you then stop the application does it send?

Lastly, any filters or codecs that might buffer (like Multiline)?

**Comment by trikosuave** [comment]
Yes, if I cat the log file, it has a new line at the end. Also stopping the app does not send the log. (The logAggregator.log file is not updated on stop)
I am unaware of anything other than log4j touching these logs. 
Thanks for helping on this. I am out of ideas.

**Comment by driskell** [comment]
Any filters or codecs in use at Logstash side?

**Comment by trikosuave** [comment]
The only thing installed on top of the standard logstash installation (1.4.5) is logstash-contrib and the log-courier plugin (via the gem - 1.8.1).

**Comment by trikosuave** [comment]
I have also verified that elasticsearch does not have the latest log (confirming log-courier is not sending it). 
For my test, I caused a "test6" error 6 times. The appserver has 6 "test6" log entries, log-courier is sitting idle after sending what it had, and kibana/elasticsearch is only showing 5 "test6" entries.

**Comment by trikosuave** [comment]
We do have this in logstash conf:
```
filter {
  if [type] =~ /-tomcat$/ {
    multiline {
      pattern => "^%{TOMCAT_DATESTAMP}"
      negate => true
      what => "previous"
    }
    grok {
      match => [ "message", "(?m)%{TOMCAT_DATESTAMP:raw_timestamp} %{LOGLEVEL:level} %{JAVAFILE:class_name}(:%{NUMBER:line_number})? - %{JAVALOGMESSAGE:log_message}" ]
    }
    date {
      match => [ "raw_timestamp", "YYYY-MM-dd HH:mm:ss" ]
    }
  }
...
}

**Comment by trikosuave** [comment]
Just found this: 
'''
A side effect of using "previous" is that an event will not be flushed until the first line of the next event is encountered. The "previous timeout" option offers a solution to this.
'''
Trying now. Will close issue, if it works. Thanks again!

**Comment by trikosuave** [comment]
I have multiline on the logstash input side. I do not have any codecs on the log-courier side. Should I do it on the log-courier side?  or both?

**Comment by driskell** [comment]
You can use multiline on the logstash side, but only the filter. You should never use the codec. It doesn't really matter which side you use it at. But it is true when using multiline "previous" in Logstash it won't send the last line onto the outputs.

Essentially, when it hits the match, it says "this event belongs to previous event". And it won't send anything until it receives an event that doesn't match. So it's always a line behind when using "previous".
If you use the Log Courier multiline codec you can use "previous timeout" (not sure if the Logstash side implements similar yet but I think it does...) which will only hold a line for a period of time, since you'd always expect multiline events to flush together to the file at roughly the same time. The alternative is to the rewrite the query to use "next" - which is never behind (its always ahead).

**Comment by trikosuave** [comment]
Upgrading to logstash 1.5 fixes the issue with what=>"previous" on the logstash multiline filter, instead of using log-courier multiline codec. Thanks again for your help.
