### ISSUE TITLE
Log courier excessive memory usage under Windows

### ISSUE THREAD

**Issue by martinivanov** [driskell/log-courier#242]
Hi,

I'm experiencing excessive memory usage with log courier under Windows. It may be related to the way my logger works - it logs in separate file per log (e.g. per class) and per hour. This results in ~30-40 different files per hour. If I start with an empty log directory, the memory consumption is low, but if I start log courier on already populated directory, it starts up with ~200-300 MB of memory and doesn't drop.

OS is Windows Server 2012
LogCourier version 1.8.1 built with Go 1.5

Configuration used:
```json
{
  "network": {
	"transport": "tcp",
    "servers": [ "logstash-server" ],
    "timeout": 15
  },
  "files": [
    {
      "paths": [
		"C:/Windows/Temp/Logs/*/*.json.log", 
		"C:/Windows/Temp/Logs/*/*/*.json.log", 
		"C:/Windows/Temp/Logs/*/*/*/*.json.log"],
      "fields": { "type": "json" },
	  "dead time": "10m"
    }
  ]
}
```

**Comment by driskell** [comment]
Hi @martinivanov 

How are you measuring the memory? Go is known for allocating extremely large regions of virtual memory. However, because this memory is virtual and not allocated or mapped, the corresponding physical usage is much much smaller. It may be you are seeing the virtual region - but this does not correlate to physical memory at all.

Jason

**Comment by martinivanov** [comment]
Hey,

Thanks for the quick reply :)

Memory was measured with process explorer and it was actually used, because several applications started to complain that they are running out of memory.

I will try to collect more information and provide it later.

**Comment by martinivanov** [comment]
I did some testing, and indeed, if log courier is restarted and there are old files left its memory usage explodes.

**Comment by driskell** [comment]
> I did some testing, and indeed, if log courier is restarted and there are old files left its memory usage explodes.
I don't understand what you mean. Can you explain in some more detail?

**Comment by driskell** [comment]
Additionally, when you "measured with process explorer", which memory metric did you use? Process Explorer exposes several different memory values, which one you are reading is important.

**Comment by martinivanov** [comment]
1. By "old files" I mean files that are not being written anymore and log courier already processed. Deleting them seems to fix the issue.
2. I'm looking at the private bytes column.

Thanks

**Comment by driskell** [comment]
Aha. How many old files are there?

Each file will use around 16KB of memory for the read buffer, and some little more for other bits so lets say 32KB. So if there are 1000 old files, this could be 32MB.

Usually any file older than `"dead time"` configuration will not be touched though, only watched, and not use any additional memory (except for the tracking, which is tiny.) I will check if there's something extra can be done though.

**Comment by driskell** [comment]
OK I can see one improvement. Looks like we resume all files regardless of age on startup. That's somewhere I can optimise which should reduce memory usage on restart. This memory will release once `"dead time"` reached (which could be in mere seconds once it realises it's an old file) but ideally shouldn't have even been used to start with.

Reducing `"dead time"` so the number of open files is kept low will help reduce running memory usage though.
