### ISSUE TITLE
Adding log file ctime/mtime in a field to support date-less timestamps

### ISSUE THREAD

**Issue by nixar** [driskell/log-courier#244]
I have to ship crappy files with only time information, not a full timestamp. When I extract the date with logstash's date filter, my logs end up smoking weed and protesting Vietnam:

```ruby
{
    "@timestamp" => "1970-01-01T15:59:38.824Z",
       "message" => "15:59:38,824 INFO  [ServerInfo] Java version: 1.6.0_45,Sun Microsystems Inc.",
      "@version" => "1",
          "host" => "xxx.virtualbox",
          "time" => "15:59:38,824",
      "loglevel" => "INFO",
     "javaclass" => "ServerInfo"
}
```

One possible solution could be to reconstruct the date from the file creation time, and/or possibly modification time (in case I want to re-ship old logs). That would require having the information. Adding a function to add this in a field would allow this.

**Comment by driskell** [comment]
Logstash already adds it on receive (though admittedly it may be better on read in case of connectivity, but in that event reading can stop while it waits). Maybe make the date filter in a conditional so the receive timestamp is left alone?

For reshipping that's not ideal but I'll have a think on that - with ctime/mtime it's a single timestamp for nearly all the lines in that case and I wouldn't want to confuse multiple sources in the same field. It also seems something only relevant to reshipping. Maybe it's best as a one-off field added manually or something like that.

**Comment by driskell** [comment]
(Added roadmap then realised Logstash adds missing timestamp on receive)

**Comment by driskell** [comment]
Will close as it's a fairly specific issue, but can reopen if its needs attention.
