### ISSUE TITLE
logstash 2.0 beta / rc plugin installation issues

### ISSUE THREAD

**Issue by sysmonk** [driskell/log-courier#245]
Hi,

I'm trying to use logstash 2.0-rc1 with log-courier, but the input plugin fails to install:

```
# /home/logstash/bin/plugin install logstash-input-log-courier
Validating logstash-input-log-courier
Installing logstash-input-log-courier
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 2.0.0.rc1)

  In Gemfile:
    logstash-output-http (>= 0) java depends on
      logstash-mixin-http_client (< 3.0.0, >= 2.0.2) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-output-http (>= 0) java depends on
      logstash-mixin-http_client (< 3.0.0, >= 2.0.2) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

# same 3 lines go on for quite a lot of times ....

   logstash-output-http (>= 0) java depends on
      logstash-mixin-http_client (< 3.0.0, >= 2.0.2) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-input-log-courier (>= 0) java depends on
      logstash-core (~> 1.4) java

    logstash-core (= 2.0.0.rc1) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "logstash":
  In Gemfile:
    logstash-input-log-courier (>= 0) java depends on
      logstash (~> 1.4) java
Could not find gem 'logstash (~> 1.4) java', which is required by gem 'logstash-input-log-courier (>= 0) java', in any of the sources.
```

It's a fresh logstash 2.0-rc1 install on a fresh system.

**Comment by driskell** [comment]
I haven't added support for v2.0-rc1 yet, and I've not yet looked at what would need to be done.
Also - there's the potential that when updating to support 2.0, support for 1.0 is lost, so there's that to consider too.

I'll look into this soon as 2.0 looks just around the corner now.

**Comment by sysmonk** [comment]
Yesterday 2.0 got released:

https://www.elastic.co/blog/logstash-2-0-0-released

Waiting for the plugin  update!

**Comment by sysmonk** [comment]
Also, not really familiar with rubygems stuff, isn't there possible to have multiple versions of the plugin ( "branches" )? Sounds kinda bad if you can't and want to support multiple versions :(

**Comment by Scratch-net** [comment]
Updated to logstash 2.0 today and also faced the log courier installation problem. Waiting for the fix

**Comment by JamesBromberger** [comment]
+1

**Comment by driskell** [comment]
Looks like there are plans to make Logstash pick the latest *compatible* version, which means if I drop in a 1.9 courier gem that works with say, Logstash 3, then Logstash 2 will ignore it. Funny thing is I think Logstash 1.5 isn't going to get that fix :)

I'm doing some testing to see if the plugin as is works fine in Logstash 2. If that's the case, I'll simply raise the Logstash version constraint to include version 2 as well as 1.5

**Comment by Scratch-net** [comment]
Sounds like a plan ) Fingers crossed

**Comment by driskell** [comment]
I've pushed 1.8.2 which I've tested and works fine. Let me know if not.
Looks like the only change was relating to shutdown, and I fixed that, and events flowed as normal and shutdown was fast and clean.

**Comment by Scratch-net** [comment]
@driskell Works like a charm, thanks!
