### ISSUE TITLE
LOG_COURIER_ARGS in rhel7 rpm sysconfig file not working out of the box

### ISSUE THREAD

**Issue by travisgroth** [driskell/log-courier#248]
Hi,

I've been trying out a test config with log-courier on a centos7 machine and something seems off with the default sysconfig file and how log-courier is starting via systemd. 

As-shipped, with a valid config in /etc/log-courier/log-courier.conf, systemd cannot start log-courier.  I think systemd is implicitly turning the entire LOG_COURIER_ARGS variable into a single argument when parsing the Exec* options.  On startup I get this:
>log-courier[9482]: flag provided but not defined: -config /etc/log-courier/log-courier.
>log-courier[9482]: Usage of /usr/sbin/log-courier:
>log-courier[9482]: -config="": The config file to load
>log-courier[9482]: -config-test=false: Test the configuration specified by -config and 
>log-courier[9482]: -cpuprofile="": write cpu profile to file
>log-courier[9482]: -from-beginning=false: On first run, read new files from the 
>log-courier[9482]: -list-supported=false: List supported transports and codecs
>log-courier[9482]: -stdin=false: Read from stdin instead of files listed in the config 
>log-courier[9482]: -version=false: show version information>

If I change the sysconfig file to this, it starts correctly:
>LOG_COURIER_ARGS='-config=/etc/log-courier/log-courier.conf'

I'm not very familiar with systemd so I'm just making an educated guess on what it is doing internally.  I can reproduce this error on the command line by doing this:

>$ log-courier '-config /etc/log-courier/log-courier.conf'
>flag provided but not defined: -config /etc/log-courier/log-courier.conf
>Usage of log-courier:
>  -config="": The config file to load
>  -config-test=false: Test the configuration specified by -config and exit
>  -cpuprofile="": write cpu profile to file
>  -from-beginning=false: On first run, read new files from the beginning instead of the end
>  -list-supported=false: List supported transports and codecs
>  -stdin=false: Read from stdin instead of files listed in the config file
>  -version=false: show version information

I'm not sure if there's a way to have the variable interpolation work more intuitively for this use case but the simple fix is to switch to option= syntax in the default sysconfig file.  Obviously that only works for a single option in the file so maybe there's a way to tell systemd to behave differently.

Let me know if you need more info.

**Comment by travisgroth** [comment]
Actually, I just noticed the problem.  The systemd unit file is referencing the LOG_COURIER_ARGS variable with curly braces so its being handled as a single argument.  Changing to $LOG_COURIER_ARGS in the Exec options results in expected behavior.

**Comment by driskell** [comment]
Thanks!

Clearly I tried to be smart and used Bash syntax in a Systemd context, forgetting the obvious knowledge Systemd wrote their own shell expansion code, as you do. 😂

Sorry about that and thanks for taking the time to fix!

**Comment by travisgroth** [comment]
Hah yes that was fun to figure out.  No problem.  Thanks for the fast merge.  Do you have a rough ETA on when you'll be cutting a new RPM?  I'm about to roll out log-courier in the next week or so and would rather not have to either build my own release or manage a drop-in override.  Thanks!
