### ISSUE TITLE
Logstash 2 Support?

### ISSUE THREAD

**Issue by ninjada** [driskell/log-courier#254]
Just testing the latest round of updates to the ELK stack, with logstash 2.0. 

No luck so far post plugin install for logstash-input-courier. Still tinkering about but is log-courier expected to work with latest logstash 2.x?

**Comment by driskell** [comment]
> ...is log-courier expected to work with latest logstash 2.x?

Yes

> No luck so far post plugin install

I'll need more information in order to help. What is happening that isn't as you expect?

**Comment by Balanc3** [comment]
Is it possible to put 1.8.2. in the apt-get repository? If not, how can I update it easily? I don't really want to build it across my 100+ machines.

**Comment by driskell** [comment]
@Balanc3 What do you mean? The plugins don't come in packages and are installed via Logstash `bin/plugin` command.

**Comment by ninjada** [comment]
had a logstash issue, everything lookin good under v2!
