### ISSUE TITLE
RPM Package should not use root user by default

### ISSUE THREAD

**Issue by nazunalika** [driskell/log-courier#255]
Currently, the RPM version of log-courier does not use a non-root user to run. Another issue I had found talking about logstash noted that the logstash RPM does not run as root.

It would be ideal if log-courier ran as a non-root user. If there is a reason why it runs as root, please let me know. My environment does not allow processes/applications to run as root (for security reasons).

**Comment by driskell** [comment]
Running as root is for two reasons:
1. I run it as root so it can easily access all the logs I need to ship
2. Logstash forwarder used to run as root

So actually, not for any *good* reason.
I'm breaking lots of backwards compatibility with 2.0 and so maybe it's time there to change that. For sure I will make sure it is configurable in the environment file (`log-courier.sysconfig` etc.)

**Comment by nazunalika** [comment]
I see the reasoning now. I had noticed some devs where I work were creating a local account and running log-courier manually as that user.

Thanks for the heads up! I think others may find it useful too to have it run as a non-root user in the future.

**Comment by driskell** [comment]
Subsequent packages will now use log-courier as default now.
It can be changed in /etc/sysconfig/log-courier to keep it as root if needed
