### ISSUE TITLE
no RPM for new version 1.8.2

### ISSUE THREAD

**Issue by abarbieri** [driskell/log-courier#259]
last build available for EL7 is log-courier-1.8-1.el7.centos.x86_64 dated Thu 06 Aug 2015 10:01:56 AM EDT.

**Comment by driskell** [comment]
Please see: https://github.com/driskell/log-courier/issues/256

1.8.2 was plugin changes only. The latest version of Log Courier is 1.8.0.
https://github.com/driskell/log-courier/blob/master/docs/ChangeLog.md shows "No Changes" for Log Courier.
I know this is confusing and I'm working on resolving it by splitting the plugins out into their own repositories (which is completed) and I just need to clean up the Log Courier repository.

**Comment by abarbieri** [comment]
OK, thanks!

so to fix "LogStash::Json::GeneratorError: Failed to load class 'org.jruby.RubyObject$Access4JacksonDeserializer4a901575': com.fasterxml.jackson.module.afterburner.ser.BeanPropertyAccessor" when using Logstash 1.5.5 I need to use logstash-input-courier v1.8.2 which is not available yet with the traditional plugin install process?

**Comment by driskell** [comment]
You need to use logstash-input-courier 1.9.0

This is available now.

You can remove and install the plugin again.
