### ISSUE TITLE
It would be great if there were more example log-courier configurations.

### ISSUE THREAD

**Issue by shurane** [driskell/log-courier#26]
https://github.com/driskell/log-courier/blob/develop/docs/Configuration.md is awesome documentation, but I would love to see some example configurations, much in the line of all the examples for @coolacid's https://github.com/coolacid/GettingStartedWithELK repo.

It's probably worth mentioning if `log-courier` is backwards compatible with `logstash-forwarder` configs as well.

I'm drawing inspiration for a well detailed config mainly from this ansible [playbook.yml](https://gist.github.com/phred/2897937) and this [elasticsearch.yml](https://github.com/elasticsearch/elasticsearch/blob/master/config/elasticsearch.yml).

**Comment by PMDubuc** [comment]
The list of examples doesn't show the use of the "general" section.  How to enable administration and change the default admin listen address for example.

**Comment by WishCow** [comment]
The link is now a 404

**Comment by driskell** [comment]
Whoops. Yes it is.

See here for the files:
https://github.com/driskell/log-courier/tree/master/docs/examples

I'll create issue to update docs

**Comment by ruddj** [comment]
To check, all examples are yaml now? There are no json examples?

**Comment by driskell** [comment]
I've fixed the 404 and was meant to add a new JSON example but didn't commit it 😩

I'll push up the JSON example tonight or tomorrow. There's an in-page example though in the configuration docs where I try to describe the config formats. Hope it helps.

**Comment by driskell** [comment]
Added a JSON example now. I'll get some more detailed ones added in the future with everything in them and lots of comments.
