### ISSUE TITLE
log-courier keeps files open when logstash-server unreachable

### ISSUE THREAD

**Issue by dixitk13** [driskell/log-courier#261]
with ref to https://github.com/driskell/log-courier/issues/152 what can I do when the logstash-server is unreachable and log-courier holds on to the files leading to disk space filling up? Ideally I would want log-courier to stop holding on to files after a certain period in case of logstash-server unavailability.

I tried the following "dead time" at the files level, but lsof shows files marked as deleted but kept open by log-courier.

```
  "files":[
    {
      "paths": [
        "/xxx/xxx/*.xxx.log"
      ],
      "dead time":"1h",
      "fields": { "type": "xxx", "xxx":"xxx" },
       "codec": {
            "name": "multiline",
            "pattern" : "xxxx",
            "negate" : true,
            "what" : "previous",
            "previous timeout": "30s"
          }
    }
  ]
```

```
root@xxx|/>lsof | grep deleted
log-couri 22777      root    6r      REG              253,0  146008850    3145953 /xxx/xxx/log/hist/112315/xxx.log (deleted)
log-couri 22777      root    7r      REG              253,0  174444874    3149952 /xxx/xxx/log/hist/112315/xxx.log (deleted)
log-couri 22777      root    8u      REG              253,0  177215663    3146712 /xxx/xxx/log/hist/112315/xxx.log (deleted)

```

**Comment by dixitk13** [comment]
@driskell Jason?

**Comment by driskell** [comment]
Hello

Currently only way is to restart or try keep the Logstash side running.

In that ticket I spoke of a configure to only hold deleted files for so long. Does that seem acceptable? The problem is also going to include instances where processing is too slow and logs are added faster than processed. So I wonder if this not sufficient.

Another idea I had was to monitor disk space when a file is deleted and if it's over a set watermark, close the file.

Any other ideas?

**Comment by driskell** [comment]
I guess the max time for closed files could apply regardless if sending slowly or not. Most systems gonna have multiple rotations and if still sending oldest one I guess it's certain there's problems. As long as it logs an error.

**Comment by dixitk13** [comment]
I believe if you let someone set a certain time to hold deleted files for so long (delete hold max) - servers the purpose. So having the capability of keeping two settings: 
1. "delete hold max" - hold the deleted files for so long and spit to logs in case time exceeds and shipping doesn't finish, just for closed files. If not specified it functions the way it does right now - not worrying about speeds or one time delivery. So a "delete hold max" comes with a warning for the person who uses this and the losses go into his bucket :-)
2. "dead time" - does what it does today.

For the idea of monitoring disk space utilized when deleted - I think it wouldn't work, cause there maybe be peak times when the application logging these logs has a very high volume and could lead  to a false disk space alert - leading to more losses in closed files.

thoughts?

**Comment by driskell** [comment]
I agree, "delete hold max" makes sense. I hope to get some things done soon I'm just so busy at the moment.

**Comment by Inderjeet26** [comment]
Hello, What happens when the Logstash comes back up and the Log Courier which is still holding onto the log files. Does the Log Courier send those old logs now in the already rotated opened log files?
