### ISSUE TITLE
log-courier skipping files, even if its a new file with new i-node number

### ISSUE THREAD

**Issue by amodakvnera** [driskell/log-courier#262]
Hello,
I have rsync sending logs to centrally located server. And the log-courier is installed on central server.

Using rsync I want to retain the log file timestamp between source and destination. This is required for auditing. And I have set the "dead time" as 5 min, as I don't want to keep the file opened for too long due to heavy load on central server.

Now, even if it is a new file with new i-node number on the central server, the log-courier is skipping the file, as the file has older timestamp than 5 min.

Any idea how to get around this?

Thanks.

**Comment by driskell** [comment]
Only way is to increase the dead time. Log courier is designed to be the spoke and not the axle - could you install it on the end servers?

**Comment by driskell** [comment]
Will close this as it's not really the intended way to use Log Courier. If you do have any other suggestions though that might help make this work better we can look at them. Though I think dead time is the way to go, and at the same time ensuring that the time between a log last updating and getting rsync across is less than the configured dead time, then I think things should work as expected.
