### ISSUE TITLE
Allow multiple multiline codec sections

### ISSUE THREAD

**Issue by konstantinkoschke** [driskell/log-courier#263]
Hi,

thank you for excellent work.

I am very happy about the possibility of using multiline on the shipper's side. 
However, the current implementation only obeys the last codec-multiline section. Something like the following would hence not work:

    "files": [
        {
            "paths": [
                "loggylogfiles.log"
            ],
            "fields": { "type": "loggy" },
            "codec": {
              "name": "multiline",
              "pattern": "<pattern that always matches except for exceptions>",
              "negate": true,
              "what": "previous"
            },
            "codec": {
              "name": "multiline",
             "pattern": "<pattern that matches 'additional information' statements which should be grouped with the previous real statement>",
              "what": "previous"
            }
        ...

Allowing mutliple codec sections would help a lot.

Cheers
konstantin

Edit: I guess it's related/a duplicate of https://github.com/driskell/log-courier/issues/257

**Comment by driskell** [comment]
I don't know how it would work to have multiple multiline blocks.
Do you mean multiple patterns?
Sorry for the delay in response.

**Comment by konstantinkoschke** [comment]
Multiple patterns would help, but doesn't solve all possible combinations, e.g.:
```
 ...
"pattern": "<pattern1>",
"negate":"true"
...
"pattern": "<pattern2>",
"negate":"false"
...
```
Cheers
konstantin

**Comment by driskell** [comment]
Do you mean multiple patterns but some negate and some not?

I'm open to changing API in v2 and maybe patterns could have multiple and if you want to negate one you prefix it with `!`

**Comment by driskell** [comment]
I've implemented in master allowing multiple patterns with different negates. This also now applies to the filter codec.
