### ISSUE TITLE
lc-admin status Question

### ISSUE THREAD

**Issue by gamename** [driskell/log-courier#264]
Hi,

Background: I have an aws instance which is only used for a short time as a database restoral box.  Once the restore completes, we take the box down.  But I want to make sure all logs are forwarded first.  

It appears the best way to do that is doing a 'lc-admin status' on the temporary instance.  Correct? It looks like waiting for "Pending Payload" to be 0 could be used to  indicate everything was forwarded and we can stop the system.

Make sense, or is there a better way to do this? 

Thanks,
-T

**Comment by driskell** [comment]
Hi gamename,

You'll be wanting to check the status of all files to make sure they are "Idle".
That status means the file has stopped updating and LC has *reached the end of the file*.
Finally, then you'll need to check Pending Payloads.

I don't think this is anywhere near perfect though, but it's the best I can come up with. It's potential that on a fast connection but slow IO you could have 0 pending payloads, idle files, but still have logs in the internal buffer (which flushes after 5 seconds if it doesn't get filled.) So there's slightly possibility of losing the last few.

Jason

**Comment by driskell** [comment]
#239 would make finding out if everything is shipped much easier too. So we can close this and if you need more accurate information, watch #239 as it will give it when implemented.
