### ISSUE TITLE
/home/arriva/in/ARREIN.E2012.txt reports_check fail

### ISSUE THREAD

**Issue by jbothma** [driskell/log-courier#265]
arriva integrates with addoro via our FTP

in sandbox it's jsut testing.

In prod they will probably pick it up before the reports_check will care.

It might be that the reports check needs to become a bit smarter to either not report on this or report more correctly (we don't expect a report for the .txt file - addoro needs to pick it up and make a kivra input file)

**Comment by driskell** [comment]
Did you post this in the right place?

**Comment by jbothma** [comment]
Nope. Thanks for checking. Is it possible to delete? :)

**Comment by driskell** [comment]
GitHub doesn't allow. But you should be able to Edit and just remove all content :)
