### ISSUE TITLE
Apache Spark Streaming integration

### ISSUE THREAD

**Issue by dkirrane** [driskell/log-courier#268]
Is there anyway to integrate Apache Spark Streaming to process the stream of log events sent from log-courier to Logstash?

**Comment by trixpan** [comment]
@dkirrane you should be able to achieve this using Apache NiFi or similar as intermediaries.

https://blogs.apache.org/nifi/entry/stream_processing_nifi_and_spark

I recently wrote an input (processor) to listen for logstash-forwarder and once I understand the log-courier protocol I plan to write one as well (unless someone writes it first).

**Comment by driskell** [comment]
Hey guys. Hopefully the description in #269 is sufficient. I'll eventually copy it and clean it up into a document for those that need it.
