### ISSUE TITLE
document the protocol

### ISSUE THREAD

**Issue by trixpan** [driskell/log-courier#269]
Hi,

I am considering writting a log-courier interface to Apache NiFi (lets call it ListenLogcourier) but couldn't find the protocol specification.

Would you have one by any chance?

**Comment by driskell** [comment]
I haven't documented the protocol yet! Apologies.

It's a 32-bit protocol at the moment. It is a stream of "messages" much like Logstash Forwarder was.
Each message is formed as follows:
* 4-byte identifier
* 4-byte data length
* Data of exact length given, no termination

There are several types of messages:
* PING, mandatory length 0. Servers should respond with a PONG, mandatory length 0. This is to keep ports open in stateful firewalls when the connection is idle. Connection should be aborted if any length is not 0.
* PONG, mandatory length 0. Sent by a client in response to a PING. Connection should be aborted if length is not 0.
* JDAT message. This stands for "JSON Data". The first 16 bytes of the data are a "nonce", and this is just a randomised set of bytes that should uniquely identify the event packet being transmitted. Minimum data length is 1 byte so this is always at least 17 bytes. The data itself is ZLIB compressed. The compressed data is a set of JSON events, each event is its own JSON object, and is preceded by 4-byte length. So you have length:json:length:json:length:json, compressed, and then prefixed with nonce.
* ACKN message. This is sent by the server to notify Log Courier of the status of the processing for a JDAT message that was received. It should aim to respond well within the network timeout, regardless of how far it processed. The courier Logstash plugin responds within 5 seconds always. The message data is formed of the 16-byte nonce of the JDAT message currently in progress, and a 4-byte number giving the number of events acknowledged, meaning Log Courier can discard them. So if zero events are processed yet, it sends 0. If 10 events processed, it sends 10. A client should ignore ACKN that goes backwards. It can also take a number larger than the number of events sent as "fully completed". So it is graceful. Acknowledged events should not be resubmitted. If connection is lost, the JDAT payload should be recalculated to not contain the acknowledged events and resubmitted.

A few notes:
JDAT messages can be send contiguously before any ACKN. It's a good way to fill buffers at both side of a connection to completely rule out latency when there's lots of logs to send.
Responses must be handled asynchronously. For example, Log Courier will allow a ACKN to be received before the JDAT has actually finished sending. This is important for speed of the connection. And important for reliability of the connection. If it's a big chunk of events on slow connection, it could take a minute to send it. Even so, it should timeout on network timeout if no ACKN received. So ACKN should be sent from the moment enough information is available. So once nonce is received (4+4+16), start sending ACKN with 0, once all data received, then you can start sending progress. Logstash courier plugin doesn't do this so big packets can timeout, but my alpha does this correctly. It's not mandatory though - it would just mean slow connections are unreliable if it doesn't.

Hope this is enough information. When things calm down for me I'm hoping to get alpha into beta and I should document this.

**Comment by trixpan** [comment]
@driskell 

Thanks for the description.

Regarding the JDAT message. Is it like Lumberjacks multiple 1D inside a 1C message or is it:

4 bytes messageType
4 bytes payloadLength (of compressed data)
x bytes of compressed data (where the decompressed data is 4 bytes contentLenght + content

and where compressed data *CANNOT* contain a nested frame?

Also, do JDAT messages contain more than one log line (when used as a tailf for syslog files)?

Cheers

**Comment by driskell** [comment]
JDAT cannot contain nested messages. It can contain multiple log events though, at least one. Each log event has a length prefix so you can work out where one ends and next starts.

So it's like your description with multiple events inside the compressed data.

**Comment by driskell** [comment]
I've uploaded this to docs/Protocol.md on master branch :) If you need any more information let me know.
