### ISSUE TITLE
Multiple SSL certificate files

### ISSUE THREAD

**Issue by angel-smile** [driskell/log-courier#272]
In log-courier configuration file, since we can specify multiple logstash servers, is it possible to also specify different SSL ca files for different servers as they might use different certificates? Excuse me if my question is silly:)

**Comment by driskell** [comment]
Hello. This should be possible by just concatenating the certificates together into a single file and providing that as the CA file. If I remember correctly, the CA file can contain as many certificates as you need, whether that be intermediates to complement a root or multiple roots. Give it a go!

**Comment by angel-smile** [comment]
I've tried that and looks like it's working. Didn't know that the CA file can contain multiple certificates. Thank you for the information!

**Comment by driskell** [comment]
I'll be sure to update the docs!
