### ISSUE TITLE
lc-admin missing in Ubuntu setup

### ISSUE THREAD

**Issue by dkirrane** [driskell/log-courier#273]
`lc-admin` does not seem to be available when you install logcourier using Ubuntu steps defined here: https://github.com/driskell/log-courier#ubuntu

**Comment by driskell** [comment]
Very odd. Can you check `/usr/bin` it should be installed there. I checked the scripts and it seems it SHOULD be, though I only use Ubuntu to build the packages (as it mentions in the docs I don't do any extensive testing like I do with the RPM.)

**Comment by driskell** [comment]
Could you let me know the version of the package you are using? I wonder if it's an older one as I do remember at one point the PPA stopped allowing updates to some old versions of Ubuntu so maybe it's one that didn't bundle lc-admin :-(

**Comment by driskell** [comment]
I'll close this now as I can't seem to work out why this would be missing as it should be packaged.
