### ISSUE TITLE
Not compatible with master branch of https://github.com/op/go-logging

### ISSUE THREAD

**Issue by kabakaev** [driskell/log-courier#274]
Current master branch of https://github.com/op/go-logging has incompatible log message formatting placeholders.

As a result, log file is full of corrupt messages:
2016/02/18 06:25:05.089829 %d payloads still pending, resetting timeout 10
(%d is not substituted).

In order to fix the issue, I had to recompile with version of go-logging from January 2016.

```
cd ~/build/log-courier-1.8.2/src/github.com/op/go-logging
git checkout fa10849c4063391f2be4c61c32bd9cc82f3ddb57
cd ~/build/log-courier-1.8.2
make
```

All tests were performed on Debian Wheezy with golang-1.3.3 from backports repo. 

Same bug is reproduced on wheezy with the latest golang binary package.

Finally, the bug is reproducible on current master branch of log-courier, revision 17d0c19d152d60c4afb463c69364fcbf55d5e3f5.

**Comment by kabakaev** [comment]
Temporary fix is implemented in https://github.com/driskell/log-courier/pull/275

**Comment by driskell** [comment]
Thanks for the report! I've been tinkering with Godep and looking at using Go 1.5/1.6 censoring but need to check Ubuntu Go versions for compiling. Will get this merged in manually as I'm on the brink of pushing a v2 beta once it compiles.

**Comment by driskell** [comment]
I merged into 1.x branch. Thanks!
It's also fixed in master.
