### ISSUE TITLE
log-courier 2.x ?

### ISSUE THREAD

**Issue by sysmonk** [driskell/log-courier#278]
Hi,

It looks like log-courier 2.x is on the way (based on the recent mass-closure of issues). Can we get some status updates on how it goes, maybe needs some testing and etc?

From what i understand it will fully remove support for the ZMQ transport? Will the protocol be backwards compatible with log-courier 1.x (will 1.x clients be able to connect to logstash with 2.x log-courier plugin)? 

Thanks again for developing this product!

**Comment by driskell** [comment]
Hello!

It's in a testable state right now and definitely needs lots of testing. The entire publishing system is reworked. I'm working on getting it into some small environments this week to test memory and stability. Load balancing is also not making the best decisions just yet but that's to come (it logs the latency at the moment but doesn't use it in deciding best server.) And I still plan on a few extra options and improvements to `lc-admin` and packaging.

Yes, ZMQ will be gone completely. Protocol is completely backwards compatible with 1.x plugin. In fact I separated versioning of the plugin from Log Courier itself (https://github.com/driskell/logstash-input-courier) and the plugin won't be updated until the client is finished. The plugin update will bring memory improvements in Logstash and I'm hoping it will coincide perfectly with stability to the metrics and API features heading for the next major Logstash.

**Comment by driskell** [comment]
We can continue the discussions in #257
