### ISSUE TITLE
Logging as JSON

### ISSUE THREAD

**Issue by rhoml** [driskell/log-courier#280]
Is it possible to make log-courier log in Json format? That way we could monitor log-courier with logstash easily :)

**Comment by driskell** [comment]
Is there specific information you'd like to monitor?

I've never been sure if sending the shipper logs using the shipper is a good thing to do. When an error occurs more logs are generated but wouldn't be able to transmit, so might cause pressure buildup for when it reconnects. You also have the problem where if shipper isn't shipping, the problem can only be discovered by a lack of logs arriving as opposed to a specific log arriving.

There is `lc-admin` that provides status information that can be tied into monitoring tools like `munin` and `nagios` which may be better (I use it this way) as it's independent of the log pipeline. I'm all open to ideas though.

**Comment by rhoml** [comment]
So you are right when it comes to find why the logs are not getting shipped. But if we could have some telemetry in the logs it would be nice so we could graph in kibana metrics about log-courier and detect hosts that are getting behind for example. 

Also a good things would be if the current information that is been logged at start could be logged as json, I know we have the lc-admin but I'd like to see this information in kibana too.

**Comment by driskell** [comment]
If we make the log file for log-courier log as JSON - would you use Log Courier to ship that to Logstash? I'm wondering if the best thing here is telemetry like you say but internal to Log Courier so it doesn't get printed to a log file - it just gets shoved into the pipeline and eventually hits Logstash. This wouldn't be a solution for everything though - you'd only be able to see telemetry for clients that are connected and sending - so you'd be able to see pipeline latency (it could send an event to say how far behind log files are). However, if the connection is not present, there would be no information.

Does this sound like what you're looking for?

**Comment by rhoml** [comment]
This is correct, 
I would like to send that telemetry to logstash and monitoring that could help us detect any bottleneck on the pipeline. For example, if log-courier shipping gets slower or if something happens regularly at certain period of time it could help us detect if something is wrong on the pipeline or if logstash isn't able to cope with the load.

**Comment by driskell** [comment]
Hi - I'm going to close this issue as I'm unsure at this stage on the best approach.

Logstash is introducing full telemetry and metrics and it may be that I implement all the metric bits at that side rather than in Log Courier - or it may even be that Logstash is able to provide the telemetry as is.

I do plan at some point to consider sending some of the `lc-admin` metrics as periodic events so there is some telemetry from the shipper too but I'm wanting to see what we can do with Logstash first before looking at that, and I'll raise an issue about doing this once I finished that investigation.

Thanks for the ideas!
