### ISSUE TITLE
question on negate option for multiline and filter codecs

### ISSUE THREAD

**Issue by PMDubuc** [driskell/log-courier#283]
I notice that the negate option has been removed in favor of negation in the pattern.  I can't determine what version it was removed in and whether it should still work in the 1.8.2 version I am using.   I have many config files that use the negate option instead of negation in the pattern.  Do I need to modify them all?

Thanks,

**Comment by driskell** [comment]
Hello

It hasn't been removed yet. But it will be removed in v2.0 and placed in the pattern, and you'll be able to specify multiple patterns too and multiple codecs.

1.x branch is 1.8.2 still and I'm releasing a minor fix release soon. 2.0 is in beta and can be tested but not yet stable configuration or functionality wise as I'm still working on it.

**Comment by PMDubuc** [comment]
Thank you.  So will it work both ways in 1.8.2?

**Comment by driskell** [comment]
No it will stay same in 1.8.2 and the following release and throughout 1.x if there's further releases as I don't want to break any configurations people have.

2.0 is where I'm breaking them :-) though for the better I hope!
