### ISSUE TITLE
Multiple "Transport init failed: DNS lookup failure" upon losing the network

### ISSUE THREAD

**Issue by kargig** [driskell/log-courier#284]
I'm not sure this is a bug, probably a feature request.

When a machine running log-courier loses access to the network, log-courier starts writing to syslog lines like:
```
Mar  1 13:51:54 hostname log-courier[15233]: Transport init failed: DNS lookup failure "host.example.com": lookup host.example.com: no such host"
Mar  1 13:51:55 hostname log-courier[15233]: Transport init failed: DNS lookup failure "host.example.com": lookup host.example.com: no such host

```
every single second creating a small "flood" of errors.

When the remote endpoint is not accessible, log-courier retries to connect every 'timeout' seconds.
```
Mar  1 13:52:03 hostname log-courier[15233]: Transport init failed: Failed to connect to 7.7.7.7:5555 (host.example.com): dial tcp 7.7.7.7:5555: i/o timeout
Mar  1 13:52:09 hostname log-courier[15233]: Transport init failed: Failed to connect to 7.7.7.7:5555 (host.example.com): dial tcp 7.7.7.7:5555: i/o timeout
```

It would be nice if log-courier was somewhat less noisy when it cannot resolve the remote endpoint, eg log failures every X seconds. A network outage can potentially create hundreds or thousands of unneeded log lines.

**Comment by driskell** [comment]
Absolutely. I am planning to get 1.8.3 launched with some fixes shortly and will try to get this included.

2.0 will include it too

**Comment by driskell** [comment]
The improvement will be to back off after each consecutive failure, increasing the wait time until it reaches about a minute or more, and possibly then suppressing messages

**Comment by kargig** [comment]
thanks a lot!

**Comment by driskell** [comment]
I'll add a couple more options soon to configure specifics. At moment it's a 25% back off so each wait is 25% longer than the last, up a maximum of 6000% (60 times the wait)

So eventually on a 1 second reconnect (default) it reconnects once a minute.
