### ISSUE TITLE
Allow "/foo/**/*.log" in fileglobs to match the current subdirectory and arbitrary sub-directories.

### ISSUE THREAD

**Issue by yeroc** [driskell/log-courier#285]
Currently log-courier doesn't appear to support matching in cases where logs are spread out over arbitrary depths of sub-directories.  This is commonly supported via a ".../**/.." fileglob operator in other systems.

Is there any chance this could be supported?  If not, is there a way to achieve this already with log-courier?  

Thanks,
Corey

**Comment by yeroc** [comment]
Looking at the code I guess you're using Go's built-in Glob function so this isn't supported in the core library right now: golang/go#11862.  That ticket does reference at least one other alternative library that adds support for this though...

**Comment by driskell** [comment]
Could you let me know the structure of your logs that would require this functionality?

**Comment by yeroc** [comment]
@driskell The logs are spread out in sub-directories that mirror the mapping of services to a hierarchical URL structure.  So someone can add a new service in a sub-directory another level deep and log-courier doesn't see it anymore.  This is a commercial third-party product so we don't have control over where the logs are placed.  Hope that makes sense.

**Comment by driskell** [comment]
Found a package that will do this as a drop in replacement for Glob
