### ISSUE TITLE
log-courier 2.x: issues with building from source

### ISSUE THREAD

**Issue by sysmonk** [driskell/log-courier#286]
Hi,

Tried log-courier 2.x today, there's some issues with building ( based on https://github.com/driskell/log-courier/blob/master/docs/BuildingFromSource.md ):

Issue 1:

```
~$ go version
go version go1.6 linux/amd64
~$ export GO15VENDOREXPERIMENT=1
~$ go get -d https://github.com/driskell/log-courier
package https:/github.com/driskell/log-courier: "https://" not allowed in import path
```

The `go get` command fails. It does work if i remove https:// (it doesn't work with http:// either).

Issue 2: 
Typo in the docs: 
```cd $GOPATH/src/gitub.com/driskell/log-courier```
shuold be:
```cd $GOPATH/src/github.com/driskell/log-courier```

Issue 3:
```
$ go get -d github.com/driskell/log-courier
package github.com/driskell/log-courier: no buildable Go source files in /home/sysmonk/gosrc/src/github.com/driskell/log-courier
```
The ```go get``` command refers to the driskell/log-courier, which is a default branch of 1.x. Log-courier 2.x branch is 'master'. I don't know how to checkout that branch with ```go get``` though. I just did ```git checkout  master``` in $GOPATH/src/github.com/driskell/log-courier

**Comment by driskell** [comment]
Thanks -I've updated docs.
I plan to do a full run-through once I switch over the main branch to master to check it, and also test the Windows compilation at that point.
