### ISSUE TITLE
feature of listening log4j socket ???

### ISSUE THREAD

**Issue by iamtiancaif** [driskell/log-courier#291]
hi everyone, does log-courier support listening log4j socket like logstash?

_input {
  log4j {
    mode => server
    host => "0.0.0.0"
    port => [log4j_port]
    type => "log4j"
  }
}
output {
  elasticsearch {
    protocol => "http"
    host => "[myIpAddress]"
    port => "[myPort]"
  }
}_

In my project i use courier to transfer log to a center which actual is a logstash cluster that store logs into redis before indexing into es. My colleague observe that sync log writing into disk become a bottleneck under great throughput. 
I don't want to swtich my client to logstash because it's much heavier than courier.

BTW, i am using the version before f4ad5d987a9cecfe2fdc8cdbf3005084c3d49c9a, forget the excactly version.

thanks.

**Comment by driskell** [comment]
Hello!

No it doesn't support that I afraid. It only ships log files. Log4j could be sent over the network directly to Logstash though but it wouldn't be encrypted I guess. I've rarely seen sync IO issues for general logs, and where it is an issue you might find using memory storage efficient, such as tmpfs if it's Linux

**Comment by iamtiancaif** [comment]
thanks very much! I'll figure it out another way.
