### ISSUE TITLE
Windows: Unable to build lc-admin from master

### ISSUE THREAD

**Issue by jfrome** [driskell/log-courier#292]
I receive the following error when running the following command in Windows:
```
$ go install . ./lc-admin ./lc-tlscert
# github.com/driskell/log-courier/lc-admin
lc-admin\admin.go:34: undefined: admin.Client
```
Both log-courier.exe and lc-tlscert.exe are built without errors.

Per documentation here: https://github.com/driskell/log-courier/blob/master/docs/BuildingFromSource.md#windows

**Comment by driskell** [comment]
lc-admin is currently in development still so doesn't work in master currently as WIP. Expecting to resolve it shortly

**Comment by driskell** [comment]
You can successfully build the other components though just by omitting ./lc-admin from the argument lists

**Comment by driskell** [comment]
lc-admin is now updated
