### ISSUE TITLE
Windows: "No buildable Go source files" when building from master

### ISSUE THREAD

**Issue by jfrome** [driskell/log-courier#293]
I receive the following error after running `go get -d github.com/driskell/log-courier`: 
```
$ go get -d github.com/driskell/log-courier
package github.com/driskell/log-courier: no buildable Go source files in C:\GOWORKSPACE\src\github.com\driskell\log-courier
```
I was able to work around this by doing the following:
```
cd %GOPATH%/src/github.com/driskell/log-courier
git checkout master
```

Seems that the `go get` command needs to specify the master branch, or update the instructions to change branches.

**Comment by sysmonk** [comment]
Similar reported in #286

**Comment by driskell** [comment]
This would work if master was default branch.

I'm going to look at gopkg.in as I think it'll get this working whatever is the default branch.

**Comment by driskell** [comment]
Will close as once branch switched to 2.x it will work. Thanks
