### ISSUE TITLE
Question: Can we use multiline and filter codec together?

### ISSUE THREAD

**Issue by amodakvnera** [driskell/log-courier#295]
Hello,
I have a query - can we use multiline and filter codec together?
something like this -
"codec" : {
          		        "name": "multiline",
                                "pattern": "^INFO:|^Exception|^SEVERE:|^[0-9][0-9]:|^[0-9][0-9][0-9][0-9]-",
                                "negate": true,
                                "what": "previous"
                 },
"codec" : {
                               "name": "filter",
                                "patterns":  [ "^(.*sometext.*)$"]
                }

So first run multiline for all the lines and then send only if it has "sometext" present in it

Thanks,
Ashish

**Comment by jfrome** [comment]
You can starting with the new 2.x branch ( currently the master branch).  See #257.

**Comment by driskell** [comment]
Yes this is now working in the master branch too. Though build steps don't work great at moment and still a few bugs to fix and lc-admin to update.
