### ISSUE TITLE
Installing latest with apt-get

### ISSUE THREAD

**Issue by dkirrane** [driskell/log-courier#296]
I'm trying to get the latest log-courier version on Ubuntu 14:04.
The below command installs `Log Courier version 1.8-11.ge745e9e`
```
	add-apt-repository -y ppa:devel-k/log-courier \
	&& apt-get update \
	&& apt-get install -yq log-courier
```

**Comment by driskell** [comment]
That looks right.

Were you expecting 2.0? It's currently in alpha at moment and still under last leg of development.

**Comment by dkirrane** [comment]
I was expecting v1.8.2 
https://github.com/driskell/log-courier/releases

**Comment by driskell** [comment]
1.8.2 is a plugin only release. Log Courier had no changes.
I know it's not clear though and that's why I moved the plugins to separate version numbering. It'll be cleared soon when I push out 1.9 and a 2.0 beta

**Comment by driskell** [comment]
So latest Log Courier is indeed 1.8.1. Sorry for the confusion
