### ISSUE TITLE
panic: interface conversion: admin.APINavigatable

### ISSUE THREAD

**Issue by alexandervasylev** [driskell/log-courier#298]
10.2-RELEASE FreeBSD
go version go1.6 freebsd/amd64
git branch master (760022841382fd1cb80f7d9bdc4aa55e5a9d0b89)

$ ./log-courier -config lc.conf 
2016/03/28 14:49:35.963469 Log Courier version 2.0.0-beta1 pipeline starting
panic: interface conversion: admin.APINavigatable is nil, not *admin.apiRoot

**Comment by driskell** [comment]
There was a bug causing crash if admin was disabled. It's fixed now!
