### ISSUE TITLE
filter codec seems to disable multiline in 1.8.2

### ISSUE THREAD

**Issue by PMDubuc** [driskell/log-courier#299]
I have a configuration that uses both the multiline and the filter codec.  I want the filter to remove events contain the pattern (the string "[org.xxx.proxy.ASN1Proxy]" in this case, but when I include it, only the first line of every multiline message in the log is sent to logstash.  Why does this happen?  Here is an example of a file that I'm pulling in with an "includes" statement:

[ {
  "paths": [ 
     "\<logfile path\>"
    ],
  "fields": { "type": "\<log type\>" },
  "codec": {
    "name": "multiline",
    "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}",
    "negate": true,
    "what": "previous"
  },
  "codec": {
    "name": "filter",
    "patterns": [ "^(.*\\\\[org.xxx.proxy.ASN1Proxy\\\\].*)$" ],
    "negate": true
  }
} ]

**Comment by driskell** [comment]
Only one codec can be provided in 1.8.2.

When decoding the configuration from JSON it will actually not see the second block as in JSON it would replace the first.

You could try the experimental 2.0 in master branch as that fully supports it, specifying codecs as an array. Though it's very much in beta at the moment.
