### ISSUE TITLE
log-courier 2.x: Option /general/admin enabled is not available

### ISSUE THREAD

**Issue by jfrome** [driskell/log-courier#301]
I am running the latest version of master and run in the following issue when starting/checking syntax:

[root@server-01 bin]# ./log-courier -config="/etc/log-courier/log-courier.conf" -config-test
Configuration test failed: Option /general/admin enabled is not available

Process starts and runs fine if admin interface is disabled.  The same error occurs in Windows.

**Comment by driskell** [comment]
This was changed recently in the master branch and documentation was not updated accordingly. Apologies for that. I'm getting really close to a release though at which point I'll verify all docs. I'll get these docs updated ASAP too.

Administration options have been moved out of `general` and are now within a new `admin` section.

`/general/admin enabled` is now `/admin/enabled`
`/general/admin listen address` is now `/admin/listen address`

This is to make the configuration system more modular.

**Comment by driskell** [comment]
If you are building successfully in Windows please do let me know! Any feedback on it is greatly appreciated as I've not managed to test it yet. It'll help me clear up #211 - thanks!

**Comment by driskell** [comment]
I've now updated the documentation. Sorry about that!

https://github.com/driskell/log-courier/blob/master/docs/Configuration.md#admin
