### ISSUE TITLE
lc-admin utility outdated

### ISSUE THREAD

**Issue by sysmonk** [driskell/log-courier#308]
Hi,

seems that the information in https://github.com/driskell/log-courier/blob/master/docs/AdministrationUtility.md is outdated. There's no thing as "status", the supported commands are:
```
> help
Available commands:
  prospector [status | files [id]]
    Get information on prospector state and running harvesters
  publisher [status | endpoints [id]]
    Get information on connectivity and endpoints
  version
    Get the remote version
  exit
    Exit
```

The `help` also doesn't show a "reload" command, which is supported.

**Comment by driskell** [comment]
Thanks! I definitely missed that one.

It needs to be documented that it is now a REST API, so data can be pulled from anything, not just `lc-admin`

**Comment by driskell** [comment]
I've updated documentation. It's still limited but I'll increase it over time as I grow the REST API itself.
