### ISSUE TITLE
Question: Is log-courier v. 2.x backward compatible with logstash 1.5.x?

### ISSUE THREAD

**Issue by PMDubuc** [driskell/log-courier#313]
Thanks!

**Comment by PMDubuc** [comment]
Also, does log-courier 1.8.2 work with Logstash 2.x?

**Comment by driskell** [comment]
The protocol and plugins are unchanged, so yes!

I am releasing a major update the input plugin soon as I get to it.

**Comment by driskell** [comment]
The major update should be compatible too with 1.5.c
