### ISSUE TITLE
Documentation example for "includes" shows JSON.

### ISSUE THREAD

**Issue by PMDubuc** [driskell/log-courier#318]
How would it look in YAML?  A list?

includes:
    - "path1"
    - "path2"

**Comment by driskell** [comment]
Yes. I will plug the hole in the documentation soon!

**Comment by PMDubuc** [comment]
For example, in config/log-courier.yaml  I have:

...
includes:
    \- "config/includes/*.yaml"

and in config/includes I have 2 files:
user_log.yaml has:

\- paths:
    \- "/logs/user*.log
fields:
    type: "user_log
codecs:
    \- name: multiline
       patterns:
             \- "!^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3} "
       what: previous

and another file called systemlog.yaml which is the same except for the path and the type values.
When I run log-courier I get
Configuration error: yaml: line 2: did not find expected '-' indicator
in stdout.  I don't think the problem is with the first file but with the included files.  But I don't know what's wrong.

**Comment by driskell** [comment]
Fixed
