### ISSUE TITLE
/var/run is tmpfs on Ubuntu

### ISSUE THREAD

**Issue by lawrencedudley** [driskell/log-courier#321]
/var/run/log-courier gets deleted on reboot - the init script should create this directory on start

**Comment by driskell** [comment]
Thanks for reporting this! It's something I was not aware of.

**Comment by lawrencedudley** [comment]
No worries! I'd stick a pull request in but am concerned I'd break something.

I did a bit of digging and it's because /var/run is tmpfs on Ubuntu.
