### ISSUE TITLE
unable to parse some log file lines

### ISSUE THREAD

**Issue by MKuzma** [driskell/log-courier#325]
I am updating log-courier to a recent version of 2.0.3. On Red-Hat 6 and Debian 5 (yes a bit older) I am observing issues that log-courier cannot encode line with a comment in its own log file: 
`2016/06/10 14:56:01.280182 Skipping line in /var/log/sar_mem.log at offset 26789336 due to encoding failure: json: unsupported type: map[interface {}]interface {}`
Line looks like this:
`2016-06-10 15:11:01 293644 22240908 98.70 60736 18124096 16259496 1315608 7.49 206540`
Whereas other log files are parsed without any issue and may look similar to this:
`2016-06-10 15:12:01        all      7.30      0.00      0.98      0.58      0.00     91.14`
or this:
`2016-06-10 15:08:01          sda     42.62    343.36   1706.26     48.09      0.52     12.32      3.96     16.89`
Is it a kind of an issue of log-courier or go lang itself? Log-courier version 1.8.1 parsed these lines no worries.

**Comment by driskell** [comment]
Oh

Are you using a `fields` declaration in your config, containing a key-value map? Is your config YAML?

I think if you switched back to JSON it will work if so. I'll check this and fix it when I get a moment.

Thanks for bringing it to my attention.

**Comment by MKuzma** [comment]
Tried the 2.0.4 today. Yes you are right I migrated the config to YAML. Unfortunately I'm getting the same error:
`2016/06/13 10:40:02.042098 Skipping line in /var/log/sar_mem.log at offset 27145344 due to encoding failure: json: unsupported type: map[interface {}]interface {}`
for these log lines:
`2016-06-13 10:41:01 226496 22308056 98.99 44668 17731048 16486360 1088744 6.19 179128`
The YAML part of config is here:
`- paths: [ "/var/log/sar_mem.log"]`
`   add host field: true`
`   fields:`
`    type: "sar_mem"`
`    site: "XXXXX"`
`    codecs:`
`     - name: plain`

` - paths: [ "/var/log/sar_io.log"]`
`   add host field: true`
`   fields:`
`    type: "sar_io"`
`    site: "XXXXX"`
`   codecs:`
`    - name: plain`
The sar_io.log line: `2016-06-13 10:45:01        24.80      9.94     14.86    467.70    244.54` as well as couple of other sar_xyz.log lines seems to be encoded fine.

**Comment by driskell** [comment]
Can you check the `codecs` is indented correctly?

Looks like it might be embedded into `fields` due to indentation. And I can see why my fix did not work - I didn't account for the fact there's an array there (`- name: plain`). But looks like you'll be able to fix this by fixing the indentation.

When `plain` is required - I would remove the entire `codecs` declaration from the configuration, as its the default anyway and always will be.

**Comment by MKuzma** [comment]
Oh,
I am sorry I overlooked the indentation, somehow I got one white space symbol more in front of codecs. Log-courier 2.0.4 works fine even with `-name plain`! No more notifications in log-courier log file.

**Comment by driskell** [comment]
Great! I'll attempt to get the final fix into a 2.0.5 in the future. I mainly see one-level hash in the `fields` like you have here and very little arrays or nested fields so should be OK for 99% of people until 2.0.5, which I'd rather leave a few weeks :)

Thanks for reporting though!

**Comment by MKuzma** [comment]
You're welcome! Thank you for a very quick response anyway, I really appreciate that :)
