### ISSUE TITLE
how safe is it to kill logstash when using courier input only?

### ISSUE THREAD

**Issue by tomryanx** [driskell/log-courier#326]
I'm having some issue with logstash shutdown times that I won't go into here, and I'm wondering whether I can safely use the `--allow-unsafe-shutdown` option before I have them solved.  In other words, whether the log-courier client will be aware of whether a document was really indexed and retry if not.

In case it's relevant, duplication is not an issue because I compute doc IDs based on message - all I need to ensure is 'at least once' delivery.

**Comment by driskell** [comment]
Log Courier implements at least once semantic when shipping to Logstash. However, Logstash does not when sending to Elasticsearch. Anything Logstash has acknowledged as received but wasn't yet sent to Elasticsearch during shutdown would be lost. That's unless your using the newest beta versions I think which have queue persistence options you can enable but I've not played with it yet to see how it works.

Best approach if you cannot lose messages is to shutdown the shippers cleanly and wait for Logstash to finish flushing before stopping it.

**Comment by tomryanx** [comment]
Understood, thanks
