### ISSUE TITLE
HTTP(S) transport

### ISSUE THREAD

**Issue by punya** [driskell/log-courier#328]
Would you accept a PR to add support for HTTP(S) as a transport?

I'm running Logstash in a restricted environment where I can only consume HTTPS rather than raw TCP, and I'd like to avoid running something to postprocess log-courier's output in order to send it to Logstash (which already has an HTTP input plugin).

**Comment by driskell** [comment]
I would consider it. The issue I see though is only one event can be sent in each request and there would be a response for every request. Making that asynchronous might be difficult and so overall it would be significantly slower than the TCP option.

Any variance in performance on the Logstash side could also cause timeouts and unnecessary retransmits as there's no flow control.

But maybe these are acceptable trade offs in some environments where policy cannot be updated for additional protocols.

**Comment by punya** [comment]
Thanks, I'll write something up and see if I can find ways to mitigate the
issues you mentioned.
