### ISSUE TITLE
Custom JSON fields as version identifiers ?

### ISSUE THREAD

**Issue by maneeshmehra** [driskell/log-courier#330]
Hi:

We catalog our log-courier configuration file in a git-based source code repository. Changes to this configuration file are then pushed out to the system whose logs need to be shipped via a Chef installation of log-courier. As part of identifying the exact version of the configuration file running on each system, we'd like to introduce our own versioning scheme inside the configuration file. These would be updated with information like git commit ID, date-time stamp, Jenkins build ID, Chef cookbook version ID etc, so that at runtime we can identify the exact version of the configuration file in use. I'd like to know if we can introduce a set of custom fields like these into the configuration file ? If yes, then where ?

Thanks,

Maneesh

**Comment by driskell** [comment]
Take a look at the `global fields` option which allows you to add additional fields to the event sent across to Elasticsearch, which could be the version number.

If the version doesn't need to be in the event, and you only need it "noted" in the configuration file, the configuration file accepts comments. YAML takes normal YAML comments and JSON configuration files do take comments as well as an extension to the standard.

**Comment by driskell** [comment]
There's YAML example of `fields` here: https://github.com/driskell/log-courier/blob/master/docs/examples/example-fields.yaml

I do need more examples :)

You can use `global fields` like this:

```
general:
  global fields:
    config_version: 1.0
    deployed_date: 27-06-2016 22:34:00 +0100
```

**Comment by maneeshmehra** [comment]
Thanks. This is great !
