### ISSUE TITLE
Is logstash 2.3 supported?

### ISSUE THREAD

**Issue by martinhynar** [driskell/log-courier#331]
Hi, I am testing upgrade from logstash 1.5 to 2.3 and I have troubles installing log-courier plugin.
I am on CentOS 6.6 and I did:

```
yum remove logstash (/opt/logstash removed completely)
yum install logstash (LS 2.3.3 installed)
/opt/logstash/bin/logstash-plugin install logstash-input-log-courier
```

This is what I get:

```
Validating logstash-input-log-courier
Installing logstash-input-log-courier
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 2.3.3)

  In Gemfile:
    logstash-core-plugin-api (= 1.18.0) java depends on
      logstash-core (<= 2.3.3, >= 2.0.0) java

    logstash-output-zeromq (>= 0) java depends on
      logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-output-zeromq (>= 0) java depends on
      logstash-mixin-zeromq (>= 2.0.0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0) java

    logstash-input-log-courier (>= 0) java depends on
      logstash-core (~> 1.4) java

    logstash-core (= 2.3.3) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "logstash":
  In Gemfile:
    logstash-input-log-courier (>= 0) java depends on
      logstash (~> 1.4) java
Could not find gem 'logstash (~> 1.4) java', which is required by gem 'logstash-input-log-courier (>= 0) java', in any of the sources.
```

I wonder if log-courier is targeting LS 2.3 or if it is used only for LS 1.x where it heavily outperforms logstash-forwarder. Fingers crossed LS 2.3 is still supported and I dont need to transform my setup to file beat.

Thanks, Martin

**Comment by PMDubuc** [comment]
Try 'logstash-plugin install logstash-input-courier'

**Comment by driskell** [comment]
Ah yes, @PMDubuc is right. The old log-courier name was removed so that it followed normal naming convention of plugins, that the name matches the name inside the configuration (it was always just `courier` in the configuration.)

I'll look at if I can pull that old version/name so it fails.

**Comment by martinhynar** [comment]
Omitting the 'log-' prefix made the installation succeed. Documentation is correct on this, I used obsolete command from my salt rules which had the old name. Thanks for advice guys.

**Comment by driskell** [comment]
No problem! 😃 

I remember a little now why it was renamed. Logstash 2+ required that the plugin name match the name inside Logstash configuration or it wouldn't install (or work - can't remember which). And I think I had problems getting `log-courier` with a hyphen working in the configurations - but either way it would break someone's configuration just by updating which I also wasn't willing to do. So I renamed the plugin so it was just `courier` in both the gem name and in the configuration.

Problem then was I can not yank all the `logstash-input-log-courier` gems offline. In doing so it would allow anyone else to take that name. So it's kinda stuck there with an older version 😒 If anyone has any ideas though I'm all ears!
