### ISSUE TITLE
Configuration Error: /general/persist directory must be specified

### ISSUE THREAD

**Issue by sxk14** [driskell/log-courier#332]
Hello,
I'm receiving this error when trying to run log-courier....

**Configuration Error: /general/persist directory must be specified**

I'm using the following command: log-courier.exe -config log-courierr.conf

Could I please get some help on what I need to do to solve this. My Config file is below

Thank You!

```
{
    "network": {
      "servers": [ "xxxxxxx" ],
	    "ssl ca": "C://Program Files//Logstash/logstash-forwarder.crt"
    },
	   "files": [
        {
           "paths": [ "C:\\xxx\\xxx\\LogFiles\\W3SVC*\\*"],
           "fields": {
		          "type": "IISLog",
		          "team": "NEB"
		       }
        },
	      {
           "paths": [ "C:\\xxxx\\xxxxx\\LogFiles\\HTTPERR\\*.log"],
           "fields": {
		         "type": "HTTPLog",
		         "team": "NEB"
		        }
        },
		
			{
           "paths": [ "D:\\xxxx\\Lux\\*.txt"],
           "fields": {
		         "type": "BunyanLog",
		         "team": "NEB"
		        }
			}
    ]
}
```

**Comment by driskell** [comment]
You have network and files sections. You need to add a new general section with a "persist directory" option. You should set this to where you want the database to be saved. In version 1.x it used to be saved to the working directory but now it is required to be explicitly set.

**Comment by sxk14** [comment]
Thanks for the quick reply!
We aren't using a DB for this. Is there a default setting I can set to bypass "persist directory" option.  I tried to enter a random path and i'm getting the following error now. "Configuration error: Option /persist directory is not available".

Not sure if this helps but, our ELK server is running on linux and our clients are on windows.

**Comment by driskell** [comment]
There is always a database. It is used to store the last offset in the files that were transmitted so if the server reboots or anything crashes it can resume where it left of. It is called the "registry".

Looks like you need to set it under "general" and not at the root, like so:

```
{
  "general": {
    "persist directory": "/var/lib/log-courier"
  },
  "network": {
...
  }
}

```
