### ISSUE TITLE
How can I read cpuprofile output

### ISSUE THREAD

**Issue by dkirrane** [driskell/log-courier#333]
Hi,

I've created a profile file with the [cpuprofile cli arg](https://github.com/driskell/log-courier/blob/master/docs/CommandLineArguments.md#-cpuprofilepath)

Not familiar with Golang. Is there some Go tool I need to use to read it?
Also, is there an option to monitor memory and network usage also? Or is this also included with cpuprofile

**Comment by driskell** [comment]
You can use the `go tool pprof` command.

Is there a specific issue you are investigating?

**Comment by dkirrane** [comment]
Thanks, no issue just want to profile cpu, memory, network usage under high log output. Maybe linux tools like top etc are a better option. this is more for debugging I guess
