### ISSUE TITLE
[Enhancement] Support for filtering log statements

### ISSUE THREAD

**Issue by dkirrane** [driskell/log-courier#339]
It would be great if there was a way to ship only certain log statements. 
For instance only ship lines containing `WARN` or `ERROR`:

```
files:
- paths:
  - "/var/log/App*.log"
- line-contains:
  - "ERROR"
  - "WARN"
```

**Comment by PMDubuc** [comment]
dkirrane wrote:
> It would be great if there was a way to ship only certain log statements.
> For instance only ship lines containing |WARN| or |ERROR|:
>


Try something like this. I haven't tested it, but it should be close to what 
you need:

files:
   - paths:
     - "/var/log/App*.log"
     codecs:
       - name: filter
         patterns:
           - ".*\|WARN\|.*"
           - ".*\|ERROR\|.*"
         match: all

**Comment by driskell** [comment]
Thanks @PMDubuc  :) Yes, the `filter` codec is the way to go @dkirrane 

I think possibly just `"WARN"` and `"ERROR"`, if sufficient, would be even better as it less CPU I think with no wildcard. Though I may be forgetting how my own filter functionality works 😄
