### ISSUE TITLE
Logstash installation fails with latest logstash logstash:5.0.0-alpha5

### ISSUE THREAD

**Issue by sklaus** [driskell/log-courier#340]
I'm using the official container form dockerhub

docker pull logstash:5.0.0-alpha5

When I try to install the logstash-input-courier plugin, I get:

```
root@8869b8abf890:/# /usr/share/logstash/bin/logstash-plugin install logstash-input-courier
Validating logstash-input-courier
Installing logstash-input-courier
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 5.0.0.pre.alpha5)

  In Gemfile:
    logstash-core-plugin-api (>= 0) java depends on
      logstash-core (= 5.0.0.pre.alpha5) java

    logstash-input-courier (>= 0) java depends on
      logstash-core (~> 1.4) java

    logstash-core (>= 0) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by driskell** [comment]
I have yet to update the plugins to allow install onto the new Logstash 5. I'd like to do some tests too before I do. I'll try to get to this soon and also push up the latest plugin which is much faster and more efficient.

**Comment by muppettizer** [comment]
Hi, any update on when the Logstash 5 plugin might land?

**Comment by danufriev** [comment]
Hi! Do you have any update on this issue?

**Comment by driskell** [comment]
If anyone still needs it. I just pushed 1.9.1 of the plugin which hopefully will now work.
