### ISSUE TITLE
Log Courier holding on to the log files and Logstash ?

### ISSUE THREAD

**Issue by Inderjeet26** [driskell/log-courier#343]
Hello,

What happens when the Logstash comes back up and the Log Courier which is still holding onto the log files. Does the Log Courier send those old logs now in the already rotated opened log files?

Thanks

**Comment by driskell** [comment]
Hello

Yes as long as log-courier hasnt been restarted any rotated files will still be "held" until they can be sent to log stash so as soon as logstaahcomes online it will flush the logs to it and then eventually close the file freeing resources.

If the file rotated by truncation though the data will be lost as it won't be held anywhere.

Jason

**Comment by driskell** [comment]
Related to #261 - I've been meaning for some time to look at putting some better handing into this so files are released after certain period of time
