### ISSUE TITLE
logstash-input-courier plugin install on logstash 5.x

### ISSUE THREAD

**Issue by berglh** [driskell/log-courier#351]
I was not able to raise an issue on [https://github.com/driskell/logstash-input-courier](logstash-input-courier) repo, so I thought I'd report here. Sorry if this is misguided. When I attempt to install the input plugin for logstash in version 5, it has a bit of a barney about logstash-core version mismatch.

```
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 5.0.2)

  In Gemfile:
    logstash-core-plugin-api (>= 0) java depends on
      logstash-core (= 5.0.2) java

    logstash-input-courier (>= 0) java depends on
      logstash-core (~> 1.4) java

    logstash-core (>= 0) java
```

My question is also about the future of log-courier, as much as it is about a request to update the plugin for this version of logstash. Will log-courier continue on into the new logstash regime; or given the rising maturity of elastic beats and the slowness improvements of logstash-input-beat plugin, is there little point to replicate?

Under my version 2 testing of logstsah, the courier plugin was several times faster, particularly with multi-line log events. I think a lot of these issues have been addressed in logstsah-input-beats for version 5 of logstash, but for the mean time we're still using log-courier as our primary log shipper.

**Comment by ninjada** [comment]
hit this roadblock too.. will log-courier be updated?

**Comment by gupta2007vaibhav** [comment]
facing same issue. any solution ?

**Comment by sysmonk** [comment]
@driskell can we get any comment about this, or should we all start moving our log-couriers to beats :( ?

**Comment by tobias-m** [comment]
I faced the same issue after upgrading to 5.1.2 and want to share my solution for everyone who is interested.

https://gist.github.com/tobias-m/8eb16fc7ebafbf3eced3847da1fc1ebe

**Comment by driskell** [comment]
Apologies for the delay. Life took hold.

I just pushed plugin 1.9.1 which hopefully will work. I added a quick rspec test that passed and it seems to install fine now for me. I haven't been able to do a full end-to-end test just yet though but will aim to do this weekend as I have a bit of extra time.
