### ISSUE TITLE
Files encoded Little-endian UTF-16

### ISSUE THREAD

**Issue by disaster37** [driskell/log-courier#352]
hi,

log-courier seems not working right when it read file encoded with " Little-endian UTF-16 Unicode text, with CRLF, CR line terminators"

The multiline codecs not working and I get the following this on ES:

```
\ufffd\ufffd\r\u0000\n\u0000[\u00002\u00000\u00001\u00006\u0000/\u00001\u00002\u0000/\u00000\u00007\u0000 \u00001\u00003\u0000:\u00005\u00001\u0000:\u00000\u00001\u0000.\u00007\u00001\u00009\u0000 \u0000

...
```

**Comment by driskell** [comment]
Log Courier sends text as-is without any transformation of encodings. You should use a filter on the Logstash side to do any necessary transformations you need, probably to UTF-8.

Alternatively, Filebeat supports this kind of encoding handling out-of-the-box so everything arrives in UTF-8 at Logstash/Elasticsearch and has for quite a while now if I remember rightly.
