### ISSUE TITLE
Make log-courier stop watching a file

### ISSUE THREAD

**Issue by pahool** [driskell/log-courier#356]
If I change my log-courier.conf file and remove a file pattern from the watch list and then restart log-courier. Log-courier continues to monitor files that no longer match the new file patterns. Is there a way to force log-courier to drop any files that don't match the current pattern without manually editing the offsets file?

**Comment by driskell** [comment]
Hi

Did you reload or restart? For changes to the watch list I believe a restart is needed.
If you restart, it shouldn't be resuming the files if they don't match the pattern. What should happen is it will load the offset file and create entries for each file, but it will only start harvesters when the path scan from your patterns actually finds the file, at which point it knows it has an old offset entry and so "Resumes". Can you double check your configuration and provide it along with logs showing it resuming?

**Comment by pahool** [comment]
My bad. I was taking presence in the offset file as evidence that the files were still being monitored. I see this is not the case. Thanks for your response.
