### ISSUE TITLE
Support of TLSv1.2 only for Log Courier Input plugin

### ISSUE THREAD

**Issue by alokdnb** [driskell/log-courier#357]
It seems default Log Courier settings allows the TLSv1 .. we wanted to disable the tlsv1.1 and tlsv1. can you suggest whats the good way to disable it out ? I don't see any setting in there. 

Current settings we have is, 
input {
  courier {
    port => 5001
    ssl_certificate => "/etc/coupa/logstash/indexer.pem"
    ssl_key => "/etc/coupa/logstash/indexer.key"

**Comment by driskell** [comment]
The code that handles it is here:
https://github.com/driskell/ruby-log-courier/blob/master/lib/log-courier/server_tcp.rb
I don't know when I will gain time to look at it but hopefully it will guide you where to look if you need to patch something. I will try find some time soon as it's definitely a requirement to enforce 1.2.

**Comment by MKuzma** [comment]
Might be as simple as adding this line:
`ssl.ssl_version = :TLSv1_2`
before or after line 99:
`ssl.set_params`

**Comment by driskell** [comment]
Released as `logstash-input-courier-2.7.2`
