### ISSUE TITLE
Option /network/reconnect backoff is not available

### ISSUE THREAD

**Issue by tedder** [driskell/log-courier#360]
2.0.5. `Configuration test failed: Option /network/reconnect backoff is not available`.

Here's the network section from my file:

    network:
      servers:
      - "hostname:5550"
      "failure backoff": 10
      "reconnect backoff": 10
      transport: tcp

Tried with/without quotes (not sure about spaces in keys in yaml). What's wrong with this?

**Comment by driskell** [comment]
Ouch. Yes I can see this. It looks like I scoped those configurations for `tls` transport accidentally so they don't get picked up by `tcp` transport.

I plan to do a few tweaks soon in next 2-3 weeks I hope. I cannot guarantee but when I do I will be sure to fix this one too.
