### ISSUE TITLE
Prospector taking long time to scan 300k files

### ISSUE THREAD

**Issue by java2kus** [driskell/log-courier#37]
We are using log-courier to scan folders that contain events written in the form of XML files.  We have around 25 folders having different name (by business event type).   In each folder, we create a folder every day where events are logged in XML format.    We log around 300k XML events a day (all folders combined).

We have observed that after a day or so the prospector takes a long time (around 20-25 minutes between the file creation time to harvest time) to harvest new files created in the directories.    This latency increases even further if we check after 3-4 days.   I think this is because the prospector has to compare each file against any changes and then harvest it.   In our case, the XML event on the file system is immutable (i.e. its created and never modified).  

Question:  Is there any setting through which we can tell log-courier to delete the folders  that have already been scanned from its internal prospector registry after a day (through some pattern)?   This will speed up the subsequent scanning as it does not have to scan all those 300k files in the filesystem.

**Comment by driskell** [comment]
Closing as it’s a fairly big task and no bandwidth. And would mean a large rewrite of prospector.
