### ISSUE TITLE
does the includes configuration still work correctly?

### ISSUE THREAD

**Issue by wangzhuo0978** [driskell/log-courier#380]
The version I used before: 
```
Log Courier version 2.0.5
```
way to start the program
```
log-courier -config=/etc/log-courier/log-courier.conf
```
the configuration summary is as follows:
```
{
  "general": {
    "log file": "/var/log/log-courier/log-courier.log",
    "persist directory": "/var/lib/log-courier"
  },
  "network": {
    "servers": ["xxx"],
    "transport": "tcp"
  },
  "includes": [ "/etc/log-courier/conf.d/*.conf" ]
} 
```
When create the sub configure files and  place it when the path meets the conditions set by includes;
it's ok;
but I updated to the current version 2.5.6
It can still be started normally, but the configuration file contained in the includes path is not read;

**Comment by driskell** [comment]
You’re right - it’s loading them but not updating the runtime configuration with the new lists. Sorry about that. I’ll get to it shortly

**Comment by driskell** [comment]
Seeing that some issues have snuck in to the configuration - I resolved the include processing but then the validation has become read only and it's changes are not persisting so there's now new errors. I'll keep this open until that's resolved. I'm gradually adding more tests as the configuration parser is old and never had any (which didn't help in working on what was a feature and what wasn't) so hopefully will stop any further regressions.

So to confirm the 2.6.0 just released is in fact not working unfortunately 😢

**Comment by driskell** [comment]
Should now be resolved. I'll continue to get more tests around that code.
