### ISSUE TITLE
Information about payloads  / different debug level ? 

### ISSUE THREAD

**Issue by sysmonk** [driskell/log-courier#385]
Hi,

Trying to upgrade from 2.0.6 to 2.6.2, and hitting a small issue / feature request.
I've previously (ab)used the information in 'debug' level about the payloads sent/collected, something like this
```
Sep 10 12:13:56 net2 /usr/local/bin/log-courier[30883]: [logstash3.dca.example.com:1234] Sending payload 6104f62e00055a969a15bcb39a2f941a (4096 events)
Sep 10 12:13:56 net2 /usr/local/bin/log-courier[30883]: [logstash3.dca.example.com:1234] Acknowledgement received for payload 6104f62e00055a969a15bcb39a2f941a sequence 4096
Sep 10 12:13:59 net2 /usr/local/bin/log-courier[30883]: [logstash3.dca.example.com:1234] Sending payload 732b19e8b1fc63c6c94693cf2b7c59d1 (4096 events)
Sep 10 12:14:00 net2 /usr/local/bin/log-courier[30883]: [logstash3.dca.example.com:1234] Acknowledgement received for payload 732b19e8b1fc63c6c94693cf2b7c59d1 sequence 4096
```
This information nicely showed me if the pushing to logstash is running fine, or if the logstash is throttling/slow - in that case sending 4096 events, and ack comes back for a lower number of events than that. 
Anyway, this information was provided in "debug" level, and, as there "debug" level wasn't very noisy, it was pretty good.
Now, with 2.6.2, the "debug" level sounds more like "TRACE" level, with almost constant I/O, especially this kind of information:
```
Sep 10 12:14:00 net2 /usr/local/bin/log-courier[30883]: &{0xc0000205d0 /var/log/sflow/sflow.log 0xc0002b4110 11 0 true 0 94832748 0xc0002a8340 <nil>}
Sep 10 12:14:00 net2 /usr/local/bin/log-courier[30883]: &{0xc0000205d0 /var/log/sflow/sflow.log 0xc0002b4110 11 0 true 0 94832748 0xc0002a8340 <nil>}
Sep 10 12:14:00 net2 /usr/local/bin/log-courier[30883]: &{0xc0000205d0 /var/log/sflow/sflow.log 0xc0002b4110 11 0 true 0 94832748 0xc0002a8340 <nil>}
Sep 10 12:14:00 net2 /usr/local/bin/log-courier[30883]: &{0xc0000205d0 /var/log/sflow/sflow.log 0xc0002b4110 11 0 true 0 94832748 0xc0002a8340 <nil>}
Sep 10 12:14:00 net2 /usr/local/bin/log-courier[30883]: &{0xc0000205d0 /var/log/sflow/sflow.log 0xc0002b4110 11 0 true 0 94832748 0xc0002a8340 <nil>}
Sep 10 12:14:00 net2 /usr/local/bin/log-courier[30883]: &{0xc0000205d0 /var/log/sflow/sflow.log 0xc0002b4110 11 0 true 0 94832748 0xc0002a8340 <nil>}
Sep 10 12:14:00 net2 /usr/local/bin/log-courier[30883]: &{0xc0000205d0 /var/log/sflow/sflow.log 0xc0002b4110 11 0 true 0 94832748 0xc0002a8340 <nil>}
Sep 10 12:14:00 net2 /usr/local/bin/log-courier[30883]: &{0xc0000205d0 /var/log/sflow/sflow.log 0xc0002b4110 11 0 true 0 94832748 0xc0002a8340 <nil>}
Sep 10 12:14:00 net2 /usr/local/bin/log-courier[30883]: &{0xc0000205d0 /var/log/sflow/sflow.log 0xc0002b4110 11 0 true 0 94832748 0xc0002a8340 <nil>}
```
That log file is pretty busy, and as you can see from these dozen log lines, i get preeeety much of debug information per second printed to on "debug" log level :( 
So, the question/request is: - is it possible to get the payload logs without all the trace level information? Either lowering down what's printer in "debug" level (by sending overload to "trace" level ? ), by having a separate flag in configuration which would send this payload info to "info" level, or something like that? :)

Thanks!

**Comment by driskell** [comment]
@sysmonk I think those logs with the ampersand were added for testing v2 and I never removed it. I will remove it in the next release and hopefully it'll restore logs to what it was 👍

**Comment by driskell** [comment]
Currently testing from the log-courier2-testing repository and if all good overnight I will tag up a release.

**Comment by driskell** [comment]
All looks good. I've gone through and improved logging in general so its more consistent. Things like TLS version and client/server names are also now logged. I've also started work on lc-admin to make it a little more interactive for monitoring rather than spamming `lc-admin status` which you might find useful instead of the logs.
