### ISSUE TITLE
lc-admin does not default to tcp transport

### ISSUE THREAD

**Issue by sysmonk** [driskell/log-courier#395]
The documentation [here](https://github.com/driskell/log-courier/blob/main/docs/AdministrationUtility.md#-connect
) says:
```If no transport name is specified, "tcp" is assumed.```
And even has a "transportless" example below ```127.0.0.1:1234```

But in reality, lc-admin still requirers to specify a transport:
```
~# lc-admin -connect :127.0.0.1:12345
Admin version 2.9.1

Setting up client for :127.0.0.1:12345...
Error: unknown transport specified for admin bind: ''
~# lc-admin -connect tcp:127.0.0.1:12345
Admin version 2.9.1

Setting up client for tcp:127.0.0.1:12345...
Detected remote Log Courier v2.9.0

~#
```

this if on v 2.9.1, but 2.9.0 was the same, didn't check the versions before.

**Comment by driskell** [comment]
Ah - you need to say `127.0.0.1:12345` instead of with the proceeding colon.
I can make it handle it though for next version. It was checking for the existence of only one colon rather than handling both formats and checking for an empty value
