### ISSUE TITLE
windows event log shipping

### ISSUE THREAD

**Issue by wyaeld** [driskell/log-courier#55]
Hi @driskell, I really like the improvements you've been doing.

One thing we found was missing from logstash-forwarder was the windows event log capability that was in logstash itself.

Now, logstash is too resource intensive for us to be comfortable deploying in on every machine we manage, but is that a capability you'd be comfortable adding to log-courier's roadmap?  I really don't want to run multiple agents, but anytime we have a windows machine we want both application & event logs.

**Comment by sidewinder12s** [comment]
Any update on this integration? This would be a show stopper for us also.

**Comment by driskell** [comment]
@sidewinder12s Not yet. I'll be sure to post here when there is one. It is low on my list of things though (I have no need of this myself.)

I'm not sure what you mean by show stopper. The show hasn't even started on this feature. If anyone does get the show started though I'll happily corroborate with any Pull Requests for this.

**Comment by sidewinder12s** [comment]
Thanks for the fast response!

As far as show stopper I just meant that it would stop me from using this on Windows as we need the Event log integration. Linux though, this looks really good. (have yet to play with it)

**Comment by mheese** [comment]
@sidewinder12s , @wyaeld  : the way you could do it is to use nxlog for windows event parsing - it is great at that and delivers quite well-formed events if used together with the json (or xml) extension. Then you can use the om_exec module in nxlog and start log-courier and feed it with stuff to stdin.

It is 2 programs unfortunately, but it should work.

**Comment by sidewinder12s** [comment]
@mheese Huh, that could be a good possibility. I'd have to play with it, but we were previously using NXlog but we cannot figure out how to turn off SSLv3, short of compiling from source. (Which we have also not been able to get working)

**Comment by Jakauppila** [comment]
I did come across this package today, would it help at all for this support?

https://godoc.org/code.google.com/p/winsvc/eventlog

**Comment by driskell** [comment]
@Jakauppila That package provides ability to Log to the Windows Events Log. It does not provide an ability to read from the Windows Event Log or register as a consumer. No Go library exists, to my knowledge, that uses the required function: EvtSubscribe, EvtQuery, EvtNext (https://msdn.microsoft.com/en-us/library/windows/desktop/aa385784(v=vs.85).aspx)
