### ISSUE TITLE
Docker container that creates deb package of log-courier

### ISSUE THREAD

**Issue by arep** [driskell/log-courier#58]
Hi
I have created a docker container that compiles log-courier and creates a deb package out of it.
It is usefull for those that don't want to install goland and ruby-dev etc on their server just to get log-courier up and running.

Here it is: https://registry.hub.docker.com/u/arep/log-courier/

**Comment by driskell** [comment]
I've been pondering and think the packaging and distribution documentation is quite large already. Will close this for now and maybe come back later once things are tidied up around 2.0. Thanks !
