### ISSUE TITLE
Rotated log files issue?

### ISSUE THREAD

**Issue by cova-fe** [driskell/log-courier#7]
Hi,
I'm using log-courier to get logs from files that are rotated hourly, using a symlink  to the current one, so the log dir is similar to this example:
log.current -> log.07
log.07
log.06
log.05 
[...]

in log.courier.conf I have the path pointing to log.current and "dead file": "1h"
what happens is that rotated files are still kept open by log-courier for hours (at least 20 or more). This puzzles me as it is not what I expected, I assumed files to be relaesed after 1 hour from rotation. Is this a (likely) my wrong astedsumption on log-courier behaviour or something not working in rotated log management by log-courier?
Thanks for any answer.

**Comment by angel-smile** [comment]
@cova-fe Do you need to run a cron job to create the symlink pointing to the current file? I'm doing this for rotated log files, but my problem is the file is not always rotated at exactly the same time every cycle. Do you have such issue?

**Comment by cova-fe** [comment]
@angel-smile  Unfortunately, I no longer have access to this specific setup, so I can't check if the issue you report appears also here...

**Comment by driskell** [comment]
@angel-smile My guess would be the logging program itself did the symlinking, or it was done using the logrotated scripts. Basically whatever did the rotation. We can work out something that works for you in #225
