### ISSUE TITLE
Errors in log-courier expluatation

### ISSUE THREAD

**Issue by neolithik** [driskell/log-courier#81]
Good afternoon during operation Log-carrier I ran into some number of CMV mistakes as I understand inhibit downloading data to a central server Logstash

2014/12/16 10:21:44.245051 Registry write failed: rename ./.log-courier.new ./.log-courier: no such file or directory
2014/12/16 10:22:22.256245 Registry write failed: rename ./.log-courier.new ./.log-courier: no such file or directory
2014/12/16 10:23:03.389117 Unexpected file truncation, seeking to beginning: /opt/logs/timing_t2/findRs_kas04_n9.log
2014/12/16 10:40:15.278237 Registry write failed: rename ./.log-courier.new ./.log-courier: no such file or directory
2014/12/16 10:44:19.565910 Registry write failed: rename ./.log-courier.new ./.log-courier: no such file or directory
2014/12/16 10:47:15.066623 Registry write failed: rename ./.log-courier.new ./.log-courier: no such file or directory
2014/12/16 10:54:55.243907 Registry write failed: rename ./.log-courier.new ./.log-courier: no such file or directory
2014/12/16 10:58:26.105044 Unexpected file truncation, seeking to beginning: /opt/logs/timing_t2/check_kas04_n9.log
2014/12/16 10:58:26.105479 Unexpected file truncation, seeking to beginning: /opt/logs/timing_t2/create_kas04_n9.log
2014/12/16 10:58:26.105557 Unexpected file truncation, seeking to beginning: /opt/logs/timing_t2/createTemplates_kas04_n9.log
2014/12/16 10:58:26.105606 Unexpected file truncation, seeking to beginning: /opt/logs/timing_t2/getPaymentsHistory_kas04_n9.log
2014/12/16 10:58:26.105645 Unexpected file truncation, seeking to beginning: /opt/logs/timing_t2/confirm_kas04_n9.log

I do not quite understand what they mean, but how can they be overcome?

**Comment by driskell** [comment]
I'll close this for now and assume it's not longer an issue. If you still have problems let me know your response to my last post. Thanks!

**Comment by blalor** [comment]
I ran into this problem; turns out I had two log-courier instances running. :-)
