### ISSUE TITLE
no more randomness in choosing servers?

### ISSUE THREAD

**Issue by sysmonk** [driskell/log-courier#82]
Hi,

I've recently updated my log-courier to ``Log Courier version 1.3.1.g1d79349`` and noticed that it does not choose servers randomly anymore...

Example:
```
Jan  6 22:03:05 smtp1 log-courier[26922]: Connected to x.x.x.x:9001 (logstash1)
Jan  6 22:06:36 smtp1 log-courier[28612]: Connected to x.x.x.x:9001 (logstash1)
Jan  6 22:11:06 smtp1 log-courier[30975]: Connected to x.x.x.x:9001 (logstash1)
Jan  6 22:14:36 smtp1 log-courier[680]: Connected to x.x.x.x:9001 (logstash1)
Jan  6 22:20:37 smtp1 log-courier[3904]: Connected to x.x.x.x:9001 (logstash1)
Jan  6 22:22:01 smtp1 log-courier[4585]: Connected to x.x.x.x:9001 (logstash1)
```

Config:
```
{
        "general": {
                "spool timeout": 5,
                "spool size": 128,
                "log level" : "debug",
                "log syslog" : true,
                "admin enabled": true,
                "admin listen address": "unix:/var/run/log-courier-admin.socket"
        },
        "network": {
                "servers": [ "logstash1:9001", "logstash2:9001", "logstash3:9001", "logstash4:9001" ],
                "ssl ca": "/usr/local/share/logstash/logstash.crt",
                "timeout": 60,
                "reconnect": 20,
                "max pending payloads": 5
        },
        "includes": [
                "/etc/log-courier.d/*.conf"
        ]
}
```

**Comment by sysmonk** [comment]
Any update on this? Are there any plans on changing this functionality, or should i start searching for a new log shipper?

**Comment by driskell** [comment]
>Any update on this?
I'm exploring solutions as I appreciate the use case.

The goal was to make the functionality deterministic, at least by default. The idea of a setting to enable randomly selecting the first connection looks like the best fit solution at the moment. I can't guarantee I'll have this looked at in the next week or two as I'm fairly busy.

>Are there any plans on changing this functionality, or should i start searching for a new log shipper?
I appreciate the frustration. I'll get to addressing this soon.

**Comment by sysmonk** [comment]
Thanks!
