### ISSUE TITLE
Problems integrating Log Courier with lostash

### ISSUE THREAD

**Issue by ashusheva** [driskell/log-courier#83]
I have downloaded log-courier-1.3 gem from ruby gems. But when I try to integrate it with logstash manually , I am getting the following error :-

```
C:\Logstash\logstash-1.4.0>java -jar vendor\jar\jruby-complete-1.7.11.jar -S g
em install log-courier-1.3.gem
Exception in thread "main" java.lang.UnsupportedClassVersionError: Bad version n
umber in .class file
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClassInternal(Unknown Source)
```

The commamd i used was:-

    java -jar vendor\jar\jruby-complete-1.7.11.jar -S gem install log-courier-1.3.gem

I have tried with jre version 1.7.0_03 and jre version 1.6.0_29. 

Is there any workaround on this?

**Comment by driskell** [comment]
Can you run "java -version" before the gem install? Just to check the Java it finds is indeed 6/7. I'll look more into it but everything I see so far is referring to old JVM.

**Comment by ashusheva** [comment]
When I run java-version, I get :-
java version "1.5.0_07"
Java(TM) 2 Runtime Environment, Standard Edition (build 1.5.0_07-b03)
Java HotSpot(TM) Client VM (build 1.5.0_07-b03, mixed mode)

However when I do echo %JAVA_HOME%, I get :- 
C:\ElasLatest\logstash-1.4.0>echo %JAVA_HOME%
C:\Program Files\Java\jdk1.7.0_03\jre

I don't understand. Are there some more environment variables to be defined?

**Comment by driskell** [comment]
JAVA_HOME sets the Java home directory where libraries are looked for, it doesn't set the version of Java to run or the path to the binary to run.

If you installed the Java yourself and not through an installer that might be why it does that. Maybe check system environment variable PATH has the newer jdk earlier in the PATH than the older one (or remove the older one.)

Either way, you could run java directly e.g: C:\Program Files\Java\jdk1.7.0_03\jre\bin\java
However, I would expect Logstash will run the default java and thus run 1.5, and potentially not work.

NB: @kvkram2405 Please raise a new issue, I won't answer that here. Also note that your apology is not an apology as it predates the act you are apologising for - if you knew it was wrong to post here, you shouldn't have posted.

Jason

**Comment by driskell** [comment]
@ashusheva I'll close this for now - since it's a Java installation issue I might not be much help if the above doesn't work - the Logstash Google Group might be a better place as there's many many more people active on there who could help out - I'm also on there too.

If you hit any other problems once the Java is sorted, feel free to open a new issue too.
