### ISSUE TITLE
Add DNS SRV record support

### ISSUE THREAD

**Issue by blalor** [driskell/log-courier#85]
Would you consider adding SRV record support when resolving server addresses?  I'd find that useful when using Consul for service discovery.

**Comment by driskell** [comment]
It sounds useful. How would the syntax look?

I know other systems like MTA and Kerberos default to SRV and use square brackets to switch to A record. Do you have a suggestion for syntax to use to switch to SRV record? I'm wondering AT sign (@) so you specify server as "@logstash.net" and it would lookup "_courier._tcp.logstash.net"?

**Comment by driskell** [comment]
Please give https://github.com/driskell/log-courier/pull/94 a try and let me know if it works OK

**Comment by driskell** [comment]
@blalor Are you able to try #94 and let me know if it is what you had in mind?

Thanks

**Comment by kadaan** [comment]
What about just allowing an external executable to be called to do the lookup.  That way any logic could be done.  For instance, we don't have SRV record support, but we have our own service catalog which we could lookup the logstash nodes in.

**Comment by driskell** [comment]
@kadaan I dont think that would work well. I can't recall any other app that would do such a thing and it would be quite a large overhead for me to maintain. The SRV isn't too bad and I do see it used elsewhere - and its just a variant on regular A lookups in DNS. Also Go provides libraries for it that reduce my overhead.

There's nothing preventing an external bash script being placed in sysconfig script though (if you use the init scripts) - that could perform lookups in advance and generate the config file. Of course it wouldn't be able to redo lookups whilst running though.

**Comment by kadaan** [comment]
@driskell Fair enough.  Is there a way to have the tcp connection closed after a certain number of calls (or time) so that VIPs (with load balancing built in) will be able to work their magic?

**Comment by driskell** [comment]
@kadaan Unfortunately not. Best way is to look at ZeroMQ transport as that will load balance for you. I'm working on a transport revamp though which will load balance TCP too.

Since SRV record is in, I'll close this now. Thanks.
