### ISSUE TITLE
Mechanism to monitor Log Courier Logstash input plugin

### ISSUE THREAD

**Issue by matthughes** [driskell/log-courier#86]
The lc-admin tool enables you to monitor the progress of the client.

Is there some mechanism to monitor the health of the server?   Use case is running logstash on multiple nodes behind a load balancer; ideally you'd be able to have some health check to indicate the server is still healthy.  The only way I can see is to use simple socket check: i.e., if running input plugin on port 9000, verify that you can connect to that port.  That doesn't really tell you much though.

**Comment by driskell** [comment]
You could write a stateful script to parse lc-admin status output, specifically Publisher section. IT shows connection status, how many successfully transmitted events, and how many events are awaiting transmission. From that info you can decide what is healthy and what isn't (which might differ in different emvironments.)

**Comment by matthughes** [comment]
Hmm, but lc-admin only runs on the client side.  I'm trying to determine the health of the input plugin running in logstash.

**Comment by driskell** [comment]
For logstash side there's not really a way yet. It's really something ideally should be built in to logstash, so it monitors all inputs and outputs etc.

Rather than plugin specific if I fid write something I'd try to work with them to make it built in to logstash. But I've no plans atm. Discussions and contributions are welcome though.

**Comment by driskell** [comment]
Thinking back I know people have written nagios and munin plugins etc that read events directly from elasticsearch. That tests the full pipeline then. If events not up to date it reports a failure. Logstash mailing list has some discussions on that.

A lc-admin like thing for logstash is a good idea tho for sure.

**Comment by sysmonk** [comment]
Yeah, that's a missing feature for me too :)
There are a few possible ways i currently see that doing 
1) use the metrics filter to collect X minute metrics on logstash side
2) nagios check to query ES directly

Tried doing 1) previously, but had some issues so i went to 2)
I currently do 2), although it has some drawbacks too - if 1 out of X logstash servers is broken, the other X-1 will still parse logs and it will show up as OK in nagios. But as far as i have up to date logs, i'm happy. When things go wrong, i can look at which LS is broken and restart it for it to cope up with the backlog of logs. I can share the script if needed, although everyone probably has his own requirements for it.

**Comment by dsolsona** [comment]
I have some logstash monitoring using the metrics filter, graphite and Nagios. 

On logstash I have

```filter {
  metrics {
    meter => "events"
    add_tag => "metric"
    flush_interval => 10
  }
}
...
...
output {
  if "metric" in [tags] {
    graphite {
      metrics => [ "stats.counts.logstash.graphite.events_rate.count", "%{events.rate_1m}" ]
      host    => "host"
    }
  }
}
```
With that you can monitor the indexing rate of logstash/elasticsearch. If the rate drop you can be sure there's some issue somewhere in the stack.

**Comment by driskell** [comment]
As this is best implemented in Logstash I'll mark as Help Wanted so others can offer their suggestions. It could be useful for contrib documentation too if I get around to it so feel free to share your methods!

**Comment by blalor** [comment]
I just implemented something like @dsolsona's solution.  You can easily measure rates by input with a little bit of metadata.  For example, I add a field named `input` to every input in Logstash; for courier I set it to `courer`.  You can use that to drive per-input metrics…

**Comment by rogerthat** [comment]
here is  a **very** simple nagios/icinga-plugin now, and i plan to extend it on request and needs.
at the moment you can detect if log-courier is running and/or connected and if some files are stale/dead

we have it running now and it is ok; suggestions please below in this thread

info: 

~~~ 

check_logcourier
    nagios_plugin to check log-courier, a cool logshipper for logstash
    log-courier is here: https://github.com/driskell/log-courier
    
USAGE
    check_logcourier -t [type] [options]
    
TYPES
    -t status   - global status
                  reads from Publisher/Prospector-Sections
                  warning if Prospector watched_files != active states
                  critical only if Status != Connected
                  -wp XX - warning if pending payloads >= XX (number) **
                  -cp YY - critical if pending payloads => YY (number) **
                  -wt XX - warning if timeouts >= XX (number) **
                  -ct YY - critical if timeouts >= XX (number) **
                  returns perfdata from Publisher 

    -t files    - check for state of transferred files; at the moment just
                  checks for file in FILES, if current offset == last eof offset
                  TODO: detect stale/dead files 

MISC Options
    -R          - suppress run_time informations
  
    -H [IP]     - Host/IP to connect to, default: 127.0.0.1
    -p [PORT]   - port to connect to (default: 1234 
  
    -d        debug
    -v        version
    -h        help

Examples
  
$ /etc/nagios/plugins/check_logcourier -t files

LCourier.FILES Warning Stale Logfile: /var/log/fire.log (stat:Dead) , /var/log/fire.log (no harvester), 
    /var/log/daemon.log[cur:3258615303/eof:3258611206], 
    /var/log/syslog[cur:5863560473/eof:5863556782], 
    /var/log/nginx/access.log (stat:Dead), /var/log/nginx/access.log (no harvester), 
    /var/log/kern.log[cur:7133542680/eof:7133533586], 
    /var/log/nginx/error.log (stat:Dead), 
    /var/log/nginx/error.log (no harvester) | run_time=29.10ms; 

$ /etc/nagios/plugins/check_logcourier 
LCourier.STATUS OK Shipper Connected | lps=48.18; pub_lines=14393869; pending=0; timeouts=1; retrans=0; watched_files=9; active_files=9; run_time=31.37ms; 

Requirements:
    - python 2.5 or later
    - python-yaml
    - log-courier (obviously)
    - lc-admin 

Remarks
    - ** -> not yet implemented 


~~~

**Comment by driskell** [comment]
Logstash is shortly introducing an API for monitoring and I plan to implement that. Will close now too as the repository for the input plugin has moved to driskell/logstash-input-courier
