### ISSUE TITLE
Git requirement in build

### ISSUE THREAD

**Issue by matthughes** [driskell/log-courier#87]
More of a curiosity than anything, but when I try to either build the gem or the client binary without git on my build machine, I get this:

```
go: missing Git command. See http://golang.org/s/gogetcmd
package github.com/op/go-logging: exec: "git": executable file not found in $PATH
make: *** [bin/log-courier] Error 1
```
What part of the build requires git and what part of git does it require?  I'm trying to build the 1.3 release zip, not the git checkout.

**Comment by driskell** [comment]
Log Courier uses a third party library for logging and part of the build process involves checking out that library's code from GitHub and building it. Go builder does this automatically - the Log Courier code just points to where it is.

In the future I may use other libraries or detach certain code into their own repositories if others may find it useful (I'm panning to do this for the async ZeroMQ code). This would then also need git installed to build.

Jason
