### ISSUE TITLE
log-courier log file output and log rotation

### ISSUE THREAD

**Issue by sysmonk** [driskell/log-courier#91]
Hi,

Tried to use the 'log file' output rather than syslog due to https://github.com/driskell/log-courier/issues/90 . It did help with the initial issue, but i don't see a way to rotate the logs of log-courier.
log-courier reload / kill -HUP does not re-open the new log file, it still tries to write to the old log-file.

```
                "log level" : "debug",
                "log syslog" : false,
                "log file": "/var/log/log-courier.log",
```

After kill -HUP it still has the old log file open:

```
# lsof -np 23224 | grep /var/log/log-cour
log-couri 23224 root    3u   REG                8,6   163628776    7211651 /var/log/log-courier.log.1 (deleted)
```

**Comment by driskell** [comment]
Yes the log file backend needs to reopen log file on reload.

I'll look into this as the logging library uses the golang logger underneath which doesn't allow it. But shouldn't be too hard to implement a minimal replacement that does.
