### ISSUE TITLE
NameError: uninitialized constant LogStash::Outputs::LogCourier::Client

### ISSUE THREAD

**Issue by dsolsona** [driskell/log-courier#96]
Hi,

I'm trying to setup  log-courier 1.3 between two logstash servers. One server is using the courier output while the other is using the courier input.

This is the output configuration
```
output {
  if "_grokparsefailure" not in [tags] and "metric" not in [tags] {
    courier {
      hosts => "aa.bb.cc.dd"
      port => "5044"
      ssl_ca => "/opt/logstash/ssl/cert.crt"
    }
  }
}
```
The input config looks like
```
input {
  courier {
  codec => json {}
    port => "5044"
    ssl_certificate => "/opt/logstash/ssl/cert.crt"
    ssl_key => "/opt/logstash/ssl/cert.key"
  }
}
```
And this is the error I get when I start logstash on the server with the output:

```
NameError: uninitialized constant LogStash::Outputs::LogCourier::Client
  const_missing at org/jruby/RubyModule.java:2690
       register at /opt/logstash/lib/logstash/outputs/courier.rb:56
           each at org/jruby/RubyArray.java:1613
   outputworker at /opt/logstash/lib/logstash/pipeline.rb:220
  start_outputs at /opt/logstash/lib/logstash/pipeline.rb:152
```

Any idea what could be wrong?

**Comment by driskell** [comment]
@dsolsona Can you check that the log-courier gem is installed ok?
If you replace the input with say, a generator, and just have the output , does it work?

Just need to rule out any gem install issue.

**Comment by driskell** [comment]
@dsolsona Can you check that the log-courier gem is installed ok?
If you replace the output with say, a stdout output, and just have the input, does it work?

Just need to rule out any gem install issue.

**Comment by driskell** [comment]
*Just updated my last comment I made a big typo!*

**Comment by dsolsona** [comment]
Yeah I also thought it could be related to an issue with the installed gem, because I was packaging the gem as a debian package with fpm and I was not sure I was doing it properly.

So I went and removed all the debian packages and gems from /opt/logstash/vendor/bundle/jruby/1.9 and installed the gem using the documentation example

``
java -jar vendor/jar/jruby-complete-1.7.11.jar -S gem install log-courier-1.3.gem
``

Then started logstash with the following config
```
input {
  generator {
    type => "courier"
    lines => "blahblah"
    count => 2000
  }
}

output {
  courier {
    hosts => "aa"
    codec => json {}
    port => "5044"
    ssl_ca => "cert.crt"
  }
}
```

But still seeing the same issue
```
Using milestone 1 output plugin 'courier'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.2-modified/plugin-milestones {:level=>:warn}
NameError: uninitialized constant LogStash::Outputs::LogCourier::Client
  const_missing at org/jruby/RubyModule.java:2690
       register at /opt/logstash/lib/logstash/outputs/courier.rb:56
           each at org/jruby/RubyArray.java:1613
   outputworker at /opt/logstash/lib/logstash/pipeline.rb:220
  start_outputs at /opt/logstash/lib/logstash/pipeline.rb:152
```

**Comment by driskell** [comment]
If you use the input does that work? As in, courier input without stdout output?

Just wondering if this is isolated to just the output plugin or if it's affecting the input plugin too.

**Comment by dsolsona** [comment]
The input does work and I have several servers sending logs to it. So this is isolated to just the output plugin which makes me thing that the gem was installed properly.

**Comment by driskell** [comment]
I can confirm this bug and have found the problem - it's a namespace conflict happening in the plugin. I'll push a fix up. Just update the plugin files (lib/logstash) and it should work - no need to update the log-courier plugin.

**Comment by dsolsona** [comment]
Thanks. It works as expected!

**Comment by korayal** [comment]
I had the same issue on 1.5.0.beta1, after renaming the class name, i started getting:

```
undefined method `[]=' for nil:NilClass
```
