### ISSUE TITLE
after SIGHUP log-courier does not release deleted files

### ISSUE THREAD

**Issue by gfa** [driskell/log-courier#99]
in our precise servers when logfiles are rotated log-courier keeps them open, it does not matter if i sent sighup to it, it won't release ultil i restart log-courier

$ ps -ef |grep log-c
root      5164     1  0 Jan12 ?        00:07:01 /usr/local/sbin/log-courier -config /etc/logstash/logstash-client.conf
root@ip-58-215-138-115:~# kill -HUP 5164

root@ip-58-215-138-115:~# lsof -n -p 5164
COMMAND    PID USER   FD   TYPE     DEVICE  SIZE/OFF    NODE NAME
log-couri 5164 root  cwd    DIR        8,1      4096       2 /
log-couri 5164 root  rtd    DIR        8,1      4096       2 /
log-couri 5164 root  txt    REG        8,1   6842584 1308590 /usr/local/sbin/log-courier
log-couri 5164 root  mem    REG        8,1   1811128  931480 /lib/x86_64-linux-gnu/libc-2.15.so
log-couri 5164 root  mem    REG        8,1    135366  931474 /lib/x86_64-linux-gnu/libpthread-2.15.so
log-couri 5164 root  mem    REG        8,1    149280  931385 /lib/x86_64-linux-gnu/ld-2.15.so
log-couri 5164 root    0u   CHR        1,3       0t0    1029 /dev/null
log-couri 5164 root    1u   CHR      136,3       0t0       6 /dev/pts/3
log-couri 5164 root    2u   CHR      136,3       0t0       6 /dev/pts/3
log-couri 5164 root    3u  IPv4  334871615       0t0     TCP 127.0.0.1:1234 (LISTEN)
log-couri 5164 root    4u  0000        0,9         0    7171 anon_inode
log-couri 5164 root    5r   REG        8,1  72577442 1049715 /var/log/upstart/nova-api.log.1 (deleted)
log-couri 5164 root    6r   REG        8,1  74403075 1050759 /var/log/nova/nova-api.log.1 (deleted)
log-couri 5164 root    7r   REG        8,1  74694666 1053196 /var/log/upstart/nova-api.log.1 (deleted)
log-couri 5164 root    8r   REG        8,1 934668409 1050824 /var/log/nova/nova-conductor.log.1 (deleted)
log-couri 5164 root    9r   REG        8,1 937271817 1050801 /var/log/upstart/nova-conductor.log.1 (deleted)
log-couri 5164 root   10r   REG        8,1    669696 1047404 /var/log/nova/nova-consoleauth.log
log-couri 5164 root   11r   REG        8,1    927348 1050891 /var/log/upstart/nova-consoleauth.log.1 (deleted)
log-couri 5164 root   12r   REG        8,1  72296939 1048501 /var/log/nova/nova-api.log.1 (deleted)
log-couri 5164 root   13r   REG        8,1 937227619 1050495 /var/log/nova/nova-conductor.log.1 (deleted)
log-couri 5164 root   14r   REG        8,1  72044747 1053904 /var/log/nova/nova-api.log.1 (deleted)
log-couri 5164 root   15r   REG        8,1    670289 1050863 /var/log/openvswitch/ovs-vswitchd.log.1 
[snip]

root@ip-58-215-138-115:~# lc-admin 
Log Courier version 1.1.28.gd11a1b4 client

Attempting connection to tcp:127.0.0.1:1234...
Connected

> help
Available commands:
  reload    Reload configuration
  status    Display the current shipping status
  exit      Exit
> reload
Configuration reload successful ---> it took some time until finish
> status
"State: /var/log/nova/nova-api.log (0xc208dcd200)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 0
    Current offset: 110
    Last EOF Offset: 0
    Status: Idle
    Dead timer: 8h16m12s
"State: /var/log/nova/nova-api.log (Orphan / 0xc208004a20)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 0
    Current offset: 56783231
    Last EOF Offset: 56783119
    Status: Idle
    Dead timer: 0s
"State: /var/log/nova/nova-api.log (Orphan / 0xc208005920)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 0
    Current offset: 112
    Last EOF Offset: 0
    Status: Idle
    Dead timer: 0s
"State: /var/log/nova/nova-api.log (Orphan / 0xc208005980)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 0
    Current offset: 112
    Last EOF Offset: 0
    Status: Idle
    Dead timer: 0s
"State: /var/log/nova/nova-api.log (Orphan / 0xc208d40060)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 0
    Current offset: 112
    Last EOF Offset: 0
    Status: Idle
    Dead timer: 0s
"State: /var/log/nova/nova-api.log (Orphan / 0xc208d40240)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 0
    Current offset: 112
    Last EOF Offset: 0
    Status: Idle
    Dead timer: 0s
"State: /var/log/nova/nova-api.log (Orphan / 0xc208d41560)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 0
    Current offset: 112
    Last EOF Offset: 0
    Status: Idle
    Dead timer: 0s
"State: /var/log/nova/nova-api.log (Orphan / 0xc208d41c20)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 0
    Current offset: 112
    Last EOF Offset: 0
    Status: Idle
    Dead timer: 0s
"State: /var/log/nova/nova-api.log (Orphan / 0xc208dcc420)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 0
    Current offset: 112
    Last EOF Offset: 0
    Status: Idle
    Dead timer: 0s
"State: /var/log/nova/nova-api.log (Orphan / 0xc208ee8ae0)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 0
    Current offset: 112
    Last EOF Offset: 0
    Status: Idle
    Dead timer: 0s
"State: /var/log/nova/nova-api.log (Orphan / 0xc208ee92c0)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 0
    Current offset: 189
    Last EOF Offset: Never
    Status: Alive
"State: /var/log/nova/nova-cert.log (0xc208d41e00)":
  Status: Dead
"State: /var/log/nova/nova-cert.log (Orphan / 0xc208004ba0)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 0
    Current offset: 147
    Last EOF Offset: Never
    Status: Alive
"State: /var/log/nova/nova-conductor.log (0xc208dcca80)":
  Status: Running
  Harvester:
    Speed (Lps): 0.00
    Speed (Bps): 0.00
    Processed lines: 0
    Current offset: 1316
    Last EOF Offset: Never
    Status: Alive
"State: /var/log/nova/nova-conductor.log (Orphan / 0xc208004a80)":
  Status: Running
  Harvester:
    Speed (Lps): 80.00
    Speed (Bps): 28124.00
    Processed lines: 80
    Current offset: 699161818
    Last EOF Offset: 699160505
    Status: Idle
    Dead timer: 0s
[snip]

root@ip-58-215-138-115:~# lsof -n -p 5164
COMMAND    PID USER   FD   TYPE     DEVICE  SIZE/OFF    NODE NAME
log-couri 5164 root  cwd    DIR        8,1      4096       2 /
log-couri 5164 root  rtd    DIR        8,1      4096       2 /
log-couri 5164 root  txt    REG        8,1   6842584 1308590 /usr/local/sbin/log-courier
log-couri 5164 root  mem    REG        8,1   1811128  931480 /lib/x86_64-linux-gnu/libc-2.15.so
log-couri 5164 root  mem    REG        8,1    135366  931474 /lib/x86_64-linux-gnu/libpthread-2.15.so
log-couri 5164 root  mem    REG        8,1    149280  931385 /lib/x86_64-linux-gnu/ld-2.15.so
log-couri 5164 root    0u   CHR        1,3       0t0    1029 /dev/null
log-couri 5164 root    1u   CHR      136,3       0t0       6 /dev/pts/3
log-couri 5164 root    2u   CHR      136,3       0t0       6 /dev/pts/3
log-couri 5164 root    3u  IPv4  334871615       0t0     TCP 127.0.0.1:1234 (LISTEN)
log-couri 5164 root    4u  0000        0,9         0    7171 anon_inode
log-couri 5164 root    5r   REG        8,1  72577442 1049715 /var/log/upstart/nova-api.log.1 (deleted)
log-couri 5164 root    6r   REG        8,1  74403075 1050759 /var/log/nova/nova-api.log.1 (deleted)
log-couri 5164 root    7r   REG        8,1  74694666 1053196 /var/log/upstart/nova-api.log.1 (deleted)
log-couri 5164 root    8r   REG        8,1 934668409 1050824 /var/log/nova/nova-conductor.log.1 (deleted)
log-couri 5164 root    9r   REG        8,1 937271817 1050801 /var/log/upstart/nova-conductor.log.1 (deleted)
log-couri 5164 root   10r   REG        8,1    669899 1047404 /var/log/nova/nova-consoleauth.log
log-couri 5164 root   11r   REG        8,1    927348 1050891 /var/log/upstart/nova-consoleauth.log.1 (deleted)
log-couri 5164 root   12r   REG        8,1  72296939 1048501 /var/log/nova/nova-api.log.1 (deleted)
log-couri 5164 root   13r   REG        8,1 937227619 1050495 /var/log/nova/nova-conductor.log.1 (deleted)
log-couri 5164 root   14r   REG        8,1  72044747 1053904 /var/log/nova/nova-api.log.1 (deleted)

log-courier -version
Log Courier version 1.1.28.gd11a1b4

we have workaround it restarting it every night after logrotate, so is not a big concern for us right now

thanks anyway for this great software

**Comment by gfa** [comment]
built using 
go version go1.3.2 linux/amd64

**Comment by driskell** [comment]
Hi @gfa 
Thanks for the feedback :-)

This is intended. Just because the log file was rotated, there's no guarantee that the application originally logging to it has stopped logging. For instance, Nginx will sometimes still be logging to it up to 5 minutes after log rotation if there are old processes that are still processing requests (the access log gets written after completion of the request.) As a result, Log Courier will keep hold of the file until modifications cease for a defined period of time.

The default is 24h (inherited from Logstash forwarder) - if the file contents don't change for 24 hours, the file is closed (if it's deleted, this releases it completely and free disk space.)

This can be configured to something lower, say 1h, with the [`dead time` configuration](docs/Configuration.md#dead-time). At some point in the future I'll probably reduce this dead time down to a more sane default.

Jason

**Comment by gfa** [comment]
documentation for dead time and reloading wasn't so clear about it, at least when i read it before knowing 'the truth'  :confused: 

thank you for taking the time to respond.

**Comment by driskell** [comment]
You make a valid point. I can see that when one generally thinks about "reloading" we see that as reloading log files as well, as nearly all other applications do that.

I'll reopen and mark to update documentation. Specifically, I'll mark in the "Reload Configuration" section that watched log files are not reopened, only Log Couriers own log file (`"log file"` setting) is reopened. I'll also mention reopen of watched log files is controlled by `"dead time"` only. Does this sound OK?

**Comment by gfa** [comment]
yes, it does sound good
